#! /usr/bin/gawk -f

BEGIN {
    print "<?xml version='1.0' encoding='utf-8'?>"
    print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\""
    print "        \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">"
    print "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">"
    print "<head>"
    print "    <meta http-equiv=\"Content-Type\" content=\"application/xhtml+xml; charset=utf-8\" />"
    print "    <meta name=\"content-language\" content=\"en\"/>"
    print "    <link rel=\"shortcut icon\" href=\"favicon.png\" type=\"image/png\"/>"
    print "    <title>" TITLE "</title>"
    print "</head>"
    print "<body>"
    print "    <div style=\"text-align: center\">"
    print "        <a href=\"index.html\"><img src=\"logo.png\" width=\"309\" height=\"83\" alt=\"\"/></a>"
    print "        <br/><i>Moravia Microsystems, s.r.o.</i><br/><br/>"
    print "    </div>"
    print "    <div style=\"font-size: 14px; font-family: DejaVu Sans Mono, Monospace, Courier New\">"
}

END {
    print "    </div>"
    print "    <div style=\"text-align: center\">"
    print "        <br/><br/>"
    print "        <hr style=\"width: 90%; margin: 0 auto; color: maroon\"/><br/>"
    print "        Generated by TestLog2html.awk on " strftime ( "%c", systime() ) "."
    print "    </div>"
    print "</body>"
    print "</html>"
}

{
    gsub ( /&/,  "\\&amp;",   $0 )
    gsub ( />/,  "\\&gt;",    $0 )
    gsub ( /</,  "\\&lt;",    $0 )
    gsub ( /  /, " \\&nbsp;", $0 )

    print ( $0 "<br/>" )
}
