ATMEL: main.c File Reference
main.c File Reference
#include "config.h"
#include "modules/scheduler/scheduler.h"
#include "lib_mcu/wdt/wdt_drv.h"
#include "lib_mcu/power/power_drv.h"
#include "lib_mcu/usb/usb_drv.h"
#include "lib_mcu/util/start_boot.h"
Functions
int main (void)
Procedure to speed up the startup code
This one increment the CPU clock before RAM initialisation
char __low_level_init ()
Detailed Description
Main for USB application.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: ATmega32U4
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file main.c.
Function Documentation
int main (void)
Definition at line 93 of file main.c.
References Clear_prescaler, scheduler(), start_boot_if_required(), Usb_enable_regulator, and wdtdrv_disable().
{
   Usb_enable_regulator();
   wdtdrv_disable();
   start_boot_if_required();
   Clear_prescaler();
   scheduler();
   return 0;
}
char __low_level_init ()
Definition at line 115 of file main.c.
References Clear_prescaler.
{
  Clear_prescaler();
  return 1;
}