#! /bin/bash

# ======================================================================================================================
#
# This script converts Moravia Micorsystems' license key (RSA private key) from PEM format to raw binary ANS.1 BER (DER)
# encoded public key represented as C language static array defined with initializer list filled with hexadecimal
# values.
#
# SW dependencies: "openssl", and "od".
#
# (C) copyright 2013, 2014 Moravia Microsystems, s.r.o.
#
# author: Martin Ošmera <martin.osmera@moravia-microsystems.com>
#
# ======================================================================================================================

openssl rsa -in "${1}" -pubout -outform DER 2>/dev/null | od --format=x1 --address-radix=n | gawk -O '
    BEGIN {
        size = 0
    }

    END {
        print ( "// This file was automatically generated by script \"keygen.sh\"." )
        print ( "" )
        print ( "#ifndef LICENSECERTIFICATEKEY_H" )
        print ( "#define LICENSECERTIFICATEKEY_H" )
        print ( "" )
        print ( "static const unsigned char LicenseCertificateKey [ " size " ] =" )
        print ( "{" )

        idx = 0
        while ( idx < size ) {
            printf ( "    " )

            for ( i = 0; i < 16; i++ ) {
                if ( idx >= size ) {
                    break
                }

                if ( 0 != i ) {
                    printf ( ", " )
                }

                printf ( "0x" data[idx++] )
            }

            if ( idx < size ) {
                print ( "," )
            } else {
                print ( "" )
            }
        }

        print ( "};" )
        print ( "" )
        print ( "#endif // LICENSECERTIFICATEKEY_H" )
    }

    {
        for ( i = 1; i <= NF; i++ ) {
            data[size] = $i
            size++
        }
    }
' > "LicenseCertificateKey.h"
