MT_WARNING: 002_arithmetics.asm:14.20-14.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:15.20-15.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:16.20-16.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:17.20-17.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:18.20-18.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:19.20-19.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:20.20-20.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:21.20-21.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:22.20-22.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:23.20-23.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:24.20-24.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:25.20-25.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:28.20-28.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:29.20-29.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:30.20-30.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:31.20-31.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:32.20-32.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:33.20-33.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:34.20-34.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:35.20-35.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:36.20-36.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:37.20-37.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:38.20-38.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:39.20-39.22: Warning: instruction `ADDCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:42.20-42.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:43.20-43.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:44.20-44.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:45.20-45.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:46.20-46.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:47.20-47.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:48.20-48.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:49.20-49.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:50.20-50.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:51.20-51.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:52.20-52.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:53.20-53.22: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:56.20-56.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:57.20-57.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:58.20-58.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:59.20-59.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:60.20-60.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:61.20-61.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:62.20-62.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:63.20-63.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:64.20-64.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:65.20-65.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:66.20-66.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:67.20-67.22: Warning: instruction `SUBCY sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:70.20-70.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:71.20-71.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:72.20-72.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:73.20-73.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:74.20-74.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:75.20-75.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:76.20-76.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:77.20-77.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:78.20-78.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:79.20-79.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:80.20-80.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:81.20-81.22: Warning: instruction `COMPARE sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:83.21-83.23: Warning: instruction `ADD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:83.24-83.26: Warning: instruction `ADD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:84.21-84.23: Warning: instruction `ADDCY sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:84.24-84.26: Warning: instruction `ADDCY sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:85.21-85.23: Warning: instruction `SUB sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:85.24-85.26: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:86.21-86.23: Warning: instruction `SUBCY sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:86.24-86.34: Warning: instruction `SUBCY sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:87.21-87.23: Warning: instruction `COMPARE sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 002_arithmetics.asm:87.24-87.34: Warning: instruction `COMPARE sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: Warning: exact device not specified, using KCPSM6 by default.
MT_ERROR: 002_arithmetics.asm:16.24-16.26: Error: symbol not defined: `O5'.
MT_ERROR: 002_arithmetics.asm:30.24-30.26: Error: symbol not defined: `O5'.
MT_ERROR: 002_arithmetics.asm:44.24-44.26: Error: symbol not defined: `O5'.
MT_ERROR: 002_arithmetics.asm:58.24-58.26: Error: symbol not defined: `O5'.
MT_ERROR: 002_arithmetics.asm:72.24-72.26: Error: symbol not defined: `O5'.
MT_ERROR: 002_arithmetics.asm:86.24-86.34: Error: symbol not defined: `TESTSYMB10'.
MT_ERROR: 002_arithmetics.asm:87.24-87.34: Error: symbol not defined: `TESTSYMB11'.
