MT_ERROR: 007_SCRATCHPAD_ram.asm:37.32-37.34: Error: identifier cannot start with a digit: `8E'.
MT_ERROR: 007_SCRATCHPAD_ram.asm:37.32-38.1: Error: unexpected end of line.
MT_ERROR: 007_SCRATCHPAD_ram.asm:55.37-55.39: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 007_SCRATCHPAD_ram.asm:55.37-56.1: Error: unexpected end of line.
MT_ERROR: 007_SCRATCHPAD_ram.asm:61.39-61.41: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 007_SCRATCHPAD_ram.asm:61.39-62.1: Error: unexpected end of line.
MT_WARNING: Warning: semantic analysis was not executed due to error(s).
