MT_ERROR: 009_asm_SPI.asm:2.24-2.30: Error: symbol not defined: `_PIGGY'.
MT_ERROR: 009_asm_SPI.asm:2.33-2.38: Error: symbol not defined: `_I2C0'.
MT_ERROR: 009_asm_SPI.asm:3.24-3.30: Error: symbol not defined: `_PIGGY'.
MT_ERROR: 009_asm_SPI.asm:3.33-3.38: Error: symbol not defined: `_I2C0'.
MT_ERROR: 009_asm_SPI.asm:4.24-4.30: Error: symbol not defined: `_PIGGY'.
MT_ERROR: 009_asm_SPI.asm:4.33-4.38: Error: symbol not defined: `_I2C1'.
MT_ERROR: 009_asm_SPI.asm:5.24-5.30: Error: symbol not defined: `_PIGGY'.
MT_ERROR: 009_asm_SPI.asm:5.33-5.38: Error: symbol not defined: `_I2C2'.
MT_ERROR: 009_asm_SPI.asm:6.24-6.30: Error: symbol not defined: `_PIGGY'.
MT_ERROR: 009_asm_SPI.asm:6.33-6.38: Error: symbol not defined: `_I2C3'.
MT_WARNING: 009_asm_SPI.asm:16.28-16.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:17.28-17.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:27.26-27.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:28.25-28.27: Warning: instruction `SL0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:32.26-32.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:37.26-37.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:38.25-38.27: Warning: instruction `SL1 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:44.26-44.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:48.26-48.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:52.26-52.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:56.26-56.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:65.26-65.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:66.25-66.27: Warning: instruction `SL0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:70.26-70.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:74.26-74.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:78.26-78.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:90.26-90.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:91.25-91.27: Warning: instruction `SL1 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:97.26-97.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:101.26-101.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:110.26-110.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:111.25-111.27: Warning: instruction `SL0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:115.26-115.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:119.26-119.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:131.26-131.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:132.25-132.27: Warning: instruction `SL1 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:140.26-140.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:150.26-150.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:151.25-151.27: Warning: instruction `SL0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:155.26-155.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:165.26-165.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:168.25-168.27: Warning: instruction `SL0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:171.28-171.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:175.28-175.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:179.28-179.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:183.28-183.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:185.25-185.27: Warning: instruction `SUB sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:185.29-185.30: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:193.26-193.28: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:195.28-195.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:199.28-199.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:202.25-202.27: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:204.25-204.27: Warning: instruction `SR0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:205.25-205.27: Warning: instruction `SLA sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:206.28-206.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:208.25-208.27: Warning: instruction `SUB sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:208.29-208.30: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:217.28-217.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:219.28-219.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:223.28-223.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:225.28-225.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:233.28-233.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:235.28-235.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:239.28-239.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:241.28-241.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:249.28-249.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:251.28-251.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:255.28-255.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:267.28-267.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:270.28-270.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:272.28-272.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:281.28-281.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 009_asm_SPI.asm:283.28-283.30: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: Warning: exact device not specified, using KCPSM6 by default.
MT_ERROR: 009_asm_SPI.asm:16.28-16.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:17.28-17.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:18.25-18.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:27.26-27.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:27.30-27.32: Error: symbol not defined: `S0'.
MT_ERROR: 009_asm_SPI.asm:28.25-28.27: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:32.26-32.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:32.30-32.32: Error: symbol not defined: `S1'.
MT_ERROR: 009_asm_SPI.asm:37.26-37.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:37.30-37.32: Error: symbol not defined: `S0'.
MT_ERROR: 009_asm_SPI.asm:38.25-38.27: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:44.26-44.28: Error: symbol not defined: `S2'.
MT_ERROR: 009_asm_SPI.asm:44.30-44.32: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:48.26-48.28: Error: symbol not defined: `S3'.
MT_ERROR: 009_asm_SPI.asm:48.30-48.32: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:52.26-52.28: Error: symbol not defined: `S4'.
MT_ERROR: 009_asm_SPI.asm:52.30-52.32: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:56.26-56.28: Error: symbol not defined: `S5'.
MT_ERROR: 009_asm_SPI.asm:56.30-56.32: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:65.26-65.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:65.30-65.32: Error: symbol not defined: `S0'.
MT_ERROR: 009_asm_SPI.asm:66.25-66.27: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:70.26-70.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:70.30-70.32: Error: symbol not defined: `S1'.
MT_ERROR: 009_asm_SPI.asm:74.26-74.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:74.30-74.32: Error: symbol not defined: `S2'.
MT_ERROR: 009_asm_SPI.asm:78.26-78.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:78.30-78.32: Error: symbol not defined: `S3'.
MT_ERROR: 009_asm_SPI.asm:90.26-90.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:90.30-90.32: Error: symbol not defined: `S0'.
MT_ERROR: 009_asm_SPI.asm:91.25-91.27: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:97.26-97.28: Error: symbol not defined: `S2'.
MT_ERROR: 009_asm_SPI.asm:97.30-97.32: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:101.26-101.28: Error: symbol not defined: `S3'.
MT_ERROR: 009_asm_SPI.asm:101.30-101.32: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:110.26-110.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:110.30-110.32: Error: symbol not defined: `S0'.
MT_ERROR: 009_asm_SPI.asm:111.25-111.27: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:115.26-115.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:115.30-115.32: Error: symbol not defined: `S1'.
MT_ERROR: 009_asm_SPI.asm:119.26-119.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:119.30-119.32: Error: symbol not defined: `S2'.
MT_ERROR: 009_asm_SPI.asm:131.26-131.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:131.30-131.32: Error: symbol not defined: `S0'.
MT_ERROR: 009_asm_SPI.asm:132.25-132.27: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:140.26-140.28: Error: symbol not defined: `S2'.
MT_ERROR: 009_asm_SPI.asm:140.30-140.32: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:150.26-150.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:150.30-150.32: Error: symbol not defined: `S0'.
MT_ERROR: 009_asm_SPI.asm:151.25-151.27: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:155.26-155.28: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:155.30-155.32: Error: symbol not defined: `S1'.
MT_ERROR: 009_asm_SPI.asm:165.26-165.28: Error: symbol not defined: `SD'.
MT_ERROR: 009_asm_SPI.asm:167.25-167.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:168.25-168.27: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:171.28-171.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:172.25-172.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:175.28-175.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:176.25-176.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:179.28-179.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:180.25-180.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:181.25-181.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:182.25-182.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:183.28-183.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:185.25-185.27: Error: symbol not defined: `SD'.
MT_ERROR: 009_asm_SPI.asm:187.25-187.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:193.26-193.28: Error: symbol not defined: `SD'.
MT_ERROR: 009_asm_SPI.asm:194.25-194.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:195.28-195.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:198.25-198.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:199.28-199.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:200.25-200.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:201.25-201.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:202.25-202.27: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:203.25-203.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:204.25-204.27: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:205.25-205.27: Error: symbol not defined: `SC'.
MT_ERROR: 009_asm_SPI.asm:206.28-206.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:207.25-207.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:208.25-208.27: Error: symbol not defined: `SD'.
MT_ERROR: 009_asm_SPI.asm:216.25-216.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:217.28-217.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:218.25-218.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:219.28-219.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:220.25-220.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:221.25-221.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:222.25-222.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:223.28-223.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:224.25-224.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:225.28-225.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:232.25-232.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:233.28-233.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:234.25-234.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:235.28-235.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:236.25-236.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:237.25-237.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:238.25-238.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:239.28-239.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:240.25-240.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:241.28-241.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:248.25-248.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:249.28-249.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:250.25-250.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:251.28-251.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:252.25-252.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:253.25-253.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:254.25-254.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:255.28-255.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:256.25-256.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:266.25-266.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:267.28-267.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:269.25-269.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:270.28-270.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:271.25-271.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:272.28-272.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:273.25-273.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:280.25-280.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:281.28-281.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:282.25-282.30: Error: symbol not defined: `DELAY'.
MT_ERROR: 009_asm_SPI.asm:283.28-283.30: Error: symbol not defined: `SF'.
MT_ERROR: 009_asm_SPI.asm:284.25-284.30: Error: symbol not defined: `DELAY'.
