                   1
  00002            2     bSDA_In         EQU    _PIGGY + _I2C0          ; gets SDA level in Bit0
E: symbol not defined: `_PIGGY'.
E: symbol not defined: `_I2C0'.
  00002            3     bSDA_0          EQU    _PIGGY + _I2C0          ; Pulls SDA to 0
E: symbol not defined: `_PIGGY'.
E: symbol not defined: `_I2C0'.
  00002            4     bSDA_Z          EQU    _PIGGY + _I2C1          ; Relases SDA to float to 1
E: symbol not defined: `_PIGGY'.
E: symbol not defined: `_I2C1'.
  00002            5     bSCL_0          EQU    _PIGGY + _I2C2          ; Pulls CSCL to 0
E: symbol not defined: `_PIGGY'.
E: symbol not defined: `_I2C2'.
  00002            6     bSCL_Z          EQU    _PIGGY + _I2C3          ; Releases SCL to float to 1
E: symbol not defined: `_PIGGY'.
E: symbol not defined: `_I2C3'.
                   7
                   8     ; ---\              /--------\                                            /--
                   9     ;     \  SDA       /          \                                          /
                  10     ;      \----------/ \--------/ \----------------------------------------/
                  11     ; -------\            /----\                                         /-------
                  12     ;         \  SCL     /      \                                       /
                  13     ;          \--------/        \-------------------------------------/
                  14     ; | Start    |      Data bit     |                             |  Stop     |
                  15
000 2D102         16     Init_I2C:       OUTPUT     sF, bSDA_Z              ; SDA = Z
E: symbol not defined: `SF'.
001 2D102         17                     OUTPUT     sF, bSCL_Z              ; SCL = Z
E: symbol not defined: `SF'.
002 22001         18                     JUMP    Delay
E: symbol not defined: `DELAY'.
                  19
                  20
                  21     ; -------------------------------------------------------------------------------
                  22     ; Routine to set up for and read four bytes from I2C device
                  23     ; -------------------------------------------------------------------------------
                  24
                  25     ReadWrite4_I2C:
003 2009A         26                     CALL    I2C_Start               ; Send Start, control byte and ack
004 09101         27                     INPUT    sC, s0                  ; Load device code for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S0'.
005 14106         28                     SL0     sC                      ; add write flag
E: symbol not defined: `SC'.
006 20057         29                     CALL    I2C_Xmit                ; Send address and ack
007 2008E         30                     CALL    I2C_SAck
                  31
008 09101         32                     INPUT    sC, s1                  ; Load data for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S1'.
009 20057         33                     CALL    I2C_Xmit                ; Send data and ack
00A 2008E         34                     CALL    I2C_SAck
                  35
00B 20098         36                     CALL    I2C_RepStart            ; Send repeated start, control byte and ack
00C 09101         37                     INPUT    sC, s0                  ; Load device code for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S0'.
00D 14107         38                     SL1     sC                      ; add read flag
E: symbol not defined: `SC'.
00E 20057         39                     CALL    I2C_Xmit                ; Send address and ack
00F 2008E         40                     CALL    I2C_SAck
                  41
010 20068         42                     CALL    I2C_Recv                ; Read 8 bits of data and send ack
011 20078         43                     CALL    I2C_MAck
012 09101         44                     INPUT    s2, sC
E: symbol not defined: `S2'.
E: symbol not defined: `SC'.
                  45
013 20068         46                     CALL    I2C_Recv                ; Read next 8 bits of data and send ack
014 20078         47                     CALL    I2C_MAck
015 09101         48                     INPUT    s3, sC
E: symbol not defined: `S3'.
E: symbol not defined: `SC'.
                  49
016 20068         50                     CALL    I2C_Recv                ; Read 8 bits of data and send ack
017 20078         51                     CALL    I2C_MAck
018 09101         52                     INPUT    s4, sC
E: symbol not defined: `S4'.
E: symbol not defined: `SC'.
                  53
019 20068         54                     CALL    I2C_Recv                ; Read next 8 bits of data and send ack
01A 20083         55                     CALL    I2C_MNAck
01B 09101         56                     INPUT    s5, sC
E: symbol not defined: `S5'.
E: symbol not defined: `SC'.
                  57
01C 220A0         58                     JUMP    I2C_Stop                ; Send Stop
                  59
                  60     ; -------------------------------------------------------------------------------
                  61     ; Routine to set up for and write two bytes to I2C device
                  62     ; -------------------------------------------------------------------------------
                  63     Write3_I2C:
01D 2009A         64                     CALL    I2C_Start               ; Send Start, control byte and ack
01E 09101         65                     INPUT    sC, s0                  ; Load device code for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S0'.
01F 14106         66                     SL0     sC                      ; add write flag
E: symbol not defined: `SC'.
020 20057         67                     CALL    I2C_Xmit                ; Send address and ack
021 2008E         68                     CALL    I2C_SAck
                  69
022 09101         70                     INPUT    sC, s1                  ; Load data for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S1'.
023 20057         71                     CALL    I2C_Xmit                ; Send data and ack
024 2008E         72                     CALL    I2C_SAck
                  73
025 09101         74                     INPUT    sC, s2                  ; Load data for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S2'.
026 20057         75                     CALL    I2C_Xmit                ; Send data and ack
027 2008E         76                     CALL    I2C_SAck
                  77
028 09101         78                     INPUT    sC, s3                  ; Load data for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S3'.
029 20057         79                     CALL    I2C_Xmit                ; Send data and ack
02A 2008E         80                     CALL    I2C_SAck
                  81
02B 220A0         82                     JUMP    I2C_Stop                ; Send stop
                  83
                  84     ; -------------------------------------------------------------------------------
                  85     ; Routine to set up for and read two bytes from I2C device
                  86     ; -------------------------------------------------------------------------------
                  87
                  88     Read2_I2C:
02C 2009A         89                     CALL    I2C_Start               ; Send start, control byte and ack
02D 09101         90                     INPUT    sC, s0                  ; Load device code for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S0'.
02E 14107         91                     SL1     sC                      ; add read flag
E: symbol not defined: `SC'.
02F 20057         92                     CALL    I2C_Xmit                ; Send address and ack
030 2008E         93                     CALL    I2C_SAck
                  94
031 20068         95                     CALL    I2C_Recv                ; Read 8 bits of data and send ack
032 20078         96                     CALL    I2C_MAck
033 09101         97                     INPUT    s2, sC
E: symbol not defined: `S2'.
E: symbol not defined: `SC'.
                  98
034 20068         99                     CALL    I2C_Recv                ; Read next 8 bits of data and send ack
035 20083        100                     CALL    I2C_MNAck
036 09101        101                     INPUT    s3, sC
E: symbol not defined: `S3'.
E: symbol not defined: `SC'.
                 102
037 220A0        103                     JUMP    I2C_Stop                ; Send Stop
                 104
                 105     ; -------------------------------------------------------------------------------
                 106     ; Routine to set up for and write two bytes to I2C device
                 107     ; -------------------------------------------------------------------------------
                 108     Write2_I2C:
038 2009A        109                     CALL    I2C_Start               ; Send Start, control byte and ack
039 09101        110                     INPUT    sC, s0                  ; Load device code for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S0'.
03A 14106        111                     SL0     sC                      ; add write flag
E: symbol not defined: `SC'.
03B 20057        112                     CALL    I2C_Xmit                ; Send address and ack
03C 2008E        113                     CALL    I2C_SAck
                 114
03D 09101        115                     INPUT    sC, s1                  ; Load data for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S1'.
03E 20057        116                     CALL    I2C_Xmit                ; Send data and ack
03F 2008E        117                     CALL    I2C_SAck
                 118
040 09101        119                     INPUT    sC, s2                  ; Load data for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S2'.
041 20057        120                     CALL    I2C_Xmit                ; Send data and ack
042 2008E        121                     CALL    I2C_SAck
                 122
043 220A0        123                     JUMP    I2C_Stop                ; Send stop
                 124
                 125     ; -------------------------------------------------------------------------------
                 126     ; Routine to set up for and read one byte of I2C device
                 127     ; -------------------------------------------------------------------------------
                 128     Read1_I2C:
                 129
044 2009A        130                     CALL    I2C_Start               ; Send start, control byte and ack
045 09101        131                     INPUT    sC, s0                  ; Load address for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S0'.
046 14107        132                     SL1     sC                      ; add read flag
E: symbol not defined: `SC'.
047 20057        133                     CALL    I2C_Xmit                ; Send address and ack
048 2008E        134                     CALL    I2C_SAck
                 135
049 2009A        136                     CALL    I2C_Start               ; Send start, control byte and ack
                 137
04A 20068        138                     CALL    I2C_Recv                ; Read 8 bits of data and send ack
04B 20083        139                     CALL    I2C_MNAck
04C 09101        140                     INPUT    s2, sC
E: symbol not defined: `S2'.
E: symbol not defined: `SC'.
                 141
04D 220A0        142                     JUMP    I2C_Stop                ; Send Stop
                 143
                 144     ; -------------------------------------------------------------------------------
                 145     ; Routine to set up for and write one byte to I2C device
                 146     ; -------------------------------------------------------------------------------
                 147     Write1_I2C:
                 148
04E 2009A        149                     CALL    I2C_Start               ; Send Start, control byte and ack
04F 09101        150                     INPUT    sC, s0                  ; Load device code for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S0'.
050 14106        151                     SL0     sC                      ; add write flag
E: symbol not defined: `SC'.
051 20057        152                     CALL    I2C_Xmit                ; Send address and ack
052 2008E        153                     CALL    I2C_SAck
                 154
053 09101        155                     INPUT    sC, s1                  ; Load data for TX
E: symbol not defined: `SC'.
E: symbol not defined: `S1'.
054 20057        156                     CALL    I2C_Xmit                ; Send data and ack
055 2008E        157                     CALL    I2C_SAck
                 158
056 220A0        159                     JUMP    I2C_Stop                ; Send stop
                 160
                 161     ; -------------------------------------------------------------------------------
                 162     ; Transmit 8 bits of I2C data
                 163     ; -------------------------------------------------------------------------------
                 164     I2C_Xmit:
057 09108        165                     INPUT    sD, 8                   ; Load I2C bit counter
E: symbol not defined: `SD'.
                 166     I2C_TX:
058 20001        167                     CALL    Delay
E: symbol not defined: `DELAY'.
059 14106        168                     SL0     sC                      ; Move data bit -> carry
E: symbol not defined: `SC'.
05A 3A05E        169                     JUMP    C, I2C_TX1              ; Jump if bit high
                 170     I2C_TX0:
05B 2D102        171                     OUTPUT     sF, bSDA_0              ; SDA = 0
E: symbol not defined: `SF'.
05C 20001        172                     CALL    Delay
E: symbol not defined: `DELAY'.
05D 22060        173                     JUMP    I2C_TX2                 ; Jump over next instructions
                 174     I2C_TX1:
05E 2D102        175                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
E: symbol not defined: `SF'.
05F 20001        176                     CALL    Delay
E: symbol not defined: `DELAY'.
                 177     I2C_TX2:
                 178
060 2D102        179                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
E: symbol not defined: `SF'.
061 20001        180                     CALL    Delay
E: symbol not defined: `DELAY'.
062 20001        181                     CALL    Delay
E: symbol not defined: `DELAY'.
063 20001        182                     CALL    Delay
E: symbol not defined: `DELAY'.
064 2D102        183                     OUTPUT     sF, bSCL_0              ; SCL = 0
E: symbol not defined: `SF'.
                 184
065 18110        185                     SUB     sD, 1                   ; Decrement I2C bit counter
E: symbol not defined: `SD'.
066 36058        186                     JUMP    NZ, I2C_TX              ; Loop until 8 bits are sent
067 22001        187                     JUMP    Delay
E: symbol not defined: `DELAY'.
                 188
                 189     ; -------------------------------------------------------------------------------
                 190     ; Read 8 bits of I2C data
                 191     ; -------------------------------------------------------------------------------
                 192     I2C_Recv:
068 09108        193                     INPUT    sD, 8                   ; Load I2C bit counter
E: symbol not defined: `SD'.
069 20001        194                     CALL    Delay
E: symbol not defined: `DELAY'.
06A 2D102        195                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
E: symbol not defined: `SF'.
                 196
                 197     I2C_RX:
06B 20001        198                     CALL    Delay
E: symbol not defined: `DELAY'.
06C 2D102        199                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
E: symbol not defined: `SF'.
06D 20001        200                     CALL    Delay
E: symbol not defined: `DELAY'.
06E 20001        201                     CALL    Delay
E: symbol not defined: `DELAY'.
06F 09102        202                     IN      sF, bSDA_In
E: symbol not defined: `SF'.
070 20001        203                     CALL    Delay
E: symbol not defined: `DELAY'.
071 1410E        204                     SR0     sF                      ; LSBit -> carry bit
E: symbol not defined: `SF'.
072 14100        205                     SLA     sC                      ; Carry shifted into LSBit
E: symbol not defined: `SC'.
073 2D102        206                     OUTPUT     sF, bSCL_0              ; SCL = 0
E: symbol not defined: `SF'.
074 20001        207                     CALL    Delay
E: symbol not defined: `DELAY'.
075 18110        208                     SUB     sD, 1                   ; Decrement I2C bit counter
E: symbol not defined: `SD'.
076 3606B        209                     JUMP    NZ, I2C_RX              ; Loop until 8 bits are read
077 25000        210                     RETURN
                 211
                 212     ; -------------------------------------------------------------------------------
                 213     ; Ack by master, keep data 0
                 214     ; -------------------------------------------------------------------------------
                 215     I2C_MAck:
078 20001        216                     CALL    Delay
E: symbol not defined: `DELAY'.
079 2D102        217                     OUTPUT     sF, bSDA_0              ; SDA = 0
E: symbol not defined: `SF'.
07A 20001        218                     CALL    Delay
E: symbol not defined: `DELAY'.
07B 2D102        219                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
E: symbol not defined: `SF'.
07C 20001        220                     CALL    Delay
E: symbol not defined: `DELAY'.
07D 20001        221                     CALL    Delay
E: symbol not defined: `DELAY'.
07E 20001        222                     CALL    Delay
E: symbol not defined: `DELAY'.
07F 2D102        223                     OUTPUT     sF, bSCL_0              ; SCL = 0
E: symbol not defined: `SF'.
080 20001        224                     CALL    Delay
E: symbol not defined: `DELAY'.
081 2D102        225                     OUTPUT     sF, bSDA_0              ; SDA = 0
E: symbol not defined: `SF'.
082 25000        226                     RETURN
                 227
                 228     ; -------------------------------------------------------------------------------
                 229     ; NAck by master, release data
                 230     ; -------------------------------------------------------------------------------
                 231     I2C_MNAck:
083 20001        232                     CALL    Delay
E: symbol not defined: `DELAY'.
084 2D102        233                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
E: symbol not defined: `SF'.
085 20001        234                     CALL    Delay
E: symbol not defined: `DELAY'.
086 2D102        235                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
E: symbol not defined: `SF'.
087 20001        236                     CALL    Delay
E: symbol not defined: `DELAY'.
088 20001        237                     CALL    Delay
E: symbol not defined: `DELAY'.
089 20001        238                     CALL    Delay
E: symbol not defined: `DELAY'.
08A 2D102        239                     OUTPUT     sF, bSCL_0              ; SCL = 0
E: symbol not defined: `SF'.
08B 20001        240                     CALL    Delay
E: symbol not defined: `DELAY'.
08C 2D102        241                     OUTPUT     sF, bSDA_0              ; SDA = 0
E: symbol not defined: `SF'.
08D 25000        242                     RETURN
                 243
                 244     ; -------------------------------------------------------------------------------
                 245     ; Ack by slave, release data
                 246     ; -------------------------------------------------------------------------------
                 247     I2C_SAck:
08E 20001        248                     CALL    Delay
E: symbol not defined: `DELAY'.
08F 2D102        249                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
E: symbol not defined: `SF'.
090 20001        250                     CALL    Delay
E: symbol not defined: `DELAY'.
091 2D102        251                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
E: symbol not defined: `SF'.
092 20001        252                     CALL    Delay
E: symbol not defined: `DELAY'.
093 20001        253                     CALL    Delay
E: symbol not defined: `DELAY'.
094 20001        254                     CALL    Delay
E: symbol not defined: `DELAY'.
095 2D102        255                     OUTPUT     sF, bSCL_0              ; SCL = 0
E: symbol not defined: `SF'.
096 20001        256                     CALL    Delay
E: symbol not defined: `DELAY'.
097 25000        257                     RETURN
                 258
                 259     ; -------------------------------------------------------------------------------
                 260     ; Set up start condition for I2C
                 261     ; -------------------------------------------------------------------------------
                 262
                 263     ; SCL and SDA set to inputs, signals go high due to pull-up resistors
                 264
                 265     I2C_RepStart:
098 20001        266                     CALL    Delay
E: symbol not defined: `DELAY'.
099 2D102        267                     OUTPUT     sF, bSCL_Z              ; SCL = Z
E: symbol not defined: `SF'.
                 268     I2C_Start:
09A 20001        269                     CALL    Delay
E: symbol not defined: `DELAY'.
09B 2D102        270                     OUTPUT     sF, bSDA_0              ; SDA = 0
E: symbol not defined: `SF'.
09C 20001        271                     CALL    Delay
E: symbol not defined: `DELAY'.
09D 2D102        272                     OUTPUT     sF, bSCL_0              ; SCL = 0
E: symbol not defined: `SF'.
09E 20001        273                     CALL    Delay
E: symbol not defined: `DELAY'.
09F 25000        274                     RETURN
                 275
                 276     ; -------------------------------------------------------------------------------
                 277     ; Send I2C stop command
                 278     ; -------------------------------------------------------------------------------
                 279     I2C_Stop:
0A0 20001        280                     CALL    Delay
E: symbol not defined: `DELAY'.
0A1 2D102        281                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
E: symbol not defined: `SF'.
0A2 20001        282                     CALL    Delay
E: symbol not defined: `DELAY'.
0A3 2D102        283                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
E: symbol not defined: `SF'.
0A4 20001        284                     CALL    Delay
E: symbol not defined: `DELAY'.
0A5 25000        285                     RETURN
                 286
                 287     ; -----------I2C Subroutines end-------------------------------------------------
