MT_WARNING: 010_directives.asm:5.1-5.21: Warning: reusing already reserved space in register file memory at address: 0x1.
MT_ERROR: 010_directives.asm:26.25-26.27 ==> 010_directives.asm:27.9-27.13: Error: symbol not defined: `SC'.
MT_ERROR: 010_directives.asm:26.25-26.27 ==> 010_directives.asm:27.9-27.13: Error: symbol not defined: `SC'.
MT_ERROR: 010_directives.asm:26.25-26.27 ==> 010_directives.asm:27.9-27.13: Error: symbol not defined: `SC'.
MT_ERROR: 010_directives.asm:26.25-26.27 ==> 010_directives.asm:27.9-27.13: Error: symbol not defined: `SC'.
MT_ERROR: 010_directives.asm:26.25-26.27 ==> 010_directives.asm:27.9-27.13: Error: symbol not defined: `SC'.
MT_ERROR: 010_directives.asm:26.25-26.27 ==> 010_directives.asm:27.9-27.13: Error: symbol not defined: `SC'.
MT_ERROR: 010_directives.asm:26.25-26.27 ==> 010_directives.asm:27.9-27.13: Error: symbol not defined: `SC'.
MT_ERROR: 010_directives.asm:26.25-26.27 ==> 010_directives.asm:27.9-27.13: Error: symbol not defined: `SC'.
