MT_ERROR: 012_REPT_and_WHILE.asm:76.20-76.23: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:77.20-77.26: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:78.20-78.22: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:79.20-79.21: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:80.20-80.30: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:81.20-81.25: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:82.20-82.24: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:83.20-83.30: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:84.20-84.27: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:85.21-85.23: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:86.21-86.24: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:87.21-87.25: Error: unexpected NUMBER, expecting IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:167.25-167.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:167.27-167.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:169.13-169.19: Error: unexpected directive ENDIF.
MT_ERROR: 012_REPT_and_WHILE.asm:174.25-174.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:174.27-174.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:176.13-176.19: Error: unexpected directive ENDIF.
MT_ERROR: 012_REPT_and_WHILE.asm:181.25-181.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:181.27-181.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:183.13-183.19: Error: unexpected directive ENDIF.
MT_ERROR: 012_REPT_and_WHILE.asm:188.25-188.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:188.27-188.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:190.13-190.19: Error: unexpected directive ENDIF.
MT_ERROR: 012_REPT_and_WHILE.asm:195.25-195.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:195.27-195.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:197.13-197.19: Error: unexpected directive ENDIF.
MT_ERROR: 012_REPT_and_WHILE.asm:201.25-201.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:201.27-201.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:203.13-203.19: Error: unexpected directive ENDIF.
MT_ERROR: 012_REPT_and_WHILE.asm:207.25-207.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:207.27-207.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:209.13-209.19: Error: unexpected directive ENDIF.
MT_ERROR: 012_REPT_and_WHILE.asm:213.25-213.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:213.27-213.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:215.13-215.19: Error: unexpected directive ENDIF.
MT_ERROR: 012_REPT_and_WHILE.asm:219.25-219.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:219.27-219.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:221.13-221.19: Error: unexpected directive ENDIF.
MT_ERROR: 012_REPT_and_WHILE.asm:225.25-225.26: Error: unrecognized token: `='.
MT_ERROR: 012_REPT_and_WHILE.asm:225.27-225.29: Error: unexpected IDENTIFIER.
MT_ERROR: 012_REPT_and_WHILE.asm:227.13-227.19: Error: unexpected directive ENDIF.
MT_WARNING: Warning: semantic analysis was not executed due to error(s).
