MT_ERROR: 014_AES_sourcecode.asm:40.31-40.34: Error: invalid token: `$F0'.
MT_ERROR: 014_AES_sourcecode.asm:40.21-40.24: Error: directive EQU requires a single argument.
MT_ERROR: 014_AES_sourcecode.asm:43.32-43.35: Error: invalid token: `$2B'.
MT_ERROR: 014_AES_sourcecode.asm:43.32-43.36: Error: unexpected ",".
MT_ERROR: 014_AES_sourcecode.asm:43.37-43.40: Error: invalid token: `$7E'.
MT_ERROR: 014_AES_sourcecode.asm:43.42-43.45: Error: invalid token: `$15'.
MT_ERROR: 014_AES_sourcecode.asm:43.47-43.50: Error: invalid token: `$16'.
MT_ERROR: 014_AES_sourcecode.asm:43.52-43.55: Error: invalid token: `$28'.
MT_ERROR: 014_AES_sourcecode.asm:43.57-43.60: Error: invalid token: `$AE'.
MT_ERROR: 014_AES_sourcecode.asm:43.62-43.65: Error: invalid token: `$D2'.
MT_ERROR: 014_AES_sourcecode.asm:43.67-43.70: Error: invalid token: `$A6'.
MT_ERROR: 014_AES_sourcecode.asm:43.72-43.75: Error: invalid token: `$AB'.
MT_ERROR: 014_AES_sourcecode.asm:43.77-43.80: Error: invalid token: `$F7'.
MT_ERROR: 014_AES_sourcecode.asm:43.82-43.85: Error: invalid token: `$15'.
MT_ERROR: 014_AES_sourcecode.asm:43.87-43.90: Error: invalid token: `$88'.
MT_ERROR: 014_AES_sourcecode.asm:43.92-43.95: Error: invalid token: `$09'.
MT_ERROR: 014_AES_sourcecode.asm:43.97-43.100: Error: invalid token: `$CF'.
MT_ERROR: 014_AES_sourcecode.asm:43.102-43.105: Error: invalid token: `$4F'.
MT_ERROR: 014_AES_sourcecode.asm:43.107-43.110: Error: invalid token: `$3C'.
MT_ERROR: 014_AES_sourcecode.asm:46.32-46.35: Error: invalid token: `$32'.
MT_ERROR: 014_AES_sourcecode.asm:46.32-46.36: Error: unexpected ",".
MT_ERROR: 014_AES_sourcecode.asm:46.37-46.40: Error: invalid token: `$43'.
MT_ERROR: 014_AES_sourcecode.asm:46.42-46.45: Error: invalid token: `$F6'.
MT_ERROR: 014_AES_sourcecode.asm:46.47-46.50: Error: invalid token: `$A8'.
MT_ERROR: 014_AES_sourcecode.asm:46.52-46.55: Error: invalid token: `$88'.
MT_ERROR: 014_AES_sourcecode.asm:46.57-46.60: Error: invalid token: `$5A'.
MT_ERROR: 014_AES_sourcecode.asm:46.62-46.65: Error: invalid token: `$30'.
MT_ERROR: 014_AES_sourcecode.asm:46.67-46.70: Error: invalid token: `$8D'.
MT_ERROR: 014_AES_sourcecode.asm:46.72-46.75: Error: invalid token: `$31'.
MT_ERROR: 014_AES_sourcecode.asm:46.77-46.80: Error: invalid token: `$31'.
MT_ERROR: 014_AES_sourcecode.asm:46.82-46.85: Error: invalid token: `$98'.
MT_ERROR: 014_AES_sourcecode.asm:46.87-46.90: Error: invalid token: `$A2'.
MT_ERROR: 014_AES_sourcecode.asm:46.92-46.95: Error: invalid token: `$E0'.
MT_ERROR: 014_AES_sourcecode.asm:46.97-46.100: Error: invalid token: `$37'.
MT_ERROR: 014_AES_sourcecode.asm:46.102-46.105: Error: invalid token: `$07'.
MT_ERROR: 014_AES_sourcecode.asm:46.107-46.110: Error: invalid token: `$34'.
MT_ERROR: 014_AES_sourcecode.asm:58.31-58.34: Error: invalid token: `$01'.
MT_ERROR: 014_AES_sourcecode.asm:58.21-58.24: Error: directive EQU requires a single argument.
MT_ERROR: 014_AES_sourcecode.asm:59.31-59.34: Error: invalid token: `$1B'.
MT_ERROR: 014_AES_sourcecode.asm:59.21-59.24: Error: directive EQU requires a single argument.
MT_ERROR: 014_AES_sourcecode.asm:242.35-242.38: Error: invalid token: `$63'.
MT_ERROR: 014_AES_sourcecode.asm:242.64-243.1: Error: unexpected end of line.
MT_ERROR: 014_AES_sourcecode.asm:54.31-54.33: Error: symbol not defined: `S1'.
MT_ERROR: 014_AES_sourcecode.asm:55.31-55.33: Error: symbol not defined: `S2'.
MT_WARNING: Warning: exact device not specified, using KCPSM6 by default.
MT_ERROR: 014_AES_sourcecode.asm:70.32-70.34: Error: symbol not defined: `SF'.
MT_ERROR: 014_AES_sourcecode.asm:70.36-70.37: Error: symbol not defined: `X'.
MT_ERROR: 014_AES_sourcecode.asm:71.32-71.34: Error: symbol not defined: `S3'.
MT_ERROR: 014_AES_sourcecode.asm:78.31-78.33: Error: symbol not defined: `S3'.
MT_ERROR: 014_AES_sourcecode.asm:97.32-97.34: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:98.33-98.35: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:99.33-99.35: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:100.31-100.33: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:100.35-100.37: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:101.34-101.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:104.31-104.33: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:109.38-109.43: Error: symbol not defined: `PLAIN'.
MT_ERROR: 014_AES_sourcecode.asm:114.38-114.43: Error: symbol not defined: `INKEY'.
MT_ERROR: 014_AES_sourcecode.asm:117.32-117.34: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:118.33-118.35: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:119.34-119.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:122.31-122.33: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:130.32-130.34: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:131.33-131.35: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:132.34-132.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:135.31-135.33: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:141.33-141.35: Error: symbol not defined: `S4'.
MT_WARNING: 014_AES_sourcecode.asm:141.37-141.45: Warning: value out of range: 0x1c, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xc.
MT_ERROR: 014_AES_sourcecode.asm:142.33-142.35: Error: symbol not defined: `S5'.
MT_WARNING: 014_AES_sourcecode.asm:142.37-142.45: Warning: value out of range: 0x1d, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xd.
MT_ERROR: 014_AES_sourcecode.asm:143.33-143.35: Error: symbol not defined: `S6'.
MT_WARNING: 014_AES_sourcecode.asm:143.37-143.45: Warning: value out of range: 0x1e, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xe.
MT_ERROR: 014_AES_sourcecode.asm:144.33-144.35: Error: symbol not defined: `S7'.
MT_WARNING: 014_AES_sourcecode.asm:144.37-144.45: Warning: value out of range: 0x1f, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xf.
MT_ERROR: 014_AES_sourcecode.asm:146.32-146.34: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:146.36-146.38: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:147.32-147.34: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:147.36-147.38: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:148.32-148.34: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:148.36-148.38: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:149.32-149.34: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:149.36-149.38: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:150.32-150.34: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:150.36-150.38: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:152.32-152.34: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:152.36-152.38: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:154.32-154.34: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:154.36-154.38: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:156.31-156.33: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:156.35-156.37: Error: symbol not defined: `SF'.
MT_ERROR: 014_AES_sourcecode.asm:157.31-157.33: Error: symbol not defined: `SF'.
MT_ERROR: 014_AES_sourcecode.asm:159.31-159.33: Error: symbol not defined: `SF'.
MT_ERROR: 014_AES_sourcecode.asm:159.35-159.36: Error: symbol not defined: `G'.
MT_ERROR: 014_AES_sourcecode.asm:161.32-161.34: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:161.36-161.38: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:163.32-163.34: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:163.36-163.38: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:165.32-165.34: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:165.36-165.38: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:167.32-167.34: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:167.36-167.38: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:169.32-169.34: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:169.36-169.38: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:171.32-171.34: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:171.36-171.38: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:175.32-175.34: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:176.33-176.35: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:177.31-177.33: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:177.35-177.37: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:178.34-178.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:181.33-181.35: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:182.31-182.33: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:182.35-182.37: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:183.34-183.36: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:186.33-186.35: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:187.31-187.33: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:187.35-187.37: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:188.34-188.36: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:191.33-191.35: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:192.31-192.33: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:192.35-192.37: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:193.34-193.36: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:196.31-196.33: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:202.32-202.34: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:203.33-203.35: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:205.34-205.36: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:207.31-207.33: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:215.32-215.34: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:216.33-216.35: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:218.34-218.36: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:220.31-220.33: Error: symbol not defined: `S0'.
MT_ERROR: 014_AES_sourcecode.asm:226.34-226.36: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:226.38-226.46: Error: symbol not defined: `SBOX_ROM'.
MT_ERROR: 014_AES_sourcecode.asm:227.34-227.36: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:227.38-227.46: Error: symbol not defined: `SBOX_ROM'.
MT_ERROR: 014_AES_sourcecode.asm:235.31-235.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:235.35-235.37: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:236.31-236.33: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:237.31-237.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:237.35-237.37: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:238.31-238.33: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:239.31-239.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:239.35-239.37: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:240.31-240.33: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:241.31-241.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:241.35-241.37: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:248.32-248.34: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:249.31-249.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:249.35-249.37: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:251.31-251.33: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:253.32-253.34: Error: symbol not defined: `SC'.
MT_ERROR: 014_AES_sourcecode.asm:253.36-253.38: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:254.32-254.34: Error: symbol not defined: `SD'.
MT_ERROR: 014_AES_sourcecode.asm:254.36-254.38: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:256.31-256.33: Error: symbol not defined: `SE'.
MT_ERROR: 014_AES_sourcecode.asm:261.32-261.34: Error: symbol not defined: `SE'.
MT_ERROR: 014_AES_sourcecode.asm:263.31-263.33: Error: symbol not defined: `SD'.
MT_ERROR: 014_AES_sourcecode.asm:268.31-268.33: Error: symbol not defined: `SE'.
MT_ERROR: 014_AES_sourcecode.asm:268.35-268.37: Error: symbol not defined: `SC'.
MT_ERROR: 014_AES_sourcecode.asm:269.31-269.33: Error: symbol not defined: `SC'.
MT_ERROR: 014_AES_sourcecode.asm:271.31-271.33: Error: symbol not defined: `SC'.
MT_ERROR: 014_AES_sourcecode.asm:271.35-271.36: Error: symbol not defined: `G'.
MT_ERROR: 014_AES_sourcecode.asm:276.33-276.35: Error: symbol not defined: `S7'.
MT_WARNING: 014_AES_sourcecode.asm:276.37-276.46: Warning: value out of range: 0x11, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x1.
MT_ERROR: 014_AES_sourcecode.asm:277.33-277.35: Error: symbol not defined: `S4'.
MT_WARNING: 014_AES_sourcecode.asm:277.37-277.50: Warning: value out of range: 0x15, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x5.
MT_ERROR: 014_AES_sourcecode.asm:278.33-278.35: Error: symbol not defined: `S5'.
MT_WARNING: 014_AES_sourcecode.asm:278.37-278.54: Warning: value out of range: 0x19, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x9.
MT_ERROR: 014_AES_sourcecode.asm:279.33-279.35: Error: symbol not defined: `S6'.
MT_WARNING: 014_AES_sourcecode.asm:279.37-279.58: Warning: value out of range: 0x1d, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xd.
MT_ERROR: 014_AES_sourcecode.asm:280.34-280.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:281.34-281.36: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:282.34-282.36: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:283.34-283.36: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:285.33-285.35: Error: symbol not defined: `S6'.
MT_WARNING: 014_AES_sourcecode.asm:285.37-285.46: Warning: value out of range: 0x12, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x2.
MT_ERROR: 014_AES_sourcecode.asm:286.33-286.35: Error: symbol not defined: `S7'.
MT_WARNING: 014_AES_sourcecode.asm:286.37-286.50: Warning: value out of range: 0x16, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x6.
MT_ERROR: 014_AES_sourcecode.asm:287.33-287.35: Error: symbol not defined: `S4'.
MT_WARNING: 014_AES_sourcecode.asm:287.37-287.54: Warning: value out of range: 0x1a, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xa.
MT_ERROR: 014_AES_sourcecode.asm:288.33-288.35: Error: symbol not defined: `S5'.
MT_WARNING: 014_AES_sourcecode.asm:288.37-288.58: Warning: value out of range: 0x1e, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xe.
MT_ERROR: 014_AES_sourcecode.asm:289.34-289.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:290.34-290.36: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:291.34-291.36: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:292.34-292.36: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:294.33-294.35: Error: symbol not defined: `S5'.
MT_WARNING: 014_AES_sourcecode.asm:294.37-294.46: Warning: value out of range: 0x13, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x3.
MT_ERROR: 014_AES_sourcecode.asm:295.33-295.35: Error: symbol not defined: `S6'.
MT_WARNING: 014_AES_sourcecode.asm:295.37-295.50: Warning: value out of range: 0x17, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x7.
MT_ERROR: 014_AES_sourcecode.asm:296.33-296.35: Error: symbol not defined: `S7'.
MT_WARNING: 014_AES_sourcecode.asm:296.37-296.54: Warning: value out of range: 0x1b, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xb.
MT_ERROR: 014_AES_sourcecode.asm:297.33-297.35: Error: symbol not defined: `S4'.
MT_WARNING: 014_AES_sourcecode.asm:297.37-297.58: Warning: value out of range: 0x1f, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xf.
MT_ERROR: 014_AES_sourcecode.asm:298.34-298.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:299.34-299.36: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:300.34-300.36: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:301.34-301.36: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:308.33-308.35: Error: symbol not defined: `S4'.
MT_WARNING: 014_AES_sourcecode.asm:308.37-308.46: Warning: value out of range: 0x10, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x0.
MT_ERROR: 014_AES_sourcecode.asm:309.33-309.35: Error: symbol not defined: `S5'.
MT_WARNING: 014_AES_sourcecode.asm:309.37-309.46: Warning: value out of range: 0x11, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x1.
MT_ERROR: 014_AES_sourcecode.asm:310.33-310.35: Error: symbol not defined: `S6'.
MT_WARNING: 014_AES_sourcecode.asm:310.37-310.46: Warning: value out of range: 0x12, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x2.
MT_ERROR: 014_AES_sourcecode.asm:311.33-311.35: Error: symbol not defined: `S7'.
MT_WARNING: 014_AES_sourcecode.asm:311.37-311.46: Warning: value out of range: 0x13, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x3.
MT_ERROR: 014_AES_sourcecode.asm:313.34-313.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:314.34-314.36: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:315.34-315.36: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:316.34-316.36: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:318.33-318.35: Error: symbol not defined: `S4'.
MT_WARNING: 014_AES_sourcecode.asm:318.37-318.50: Warning: value out of range: 0x14, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x4.
MT_ERROR: 014_AES_sourcecode.asm:319.33-319.35: Error: symbol not defined: `S5'.
MT_WARNING: 014_AES_sourcecode.asm:319.37-319.50: Warning: value out of range: 0x15, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x5.
MT_ERROR: 014_AES_sourcecode.asm:320.33-320.35: Error: symbol not defined: `S6'.
MT_WARNING: 014_AES_sourcecode.asm:320.37-320.50: Warning: value out of range: 0x16, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x6.
MT_ERROR: 014_AES_sourcecode.asm:321.33-321.35: Error: symbol not defined: `S7'.
MT_WARNING: 014_AES_sourcecode.asm:321.37-321.50: Warning: value out of range: 0x17, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x7.
MT_ERROR: 014_AES_sourcecode.asm:323.34-323.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:324.34-324.36: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:325.34-325.36: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:326.34-326.36: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:328.33-328.35: Error: symbol not defined: `S4'.
MT_WARNING: 014_AES_sourcecode.asm:328.37-328.54: Warning: value out of range: 0x18, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x8.
MT_ERROR: 014_AES_sourcecode.asm:329.33-329.35: Error: symbol not defined: `S5'.
MT_WARNING: 014_AES_sourcecode.asm:329.37-329.54: Warning: value out of range: 0x19, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x9.
MT_ERROR: 014_AES_sourcecode.asm:330.33-330.35: Error: symbol not defined: `S6'.
MT_WARNING: 014_AES_sourcecode.asm:330.37-330.54: Warning: value out of range: 0x1a, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xa.
MT_ERROR: 014_AES_sourcecode.asm:331.33-331.35: Error: symbol not defined: `S7'.
MT_WARNING: 014_AES_sourcecode.asm:331.37-331.54: Warning: value out of range: 0x1b, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xb.
MT_ERROR: 014_AES_sourcecode.asm:333.34-333.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:334.34-334.36: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:335.34-335.36: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:336.34-336.36: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:338.33-338.35: Error: symbol not defined: `S4'.
MT_WARNING: 014_AES_sourcecode.asm:338.37-338.58: Warning: value out of range: 0x1c, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xc.
MT_ERROR: 014_AES_sourcecode.asm:339.33-339.35: Error: symbol not defined: `S5'.
MT_WARNING: 014_AES_sourcecode.asm:339.37-339.58: Warning: value out of range: 0x1d, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xd.
MT_ERROR: 014_AES_sourcecode.asm:340.33-340.35: Error: symbol not defined: `S6'.
MT_WARNING: 014_AES_sourcecode.asm:340.37-340.58: Warning: value out of range: 0x1e, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xe.
MT_ERROR: 014_AES_sourcecode.asm:341.33-341.35: Error: symbol not defined: `S7'.
MT_WARNING: 014_AES_sourcecode.asm:341.37-341.58: Warning: value out of range: 0x1f, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xf.
MT_ERROR: 014_AES_sourcecode.asm:343.34-343.36: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:344.34-344.36: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:345.34-345.36: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:346.34-346.36: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:351.32-351.34: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:351.36-351.38: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:352.31-352.33: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:352.35-352.37: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:353.32-353.34: Error: symbol not defined: `SA'.
MT_ERROR: 014_AES_sourcecode.asm:353.36-353.38: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:354.31-354.33: Error: symbol not defined: `SA'.
MT_ERROR: 014_AES_sourcecode.asm:354.35-354.37: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:355.32-355.34: Error: symbol not defined: `SB'.
MT_ERROR: 014_AES_sourcecode.asm:355.36-355.38: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:356.31-356.33: Error: symbol not defined: `SB'.
MT_ERROR: 014_AES_sourcecode.asm:356.35-356.37: Error: symbol not defined: `SA'.
MT_ERROR: 014_AES_sourcecode.asm:358.32-358.34: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:358.36-358.38: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:359.31-359.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:359.35-359.37: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:360.31-360.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:362.31-362.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:362.35-362.36: Error: symbol not defined: `G'.
MT_ERROR: 014_AES_sourcecode.asm:363.31-363.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:363.35-363.37: Error: symbol not defined: `SB'.
MT_ERROR: 014_AES_sourcecode.asm:364.31-364.33: Error: symbol not defined: `S4'.
MT_ERROR: 014_AES_sourcecode.asm:364.35-364.37: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:366.32-366.34: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:366.36-366.38: Error: symbol not defined: `SA'.
MT_ERROR: 014_AES_sourcecode.asm:367.31-367.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:369.31-369.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:369.35-369.36: Error: symbol not defined: `G'.
MT_ERROR: 014_AES_sourcecode.asm:370.31-370.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:370.35-370.37: Error: symbol not defined: `SB'.
MT_ERROR: 014_AES_sourcecode.asm:371.31-371.33: Error: symbol not defined: `S5'.
MT_ERROR: 014_AES_sourcecode.asm:371.35-371.37: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:373.32-373.34: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:373.36-373.38: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:374.31-374.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:374.35-374.37: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:375.31-375.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:377.31-377.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:377.35-377.36: Error: symbol not defined: `G'.
MT_ERROR: 014_AES_sourcecode.asm:378.31-378.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:378.35-378.37: Error: symbol not defined: `SB'.
MT_ERROR: 014_AES_sourcecode.asm:379.31-379.33: Error: symbol not defined: `S6'.
MT_ERROR: 014_AES_sourcecode.asm:379.35-379.37: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:381.32-381.34: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:381.36-381.38: Error: symbol not defined: `S9'.
MT_ERROR: 014_AES_sourcecode.asm:382.31-382.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:384.31-384.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:384.35-384.36: Error: symbol not defined: `G'.
MT_ERROR: 014_AES_sourcecode.asm:385.31-385.33: Error: symbol not defined: `S8'.
MT_ERROR: 014_AES_sourcecode.asm:385.35-385.37: Error: symbol not defined: `SB'.
MT_ERROR: 014_AES_sourcecode.asm:386.31-386.33: Error: symbol not defined: `S7'.
MT_ERROR: 014_AES_sourcecode.asm:386.35-386.37: Error: symbol not defined: `S8'.
