MT_ERROR: 017_Source_code_ukol_2.asm:21.31-21.34: Error: invalid token: `$01'.
MT_ERROR: 017_Source_code_ukol_2.asm:22.31-22.34: Error: invalid token: `$02'.
MT_ERROR: 017_Source_code_ukol_2.asm:28.31-28.34: Error: invalid token: `$04'.
MT_ERROR: 017_Source_code_ukol_2.asm:29.31-29.34: Error: invalid token: `$08'.
MT_ERROR: 017_Source_code_ukol_2.asm:30.31-30.34: Error: invalid token: `$10'.
MT_ERROR: 017_Source_code_ukol_2.asm:31.31-31.34: Error: invalid token: `$20'.
MT_ERROR: 017_Source_code_ukol_2.asm:32.31-32.34: Error: invalid token: `$40'.
MT_ERROR: 017_Source_code_ukol_2.asm:36.31-36.46: Error: unexpected STRING.
MT_ERROR: 017_Source_code_ukol_2.asm:45.34-45.37: Error: invalid token: `$00'.
MT_ERROR: 017_Source_code_ukol_2.asm:45.69-46.1: Error: unexpected end of line.
MT_ERROR: 017_Source_code_ukol_2.asm:99.38-99.41: Error: invalid token: `$37'.
MT_ERROR: 017_Source_code_ukol_2.asm:99.92-100.1: Error: unexpected end of line.
MT_ERROR: 017_Source_code_ukol_2.asm:101.38-101.41: Error: invalid token: `$30'.
MT_ERROR: 017_Source_code_ukol_2.asm:101.92-102.1: Error: unexpected end of line.
MT_ERROR: 017_Source_code_ukol_2.asm:105.38-105.41: Error: invalid token: `$0F'.
MT_ERROR: 017_Source_code_ukol_2.asm:105.76-106.1: Error: unexpected end of line.
MT_ERROR: 017_Source_code_ukol_2.asm:108.38-108.41: Error: invalid token: `$37'.
MT_ERROR: 017_Source_code_ukol_2.asm:108.92-109.1: Error: unexpected end of line.
MT_ERROR: 017_Source_code_ukol_2.asm:110.38-110.41: Error: invalid token: `$30'.
MT_ERROR: 017_Source_code_ukol_2.asm:110.92-111.1: Error: unexpected end of line.
MT_ERROR: 017_Source_code_ukol_2.asm:119.38-119.41: Error: invalid token: `$0D'.
MT_ERROR: 017_Source_code_ukol_2.asm:119.65-120.1: Error: unexpected end of line.
MT_ERROR: 017_Source_code_ukol_2.asm:121.38-121.41: Error: invalid token: `$0A'.
MT_ERROR: 017_Source_code_ukol_2.asm:121.70-122.1: Error: unexpected end of line.
MT_ERROR: 017_Source_code_ukol_2.asm:97.21-97.40: Error: macro not defined: "COMP".
MT_ERROR: 017_Source_code_ukol_2.asm:106.21-106.40: Error: macro not defined: "COMP".
MT_WARNING: Warning: exact device not specified, using KCPSM6 by default.
MT_ERROR: 017_Source_code_ukol_2.asm:46.28-46.33: Error: symbol not defined: `TEMP1'.
MT_ERROR: 017_Source_code_ukol_2.asm:46.34-46.37: Error: symbol not defined: `LED'.
MT_ERROR: 017_Source_code_ukol_2.asm:54.31-54.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:54.37-54.43: Error: symbol not defined: `BCD_01'.
MT_ERROR: 017_Source_code_ukol_2.asm:55.31-55.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:56.31-56.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:56.37-56.43: Error: symbol not defined: `BCD_23'.
MT_ERROR: 017_Source_code_ukol_2.asm:70.31-70.36: Error: symbol not defined: `TEMP1'.
MT_ERROR: 017_Source_code_ukol_2.asm:70.38-70.47: Error: symbol not defined: `UART_STAT'.
MT_ERROR: 017_Source_code_ukol_2.asm:71.31-71.36: Error: symbol not defined: `TEMP1'.
MT_ERROR: 017_Source_code_ukol_2.asm:73.31-73.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:73.38-73.47: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 017_Source_code_ukol_2.asm:80.31-80.36: Error: symbol not defined: `TEMP1'.
MT_ERROR: 017_Source_code_ukol_2.asm:80.38-80.47: Error: symbol not defined: `UART_STAT'.
MT_ERROR: 017_Source_code_ukol_2.asm:81.31-81.36: Error: symbol not defined: `TEMP1'.
MT_ERROR: 017_Source_code_ukol_2.asm:83.31-83.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:83.38-83.47: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 017_Source_code_ukol_2.asm:92.31-92.36: Error: symbol not defined: `TEMP2'.
MT_ERROR: 017_Source_code_ukol_2.asm:92.38-92.43: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:93.31-93.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:94.31-94.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:95.31-95.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:96.31-96.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:98.34-98.43: Error: symbol not defined: `SENDBNUM1'.
MT_ERROR: 017_Source_code_ukol_2.asm:104.31-104.36: Error: symbol not defined: `CHREG'.
MT_ERROR: 017_Source_code_ukol_2.asm:104.38-104.43: Error: symbol not defined: `TEMP2'.
MT_ERROR: 017_Source_code_ukol_2.asm:107.34-107.43: Error: symbol not defined: `SENDBNUM2'.
MT_ERROR: 017_Source_code_ukol_2.asm:139.31-139.36: Error: symbol not defined: `TEMP1'.
MT_WARNING: 017_Source_code_ukol_2.asm:139.38-139.41: Warning: value out of range: 0xfa, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xa.
MT_ERROR: 017_Source_code_ukol_2.asm:140.31-140.36: Error: symbol not defined: `TEMP2'.
MT_WARNING: 017_Source_code_ukol_2.asm:140.38-140.41: Warning: value out of range: 0xf9, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x9.
MT_ERROR: 017_Source_code_ukol_2.asm:141.31-141.36: Error: symbol not defined: `TEMP3'.
MT_WARNING: 017_Source_code_ukol_2.asm:141.38-141.41: Warning: value out of range: 0xc8, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x8.
MT_ERROR: 017_Source_code_ukol_2.asm:142.31-142.36: Error: symbol not defined: `TEMP1'.
MT_ERROR: 017_Source_code_ukol_2.asm:144.31-144.36: Error: symbol not defined: `TEMP2'.
MT_ERROR: 017_Source_code_ukol_2.asm:146.31-146.36: Error: symbol not defined: `TEMP3'.
MT_ERROR: 017_Source_code_ukol_2.asm:150.31-150.36: Error: symbol not defined: `TEMP1'.
MT_WARNING: 017_Source_code_ukol_2.asm:150.38-150.41: Warning: value out of range: 0xfa, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xa.
MT_ERROR: 017_Source_code_ukol_2.asm:151.31-151.36: Error: symbol not defined: `TEMP2'.
MT_WARNING: 017_Source_code_ukol_2.asm:151.38-151.41: Warning: value out of range: 0xf9, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x9.
MT_ERROR: 017_Source_code_ukol_2.asm:152.31-152.36: Error: symbol not defined: `TEMP3'.
MT_WARNING: 017_Source_code_ukol_2.asm:152.38-152.40: Warning: value out of range: 0x14, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x4.
MT_ERROR: 017_Source_code_ukol_2.asm:153.31-153.36: Error: symbol not defined: `TEMP1'.
MT_ERROR: 017_Source_code_ukol_2.asm:155.31-155.36: Error: symbol not defined: `TEMP2'.
MT_ERROR: 017_Source_code_ukol_2.asm:157.31-157.36: Error: symbol not defined: `TEMP3'.
