MT_ERROR: 021_demo_4.asm:170.21-170.28: Error: macro not defined: "RETURNI".
MT_WARNING: 021_demo_4.asm:160.31-160.34 ==> 021_demo_4.asm:58.41-58.45 ==> 021_demo_4.asm:160.21-160.34: Warning: value out of range: 0x49, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x9.
MT_WARNING: 021_demo_4.asm:161.31-161.34 ==> 021_demo_4.asm:58.41-58.45 ==> 021_demo_4.asm:161.21-161.34: Warning: value out of range: 0x4e, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0xe.
MT_WARNING: 021_demo_4.asm:162.31-162.34 ==> 021_demo_4.asm:58.41-58.45 ==> 021_demo_4.asm:162.21-162.34: Warning: value out of range: 0x54, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x4.
MT_WARNING: 021_demo_4.asm:163.31-163.34 ==> 021_demo_4.asm:58.41-58.45 ==> 021_demo_4.asm:163.21-163.34: Warning: value out of range: 0x45, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x5.
MT_WARNING: 021_demo_4.asm:164.31-164.34 ==> 021_demo_4.asm:58.41-58.45 ==> 021_demo_4.asm:164.21-164.34: Warning: value out of range: 0x52, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x2.
MT_WARNING: 021_demo_4.asm:165.31-165.34 ==> 021_demo_4.asm:58.41-58.45 ==> 021_demo_4.asm:165.21-165.34: Warning: value out of range: 0x52, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x2.
MT_WARNING: 021_demo_4.asm:166.31-166.34 ==> 021_demo_4.asm:58.41-58.45 ==> 021_demo_4.asm:166.21-166.34: Warning: value out of range: 0x55, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x5.
MT_WARNING: 021_demo_4.asm:167.31-167.34 ==> 021_demo_4.asm:58.41-58.45 ==> 021_demo_4.asm:167.21-167.34: Warning: value out of range: 0x50, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x0.
MT_WARNING: 021_demo_4.asm:168.31-168.34 ==> 021_demo_4.asm:58.41-58.45 ==> 021_demo_4.asm:168.21-168.34: Warning: value out of range: 0x54, allowed range is [0x0,0xf] (trimmed to 4 bits) which makes it 0x4.
MT_ERROR: 021_demo_4.asm:67.33-67.40 ==> 021_demo_4.asm:177.21-177.28: Error: symbol not defined: `RX_DATA'.
