MT_ERROR: 021_demo_4.asm:170.21-170.28: Error: macro not defined: "RETURNI".
MT_WARNING: 021_demo_4.asm:160.31-160.34: Warning: value out of range: 73, allowed range is [0,15] (trimmed to 4 bits) which makes it 9.
MT_WARNING: 021_demo_4.asm:58.41-58.45: Warning: ==> value out of range: 73, allowed range is [0,15] (trimmed to 4 bits) which makes it 9.
MT_WARNING: 021_demo_4.asm:161.31-161.34: Warning: value out of range: 78, allowed range is [0,15] (trimmed to 4 bits) which makes it 14.
MT_WARNING: 021_demo_4.asm:58.41-58.45: Warning: ==> value out of range: 78, allowed range is [0,15] (trimmed to 4 bits) which makes it 14.
MT_WARNING: 021_demo_4.asm:162.31-162.34: Warning: value out of range: 84, allowed range is [0,15] (trimmed to 4 bits) which makes it 4.
MT_WARNING: 021_demo_4.asm:58.41-58.45: Warning: ==> value out of range: 84, allowed range is [0,15] (trimmed to 4 bits) which makes it 4.
MT_WARNING: 021_demo_4.asm:163.31-163.34: Warning: value out of range: 69, allowed range is [0,15] (trimmed to 4 bits) which makes it 5.
MT_WARNING: 021_demo_4.asm:58.41-58.45: Warning: ==> value out of range: 69, allowed range is [0,15] (trimmed to 4 bits) which makes it 5.
MT_WARNING: 021_demo_4.asm:164.31-164.34: Warning: value out of range: 82, allowed range is [0,15] (trimmed to 4 bits) which makes it 2.
MT_WARNING: 021_demo_4.asm:58.41-58.45: Warning: ==> value out of range: 82, allowed range is [0,15] (trimmed to 4 bits) which makes it 2.
MT_WARNING: 021_demo_4.asm:165.31-165.34: Warning: value out of range: 82, allowed range is [0,15] (trimmed to 4 bits) which makes it 2.
MT_WARNING: 021_demo_4.asm:166.31-166.34: Warning: value out of range: 85, allowed range is [0,15] (trimmed to 4 bits) which makes it 5.
MT_WARNING: 021_demo_4.asm:58.41-58.45: Warning: ==> value out of range: 85, allowed range is [0,15] (trimmed to 4 bits) which makes it 5.
MT_WARNING: 021_demo_4.asm:167.31-167.34: Warning: value out of range: 80, allowed range is [0,15] (trimmed to 4 bits) which makes it 0.
MT_WARNING: 021_demo_4.asm:58.41-58.45: Warning: ==> value out of range: 80, allowed range is [0,15] (trimmed to 4 bits) which makes it 0.
MT_WARNING: 021_demo_4.asm:168.31-168.34: Warning: value out of range: 84, allowed range is [0,15] (trimmed to 4 bits) which makes it 4.
MT_ERROR: 021_demo_4.asm:67.33-67.40: Error: symbol not defined: `RX_DATA'.
MT_ERROR: 021_demo_4.asm:177.21-177.28: Error: ==> symbol not defined: `RX_DATA'.
