MT_ERROR: 031_example_4.asm:108.42-108.44: Error: identifier cannot start with a digit: `1A'.
MT_ERROR: 031_example_4.asm:108.42-109.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:122.45-122.47: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 031_example_4.asm:122.45-123.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:123.45-123.47: Error: identifier cannot start with a digit: `3B'.
MT_ERROR: 031_example_4.asm:123.45-124.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:124.45-124.47: Error: identifier cannot start with a digit: `3C'.
MT_ERROR: 031_example_4.asm:124.45-125.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:126.45-126.47: Error: identifier cannot start with a digit: `3E'.
MT_ERROR: 031_example_4.asm:126.45-127.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:127.45-127.47: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 031_example_4.asm:127.45-128.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:163.45-163.47: Error: identifier cannot start with a digit: `6A'.
MT_ERROR: 031_example_4.asm:163.45-164.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:164.45-164.47: Error: identifier cannot start with a digit: `6B'.
MT_ERROR: 031_example_4.asm:164.45-165.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:165.45-165.47: Error: identifier cannot start with a digit: `6C'.
MT_ERROR: 031_example_4.asm:165.45-166.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:167.45-167.47: Error: identifier cannot start with a digit: `6E'.
MT_ERROR: 031_example_4.asm:167.45-168.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:168.45-168.47: Error: identifier cannot start with a digit: `6F'.
MT_ERROR: 031_example_4.asm:168.45-169.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:179.45-179.47: Error: identifier cannot start with a digit: `7A'.
MT_ERROR: 031_example_4.asm:179.45-180.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:189.45-189.47: Error: identifier cannot start with a digit: `4A'.
MT_ERROR: 031_example_4.asm:189.45-190.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:190.45-190.47: Error: identifier cannot start with a digit: `4B'.
MT_ERROR: 031_example_4.asm:190.45-191.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:191.45-191.47: Error: identifier cannot start with a digit: `4C'.
MT_ERROR: 031_example_4.asm:191.45-192.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:193.45-193.47: Error: identifier cannot start with a digit: `4E'.
MT_ERROR: 031_example_4.asm:193.45-194.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:194.45-194.47: Error: identifier cannot start with a digit: `4F'.
MT_ERROR: 031_example_4.asm:194.45-195.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:205.45-205.47: Error: identifier cannot start with a digit: `5A'.
MT_ERROR: 031_example_4.asm:205.45-206.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:216.49-216.51: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 031_example_4.asm:216.49-217.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:217.48-217.50: Error: identifier cannot start with a digit: `2E'.
MT_ERROR: 031_example_4.asm:217.48-218.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:218.54-218.56: Error: identifier cannot start with a digit: `3B'.
MT_ERROR: 031_example_4.asm:218.54-219.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:220.50-220.52: Error: identifier cannot start with a digit: `2F'.
MT_ERROR: 031_example_4.asm:220.63-221.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:221.48-221.50: Error: identifier cannot start with a digit: `2B'.
MT_ERROR: 031_example_4.asm:221.48-222.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:222.49-222.51: Error: identifier cannot start with a digit: `2C'.
MT_ERROR: 031_example_4.asm:222.49-223.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:223.53-223.55: Error: identifier cannot start with a digit: `3C'.
MT_ERROR: 031_example_4.asm:223.53-224.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:224.56-224.58: Error: identifier cannot start with a digit: `3E'.
MT_ERROR: 031_example_4.asm:224.56-225.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:228.52-228.54: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 031_example_4.asm:228.63-229.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:260.32-260.34: Error: identifier cannot start with a digit: `2B'.
MT_ERROR: 031_example_4.asm:260.78-261.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:282.32-282.34: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 031_example_4.asm:282.32-283.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:304.31-304.33: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 031_example_4.asm:304.76-305.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:460.32-460.34: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 031_example_4.asm:460.109-461.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:950.30-950.32: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 031_example_4.asm:950.95-951.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:985.32-985.34: Error: identifier cannot start with a digit: `0E'.
MT_ERROR: 031_example_4.asm:985.94-986.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:1040.32-1040.34: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 031_example_4.asm:1040.75-1041.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:1067.31-1067.33: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 031_example_4.asm:1067.101-1068.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:1071.31-1071.33: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 031_example_4.asm:1071.101-1072.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:1147.32-1147.34: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 031_example_4.asm:1147.95-1148.1: Error: unexpected end of line.
MT_ERROR: 031_example_4.asm:1188.31-1188.34: Error: identifier cannot start with a digit: `3FF'.
MT_ERROR: 031_example_4.asm:1188.23-1188.30: Error: directive ADDRESS requires a single argument.
MT_WARNING: Warning: semantic analysis was not executed due to syntax error(s).
