MT_ERROR: 033_example_6.asm:122.40-122.42: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 033_example_6.asm:122.40-123.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:159.43-159.45: Error: identifier cannot start with a digit: `6A'.
MT_ERROR: 033_example_6.asm:159.43-160.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:160.43-160.45: Error: identifier cannot start with a digit: `6B'.
MT_ERROR: 033_example_6.asm:160.43-161.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:161.43-161.45: Error: identifier cannot start with a digit: `6C'.
MT_ERROR: 033_example_6.asm:161.43-162.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:163.43-163.45: Error: identifier cannot start with a digit: `6E'.
MT_ERROR: 033_example_6.asm:163.43-164.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:164.43-164.45: Error: identifier cannot start with a digit: `6F'.
MT_ERROR: 033_example_6.asm:164.43-165.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:175.43-175.45: Error: identifier cannot start with a digit: `7A'.
MT_ERROR: 033_example_6.asm:175.43-176.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:185.43-185.45: Error: identifier cannot start with a digit: `4A'.
MT_ERROR: 033_example_6.asm:185.43-186.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:186.43-186.45: Error: identifier cannot start with a digit: `4B'.
MT_ERROR: 033_example_6.asm:186.43-187.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:187.43-187.45: Error: identifier cannot start with a digit: `4C'.
MT_ERROR: 033_example_6.asm:187.43-188.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:189.43-189.45: Error: identifier cannot start with a digit: `4E'.
MT_ERROR: 033_example_6.asm:189.43-190.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:190.43-190.45: Error: identifier cannot start with a digit: `4F'.
MT_ERROR: 033_example_6.asm:190.43-191.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:201.43-201.45: Error: identifier cannot start with a digit: `5A'.
MT_ERROR: 033_example_6.asm:201.43-202.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:212.47-212.49: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 033_example_6.asm:212.47-213.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:213.46-213.48: Error: identifier cannot start with a digit: `2E'.
MT_ERROR: 033_example_6.asm:213.46-214.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:214.52-214.54: Error: identifier cannot start with a digit: `3B'.
MT_ERROR: 033_example_6.asm:214.52-215.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:216.48-216.50: Error: identifier cannot start with a digit: `2F'.
MT_ERROR: 033_example_6.asm:216.61-217.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:217.46-217.48: Error: identifier cannot start with a digit: `2B'.
MT_ERROR: 033_example_6.asm:217.46-218.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:218.47-218.49: Error: identifier cannot start with a digit: `2C'.
MT_ERROR: 033_example_6.asm:218.47-219.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:219.51-219.53: Error: identifier cannot start with a digit: `3C'.
MT_ERROR: 033_example_6.asm:219.51-220.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:220.54-220.56: Error: identifier cannot start with a digit: `3E'.
MT_ERROR: 033_example_6.asm:220.54-221.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:224.50-224.52: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 033_example_6.asm:224.61-225.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:298.30-298.32: Error: identifier cannot start with a digit: `2C'.
MT_ERROR: 033_example_6.asm:298.76-299.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:427.30-427.32: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 033_example_6.asm:427.97-428.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:435.30-435.32: Error: identifier cannot start with a digit: `9C'.
MT_ERROR: 033_example_6.asm:435.98-436.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:467.33-467.35: Error: identifier cannot start with a digit: `1F'.
MT_ERROR: 033_example_6.asm:467.83-468.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:640.30-640.32: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 033_example_6.asm:640.105-641.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:999.29-999.31: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 033_example_6.asm:999.78-1000.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:1008.29-1008.31: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 033_example_6.asm:1008.90-1009.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:1011.29-1011.31: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 033_example_6.asm:1011.93-1012.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:1177.28-1177.30: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 033_example_6.asm:1177.93-1178.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:1212.30-1212.32: Error: identifier cannot start with a digit: `0E'.
MT_ERROR: 033_example_6.asm:1212.92-1213.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:1267.30-1267.32: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 033_example_6.asm:1267.73-1268.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:1294.29-1294.31: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 033_example_6.asm:1294.99-1295.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:1298.29-1298.31: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 033_example_6.asm:1298.99-1299.1: Error: unexpected end of line.
MT_ERROR: 033_example_6.asm:1327.29-1327.32: Error: identifier cannot start with a digit: `3FF'.
MT_ERROR: 033_example_6.asm:1327.21-1327.28: Error: directive ADDRESS requires a single argument.
MT_WARNING: Warning: semantic analysis was not executed due to error(s).
