MT_ERROR: 034_example_7.asm:208.31-208.33: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 034_example_7.asm:208.90-209.1: Error: unexpected end of line.
MT_ERROR: 034_example_7.asm:247.28-247.30: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 034_example_7.asm:247.66-248.1: Error: unexpected end of line.
MT_ERROR: 034_example_7.asm:508.27-508.29: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 034_example_7.asm:508.105-509.1: Error: unexpected end of line.
MT_ERROR: 034_example_7.asm:661.27-661.30: Error: identifier cannot start with a digit: `3FF'.
MT_ERROR: 034_example_7.asm:661.19-661.26: Error: directive ADDRESS requires a single argument.
MT_WARNING: Warning: semantic analysis was not executed due to syntax error(s).
