MT_ERROR: 035_example_8.asm:114.49-114.51: Error: identifier cannot start with a digit: `6A'.
MT_ERROR: 035_example_8.asm:114.49-115.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:115.49-115.51: Error: identifier cannot start with a digit: `6B'.
MT_ERROR: 035_example_8.asm:115.49-116.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:116.49-116.51: Error: identifier cannot start with a digit: `6C'.
MT_ERROR: 035_example_8.asm:116.49-117.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:118.49-118.51: Error: identifier cannot start with a digit: `6E'.
MT_ERROR: 035_example_8.asm:118.49-119.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:119.49-119.51: Error: identifier cannot start with a digit: `6F'.
MT_ERROR: 035_example_8.asm:119.49-120.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:130.49-130.51: Error: identifier cannot start with a digit: `7A'.
MT_ERROR: 035_example_8.asm:130.49-131.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:140.49-140.51: Error: identifier cannot start with a digit: `4A'.
MT_ERROR: 035_example_8.asm:140.49-141.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:141.49-141.51: Error: identifier cannot start with a digit: `4B'.
MT_ERROR: 035_example_8.asm:141.49-142.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:142.49-142.51: Error: identifier cannot start with a digit: `4C'.
MT_ERROR: 035_example_8.asm:142.49-143.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:144.49-144.51: Error: identifier cannot start with a digit: `4E'.
MT_ERROR: 035_example_8.asm:144.49-145.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:145.49-145.51: Error: identifier cannot start with a digit: `4F'.
MT_ERROR: 035_example_8.asm:145.49-146.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:156.49-156.51: Error: identifier cannot start with a digit: `5A'.
MT_ERROR: 035_example_8.asm:156.49-157.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:167.53-167.55: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 035_example_8.asm:167.53-168.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:168.56-168.58: Error: identifier cannot start with a digit: `2E'.
MT_ERROR: 035_example_8.asm:168.56-169.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:169.58-169.60: Error: identifier cannot start with a digit: `3B'.
MT_ERROR: 035_example_8.asm:169.58-170.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:171.52-171.54: Error: identifier cannot start with a digit: `2B'.
MT_ERROR: 035_example_8.asm:171.52-172.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:172.53-172.55: Error: identifier cannot start with a digit: `2C'.
MT_ERROR: 035_example_8.asm:172.53-173.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:173.57-173.59: Error: identifier cannot start with a digit: `3C'.
MT_ERROR: 035_example_8.asm:173.70-174.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:174.60-174.62: Error: identifier cannot start with a digit: `3E'.
MT_ERROR: 035_example_8.asm:174.70-175.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:177.54-177.56: Error: identifier cannot start with a digit: `2F'.
MT_ERROR: 035_example_8.asm:177.70-178.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:181.50-181.52: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 035_example_8.asm:181.76-182.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:182.56-182.58: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 035_example_8.asm:182.70-183.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:453.36-453.38: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 035_example_8.asm:453.98-454.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:629.36-629.38: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 035_example_8.asm:629.100-630.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:994.36-994.38: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 035_example_8.asm:994.78-995.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:1122.35-1122.37: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 035_example_8.asm:1122.109-1123.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:1125.35-1125.37: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 035_example_8.asm:1125.123-1126.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:1141.39-1141.41: Error: identifier cannot start with a digit: `7B'.
MT_ERROR: 035_example_8.asm:1141.111-1142.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:1156.11-1156.25: Error: identifier cannot start with a digit: `1char_to_value'.
MT_ERROR: 035_example_8.asm:1156.11-1156.26: Error: unexpected :.
MT_ERROR: 035_example_8.asm:1172.11-1172.25: Error: identifier cannot start with a digit: `2char_to_value'.
MT_ERROR: 035_example_8.asm:1172.11-1172.26: Error: unexpected :.
MT_ERROR: 035_example_8.asm:1173.32-1173.46: Error: identifier cannot start with a digit: `1char_to_value'.
MT_ERROR: 035_example_8.asm:1173.27-1173.31: Error: invalid number of operands, instruction CALL takes 1 or 2 operand(s).
MT_ERROR: 035_example_8.asm:1182.32-1182.46: Error: identifier cannot start with a digit: `1char_to_value'.
MT_ERROR: 035_example_8.asm:1182.27-1182.31: Error: invalid number of operands, instruction CALL takes 1 or 2 operand(s).
MT_ERROR: 035_example_8.asm:1209.35-1209.37: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 035_example_8.asm:1209.87-1210.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:1218.35-1218.37: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 035_example_8.asm:1218.99-1219.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:1221.35-1221.37: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 035_example_8.asm:1221.102-1222.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:1292.35-1292.37: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 035_example_8.asm:1292.92-1293.1: Error: unexpected end of line.
MT_ERROR: 035_example_8.asm:1824.35-1824.38: Error: identifier cannot start with a digit: `3FE'.
MT_ERROR: 035_example_8.asm:1824.27-1824.34: Error: directive ADDRESS requires a single argument.
MT_ERROR: 035_example_8.asm:1832.35-1832.38: Error: identifier cannot start with a digit: `3FF'.
MT_ERROR: 035_example_8.asm:1832.27-1832.34: Error: directive ADDRESS requires a single argument.
MT_WARNING: Warning: semantic analysis was not executed due to error(s).
