MT_ERROR: 038_example_11.asm:72.41-72.43: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 038_example_11.asm:72.41-73.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:74.42-74.44: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 038_example_11.asm:74.42-75.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:76.44-76.46: Error: identifier cannot start with a digit: `0E'.
MT_ERROR: 038_example_11.asm:76.44-77.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:77.44-77.46: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 038_example_11.asm:77.44-78.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:109.40-109.42: Error: identifier cannot start with a digit: `6A'.
MT_ERROR: 038_example_11.asm:109.40-110.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:110.40-110.42: Error: identifier cannot start with a digit: `6B'.
MT_ERROR: 038_example_11.asm:110.40-111.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:111.40-111.42: Error: identifier cannot start with a digit: `6C'.
MT_ERROR: 038_example_11.asm:111.40-112.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:113.40-113.42: Error: identifier cannot start with a digit: `6E'.
MT_ERROR: 038_example_11.asm:113.40-114.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:114.40-114.42: Error: identifier cannot start with a digit: `6F'.
MT_ERROR: 038_example_11.asm:114.40-115.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:125.40-125.42: Error: identifier cannot start with a digit: `7A'.
MT_ERROR: 038_example_11.asm:125.40-126.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:135.40-135.42: Error: identifier cannot start with a digit: `4A'.
MT_ERROR: 038_example_11.asm:135.40-136.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:136.40-136.42: Error: identifier cannot start with a digit: `4B'.
MT_ERROR: 038_example_11.asm:136.40-137.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:137.40-137.42: Error: identifier cannot start with a digit: `4C'.
MT_ERROR: 038_example_11.asm:137.40-138.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:139.40-139.42: Error: identifier cannot start with a digit: `4E'.
MT_ERROR: 038_example_11.asm:139.40-140.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:140.40-140.42: Error: identifier cannot start with a digit: `4F'.
MT_ERROR: 038_example_11.asm:140.40-141.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:151.40-151.42: Error: identifier cannot start with a digit: `5A'.
MT_ERROR: 038_example_11.asm:151.40-152.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:162.44-162.46: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 038_example_11.asm:162.44-163.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:163.43-163.45: Error: identifier cannot start with a digit: `2E'.
MT_ERROR: 038_example_11.asm:163.43-164.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:164.49-164.51: Error: identifier cannot start with a digit: `3B'.
MT_ERROR: 038_example_11.asm:164.49-165.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:166.45-166.47: Error: identifier cannot start with a digit: `2F'.
MT_ERROR: 038_example_11.asm:166.58-167.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:167.43-167.45: Error: identifier cannot start with a digit: `2B'.
MT_ERROR: 038_example_11.asm:167.43-168.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:168.44-168.46: Error: identifier cannot start with a digit: `2C'.
MT_ERROR: 038_example_11.asm:168.44-169.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:169.48-169.50: Error: identifier cannot start with a digit: `3C'.
MT_ERROR: 038_example_11.asm:169.48-170.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:170.51-170.53: Error: identifier cannot start with a digit: `3E'.
MT_ERROR: 038_example_11.asm:170.51-171.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:174.47-174.49: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 038_example_11.asm:174.58-175.1: Error: unexpected end of line.
MT_ERROR: 038_example_11.asm:641.26-641.29: Error: identifier cannot start with a digit: `3FF'.
MT_ERROR: 038_example_11.asm:641.18-641.25: Error: directive ADDRESS requires a single argument.
MT_WARNING: Warning: semantic analysis was not executed due to syntax error(s).
