MT_ERROR: 041_example_14.asm:94.47-94.49: Error: identifier cannot start with a digit: `6A'.
MT_ERROR: 041_example_14.asm:94.47-95.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:95.47-95.49: Error: identifier cannot start with a digit: `6B'.
MT_ERROR: 041_example_14.asm:95.47-96.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:96.47-96.49: Error: identifier cannot start with a digit: `6C'.
MT_ERROR: 041_example_14.asm:96.47-97.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:98.47-98.49: Error: identifier cannot start with a digit: `6E'.
MT_ERROR: 041_example_14.asm:98.47-99.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:99.47-99.49: Error: identifier cannot start with a digit: `6F'.
MT_ERROR: 041_example_14.asm:99.47-100.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:110.47-110.49: Error: identifier cannot start with a digit: `7A'.
MT_ERROR: 041_example_14.asm:110.47-111.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:120.47-120.49: Error: identifier cannot start with a digit: `4A'.
MT_ERROR: 041_example_14.asm:120.47-121.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:121.47-121.49: Error: identifier cannot start with a digit: `4B'.
MT_ERROR: 041_example_14.asm:121.47-122.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:122.47-122.49: Error: identifier cannot start with a digit: `4C'.
MT_ERROR: 041_example_14.asm:122.47-123.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:124.47-124.49: Error: identifier cannot start with a digit: `4E'.
MT_ERROR: 041_example_14.asm:124.47-125.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:125.47-125.49: Error: identifier cannot start with a digit: `4F'.
MT_ERROR: 041_example_14.asm:125.47-126.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:136.47-136.49: Error: identifier cannot start with a digit: `5A'.
MT_ERROR: 041_example_14.asm:136.47-137.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:147.51-147.53: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 041_example_14.asm:147.51-148.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:148.54-148.56: Error: identifier cannot start with a digit: `2E'.
MT_ERROR: 041_example_14.asm:148.54-149.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:149.56-149.58: Error: identifier cannot start with a digit: `3B'.
MT_ERROR: 041_example_14.asm:149.56-150.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:151.50-151.52: Error: identifier cannot start with a digit: `2B'.
MT_ERROR: 041_example_14.asm:151.50-152.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:152.51-152.53: Error: identifier cannot start with a digit: `2C'.
MT_ERROR: 041_example_14.asm:152.51-153.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:153.55-153.57: Error: identifier cannot start with a digit: `3C'.
MT_ERROR: 041_example_14.asm:153.68-154.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:154.58-154.60: Error: identifier cannot start with a digit: `3E'.
MT_ERROR: 041_example_14.asm:154.68-155.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:157.52-157.54: Error: identifier cannot start with a digit: `2F'.
MT_ERROR: 041_example_14.asm:157.68-158.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:161.48-161.50: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 041_example_14.asm:161.74-162.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:162.54-162.56: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 041_example_14.asm:162.68-163.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:195.46-195.48: Error: identifier cannot start with a digit: `2B'.
MT_ERROR: 041_example_14.asm:195.93-196.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:797.34-797.36: Error: identifier cannot start with a digit: `9F'.
MT_ERROR: 041_example_14.asm:797.84-798.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:1080.33-1080.35: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 041_example_14.asm:1080.107-1081.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:1083.33-1083.35: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 041_example_14.asm:1083.121-1084.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:1099.37-1099.39: Error: identifier cannot start with a digit: `7B'.
MT_ERROR: 041_example_14.asm:1099.109-1100.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:1114.9-1114.23: Error: identifier cannot start with a digit: `1char_to_value'.
MT_ERROR: 041_example_14.asm:1114.9-1114.24: Error: unexpected :.
MT_ERROR: 041_example_14.asm:1130.9-1130.23: Error: identifier cannot start with a digit: `2char_to_value'.
MT_ERROR: 041_example_14.asm:1130.9-1130.24: Error: unexpected :.
MT_ERROR: 041_example_14.asm:1131.30-1131.44: Error: identifier cannot start with a digit: `1char_to_value'.
MT_ERROR: 041_example_14.asm:1131.25-1131.29: Error: invalid number of operands, instruction CALL takes 1 or 2 operand(s).
MT_ERROR: 041_example_14.asm:1140.30-1140.44: Error: identifier cannot start with a digit: `1char_to_value'.
MT_ERROR: 041_example_14.asm:1140.25-1140.29: Error: invalid number of operands, instruction CALL takes 1 or 2 operand(s).
MT_ERROR: 041_example_14.asm:1167.33-1167.35: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 041_example_14.asm:1167.85-1168.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:1176.33-1176.35: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 041_example_14.asm:1176.97-1177.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:1179.33-1179.35: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 041_example_14.asm:1179.100-1180.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:1250.33-1250.35: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 041_example_14.asm:1250.90-1251.1: Error: unexpected end of line.
MT_ERROR: 041_example_14.asm:1657.33-1657.36: Error: identifier cannot start with a digit: `3F5'.
MT_ERROR: 041_example_14.asm:1657.25-1657.32: Error: directive ADDRESS requires a single argument.
MT_ERROR: 041_example_14.asm:1674.33-1674.36: Error: identifier cannot start with a digit: `3FF'.
MT_ERROR: 041_example_14.asm:1674.25-1674.32: Error: directive ADDRESS requires a single argument.
MT_WARNING: Warning: semantic analysis was not executed due to syntax error(s).
