MT_ERROR: 042_example_15.asm:133.41-133.43: Error: identifier cannot start with a digit: `6A'.
MT_ERROR: 042_example_15.asm:133.41-134.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:134.41-134.43: Error: identifier cannot start with a digit: `6B'.
MT_ERROR: 042_example_15.asm:134.41-135.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:135.41-135.43: Error: identifier cannot start with a digit: `6C'.
MT_ERROR: 042_example_15.asm:135.41-136.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:137.41-137.43: Error: identifier cannot start with a digit: `6E'.
MT_ERROR: 042_example_15.asm:137.41-138.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:138.41-138.43: Error: identifier cannot start with a digit: `6F'.
MT_ERROR: 042_example_15.asm:138.41-139.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:149.41-149.43: Error: identifier cannot start with a digit: `7A'.
MT_ERROR: 042_example_15.asm:149.41-150.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:159.41-159.43: Error: identifier cannot start with a digit: `4A'.
MT_ERROR: 042_example_15.asm:159.41-160.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:160.41-160.43: Error: identifier cannot start with a digit: `4B'.
MT_ERROR: 042_example_15.asm:160.41-161.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:161.41-161.43: Error: identifier cannot start with a digit: `4C'.
MT_ERROR: 042_example_15.asm:161.41-162.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:163.41-163.43: Error: identifier cannot start with a digit: `4E'.
MT_ERROR: 042_example_15.asm:163.41-164.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:164.41-164.43: Error: identifier cannot start with a digit: `4F'.
MT_ERROR: 042_example_15.asm:164.41-165.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:175.41-175.43: Error: identifier cannot start with a digit: `5A'.
MT_ERROR: 042_example_15.asm:175.41-176.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:186.45-186.47: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 042_example_15.asm:186.45-187.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:187.44-187.46: Error: identifier cannot start with a digit: `2E'.
MT_ERROR: 042_example_15.asm:187.44-188.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:188.50-188.52: Error: identifier cannot start with a digit: `3B'.
MT_ERROR: 042_example_15.asm:188.50-189.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:190.46-190.48: Error: identifier cannot start with a digit: `2F'.
MT_ERROR: 042_example_15.asm:190.59-191.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:191.44-191.46: Error: identifier cannot start with a digit: `2B'.
MT_ERROR: 042_example_15.asm:191.44-192.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:192.45-192.47: Error: identifier cannot start with a digit: `2C'.
MT_ERROR: 042_example_15.asm:192.45-193.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:193.49-193.51: Error: identifier cannot start with a digit: `3C'.
MT_ERROR: 042_example_15.asm:193.49-194.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:194.52-194.54: Error: identifier cannot start with a digit: `3E'.
MT_ERROR: 042_example_15.asm:194.52-195.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:198.48-198.50: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 042_example_15.asm:198.59-199.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:219.28-219.30: Error: identifier cannot start with a digit: `2E'.
MT_ERROR: 042_example_15.asm:219.74-220.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:286.27-286.29: Error: identifier cannot start with a digit: `7F'.
MT_ERROR: 042_example_15.asm:286.66-287.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:566.26-566.28: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 042_example_15.asm:566.91-567.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:601.28-601.30: Error: identifier cannot start with a digit: `0E'.
MT_ERROR: 042_example_15.asm:601.90-602.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:656.28-656.30: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 042_example_15.asm:656.71-657.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:683.27-683.29: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 042_example_15.asm:683.97-684.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:687.27-687.29: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 042_example_15.asm:687.97-688.1: Error: unexpected end of line.
MT_ERROR: 042_example_15.asm:732.27-732.30: Error: identifier cannot start with a digit: `3FF'.
MT_ERROR: 042_example_15.asm:732.19-732.26: Error: directive ADDRESS requires a single argument.
MT_WARNING: Warning: semantic analysis was not executed due to syntax error(s).
