MT_ERROR: 043_example_16 .asm:79.54-79.56: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 043_example_16 .asm:79.102-80.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:81.54-81.56: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 043_example_16 .asm:81.92-82.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:84.54-84.56: Error: identifier cannot start with a digit: `0E'.
MT_ERROR: 043_example_16 .asm:84.92-85.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:85.54-85.56: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 043_example_16 .asm:85.92-86.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:112.54-112.56: Error: identifier cannot start with a digit: `1A'.
MT_ERROR: 043_example_16 .asm:112.103-113.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:114.54-114.56: Error: identifier cannot start with a digit: `1C'.
MT_ERROR: 043_example_16 .asm:114.92-115.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:141.41-141.43: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 043_example_16 .asm:141.41-142.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:145.41-145.43: Error: identifier cannot start with a digit: `0C'.
MT_ERROR: 043_example_16 .asm:145.100-146.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:174.44-174.46: Error: identifier cannot start with a digit: `6A'.
MT_ERROR: 043_example_16 .asm:174.44-175.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:175.44-175.46: Error: identifier cannot start with a digit: `6B'.
MT_ERROR: 043_example_16 .asm:175.44-176.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:176.44-176.46: Error: identifier cannot start with a digit: `6C'.
MT_ERROR: 043_example_16 .asm:176.44-177.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:178.44-178.46: Error: identifier cannot start with a digit: `6E'.
MT_ERROR: 043_example_16 .asm:178.44-179.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:179.44-179.46: Error: identifier cannot start with a digit: `6F'.
MT_ERROR: 043_example_16 .asm:179.44-180.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:190.44-190.46: Error: identifier cannot start with a digit: `7A'.
MT_ERROR: 043_example_16 .asm:190.44-191.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:200.44-200.46: Error: identifier cannot start with a digit: `4A'.
MT_ERROR: 043_example_16 .asm:200.44-201.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:201.44-201.46: Error: identifier cannot start with a digit: `4B'.
MT_ERROR: 043_example_16 .asm:201.44-202.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:202.44-202.46: Error: identifier cannot start with a digit: `4C'.
MT_ERROR: 043_example_16 .asm:202.44-203.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:204.44-204.46: Error: identifier cannot start with a digit: `4E'.
MT_ERROR: 043_example_16 .asm:204.44-205.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:205.44-205.46: Error: identifier cannot start with a digit: `4F'.
MT_ERROR: 043_example_16 .asm:205.44-206.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:216.44-216.46: Error: identifier cannot start with a digit: `5A'.
MT_ERROR: 043_example_16 .asm:216.44-217.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:227.48-227.50: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 043_example_16 .asm:227.48-228.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:228.47-228.49: Error: identifier cannot start with a digit: `2E'.
MT_ERROR: 043_example_16 .asm:228.47-229.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:229.53-229.55: Error: identifier cannot start with a digit: `3B'.
MT_ERROR: 043_example_16 .asm:229.53-230.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:231.49-231.51: Error: identifier cannot start with a digit: `2F'.
MT_ERROR: 043_example_16 .asm:231.65-232.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:232.47-232.49: Error: identifier cannot start with a digit: `2B'.
MT_ERROR: 043_example_16 .asm:232.47-233.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:233.48-233.50: Error: identifier cannot start with a digit: `2C'.
MT_ERROR: 043_example_16 .asm:233.48-234.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:234.52-234.54: Error: identifier cannot start with a digit: `3C'.
MT_ERROR: 043_example_16 .asm:234.52-235.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:235.55-235.57: Error: identifier cannot start with a digit: `3E'.
MT_ERROR: 043_example_16 .asm:235.55-236.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:239.51-239.53: Error: identifier cannot start with a digit: `3F'.
MT_ERROR: 043_example_16 .asm:239.65-240.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:273.31-273.33: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 043_example_16 .asm:273.104-274.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:619.34-619.36: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 043_example_16 .asm:619.34-620.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:623.34-623.36: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 043_example_16 .asm:623.34-624.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:627.34-627.36: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 043_example_16 .asm:627.34-628.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:631.34-631.36: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 043_example_16 .asm:631.34-632.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:635.34-635.36: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 043_example_16 .asm:635.34-636.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:878.34-878.36: Error: identifier cannot start with a digit: `7B'.
MT_ERROR: 043_example_16 .asm:878.106-879.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:908.6-908.20: Error: identifier cannot start with a digit: `1char_to_value'.
MT_ERROR: 043_example_16 .asm:908.6-908.21: Error: unexpected :.
MT_ERROR: 043_example_16 .asm:956.30-956.32: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 043_example_16 .asm:956.87-957.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:996.30-996.32: Error: identifier cannot start with a digit: `0F'.
MT_ERROR: 043_example_16 .asm:996.82-997.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:1005.30-1005.32: Error: identifier cannot start with a digit: `0A'.
MT_ERROR: 043_example_16 .asm:1005.94-1006.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:1008.30-1008.32: Error: identifier cannot start with a digit: `3A'.
MT_ERROR: 043_example_16 .asm:1008.97-1009.1: Error: unexpected end of line.
MT_ERROR: 043_example_16 .asm:1317.30-1317.33: Error: identifier cannot start with a digit: `3FF'.
MT_ERROR: 043_example_16 .asm:1317.22-1317.29: Error: directive ADDRESS requires a single argument.
MT_WARNING: Warning: exact device not specified, using KCPSM6 by default.
MT_ERROR: 043_example_16 .asm:910.26-910.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:910.30-910.32: Error: symbol not defined: `F6'.
MT_ERROR: 043_example_16 .asm:925.27-925.29: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:925.31-925.33: Error: symbol not defined: `S3'.
MT_ERROR: 043_example_16 .asm:928.27-928.29: Error: symbol not defined: `S3'.
MT_ERROR: 043_example_16 .asm:928.31-928.33: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:929.26-929.28: Error: symbol not defined: `S3'.
MT_ERROR: 043_example_16 .asm:930.26-930.28: Error: symbol not defined: `S3'.
MT_ERROR: 043_example_16 .asm:931.26-931.28: Error: symbol not defined: `S3'.
MT_ERROR: 043_example_16 .asm:932.26-932.28: Error: symbol not defined: `S3'.
MT_ERROR: 043_example_16 .asm:933.27-933.29: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:933.31-933.33: Error: symbol not defined: `S2'.
MT_ERROR: 043_example_16 .asm:936.25-936.27: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:936.29-936.31: Error: symbol not defined: `S3'.
MT_ERROR: 043_example_16 .asm:946.26-946.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:946.30-946.32: Error: symbol not defined: `B9'.
MT_ERROR: 043_example_16 .asm:948.26-948.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:948.30-948.32: Error: symbol not defined: `E9'.
MT_ERROR: 043_example_16 .asm:950.26-950.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:951.31-951.43: Error: symbol not defined: `ASCII_LETTER'.
MT_ERROR: 043_example_16 .asm:952.26-952.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:954.26-954.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:954.30-954.32: Error: symbol not defined: `F6'.
MT_ERROR: 043_example_16 .asm:968.26-968.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:968.30-968.32: Error: symbol not defined: `C6'.
MT_ERROR: 043_example_16 .asm:970.26-970.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:970.30-970.32: Error: symbol not defined: `F6'.
MT_ERROR: 043_example_16 .asm:988.27-988.29: Error: symbol not defined: `S1'.
MT_ERROR: 043_example_16 .asm:988.31-988.33: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:989.26-989.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:990.26-990.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:991.26-991.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:992.26-992.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:993.27-993.39: Error: symbol not defined: `HEX_TO_ASCII'.
MT_ERROR: 043_example_16 .asm:994.27-994.29: Error: symbol not defined: `S2'.
MT_ERROR: 043_example_16 .asm:994.31-994.33: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:995.27-995.29: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:995.31-995.33: Error: symbol not defined: `S1'.
MT_ERROR: 043_example_16 .asm:997.27-997.39: Error: symbol not defined: `HEX_TO_ASCII'.
MT_ERROR: 043_example_16 .asm:998.27-998.29: Error: symbol not defined: `S1'.
MT_ERROR: 043_example_16 .asm:998.31-998.33: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:1006.30-1006.41: Error: symbol not defined: `NUMBER_CHAR'.
MT_ERROR: 043_example_16 .asm:1007.26-1007.28: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:1017.27-1017.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1017.38-1017.40: Error: symbol not defined: `S2'.
MT_ERROR: 043_example_16 .asm:1018.27-1018.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1019.27-1019.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1019.38-1019.40: Error: symbol not defined: `S1'.
MT_ERROR: 043_example_16 .asm:1020.27-1020.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1030.27-1030.39: Error: symbol not defined: `HEX_TO_ASCII'.
MT_ERROR: 043_example_16 .asm:1031.27-1031.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1031.38-1031.40: Error: symbol not defined: `S0'.
MT_ERROR: 043_example_16 .asm:1032.27-1032.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1044.27-1044.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1044.38-1044.50: Error: symbol not defined: `CHARACTER_CR'.
MT_ERROR: 043_example_16 .asm:1045.27-1045.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1050.27-1050.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1050.38-1050.53: Error: symbol not defined: `CHARACTER_SPACE'.
MT_ERROR: 043_example_16 .asm:1051.27-1051.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1058.27-1058.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1058.38-1058.50: Error: symbol not defined: `CHARACTER_BS'.
MT_ERROR: 043_example_16 .asm:1059.27-1059.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1067.27-1067.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1067.38-1067.49: Error: symbol not defined: `CHARACTER_P'.
MT_ERROR: 043_example_16 .asm:1068.27-1068.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1069.27-1069.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1069.38-1069.49: Error: symbol not defined: `CHARACTER_I'.
MT_ERROR: 043_example_16 .asm:1070.27-1070.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1071.27-1071.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1071.38-1071.49: Error: symbol not defined: `CHARACTER_C'.
MT_ERROR: 043_example_16 .asm:1072.27-1072.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1073.27-1073.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1073.38-1073.49: Error: symbol not defined: `CHARACTER_O'.
MT_ERROR: 043_example_16 .asm:1074.27-1074.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1075.27-1075.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1075.38-1075.49: Error: symbol not defined: `CHARACTER_B'.
MT_ERROR: 043_example_16 .asm:1076.27-1076.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1077.27-1077.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1077.38-1077.49: Error: symbol not defined: `CHARACTER_L'.
MT_ERROR: 043_example_16 .asm:1078.27-1078.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1079.27-1079.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1079.38-1079.49: Error: symbol not defined: `CHARACTER_A'.
MT_ERROR: 043_example_16 .asm:1080.27-1080.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1081.27-1081.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1081.38-1081.49: Error: symbol not defined: `CHARACTER_Z'.
MT_ERROR: 043_example_16 .asm:1082.27-1082.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1083.27-1083.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1083.38-1083.49: Error: symbol not defined: `CHARACTER_E'.
MT_ERROR: 043_example_16 .asm:1084.27-1084.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1086.27-1086.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1086.38-1086.49: Error: symbol not defined: `CHARACTER_L'.
MT_ERROR: 043_example_16 .asm:1087.27-1087.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1088.27-1088.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1088.38-1088.49: Error: symbol not defined: `CHARACTER_I'.
MT_ERROR: 043_example_16 .asm:1089.27-1089.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1090.27-1090.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1090.38-1090.49: Error: symbol not defined: `CHARACTER_N'.
MT_ERROR: 043_example_16 .asm:1091.27-1091.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1092.27-1092.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1092.38-1092.49: Error: symbol not defined: `CHARACTER_E'.
MT_ERROR: 043_example_16 .asm:1093.27-1093.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1095.27-1095.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1095.38-1095.49: Error: symbol not defined: `CHARACTER_S'.
MT_ERROR: 043_example_16 .asm:1096.27-1096.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1097.27-1097.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1097.38-1097.49: Error: symbol not defined: `CHARACTER_T'.
MT_ERROR: 043_example_16 .asm:1098.27-1098.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1099.27-1099.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1099.38-1099.49: Error: symbol not defined: `CHARACTER_O'.
MT_ERROR: 043_example_16 .asm:1100.27-1100.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1101.27-1101.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1101.38-1101.49: Error: symbol not defined: `CHARACTER_R'.
MT_ERROR: 043_example_16 .asm:1102.27-1102.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1103.27-1103.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1103.38-1103.49: Error: symbol not defined: `CHARACTER_E'.
MT_ERROR: 043_example_16 .asm:1104.27-1104.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1106.27-1106.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1106.38-1106.49: Error: symbol not defined: `CHARACTER_T'.
MT_ERROR: 043_example_16 .asm:1107.27-1107.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1108.27-1108.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1108.38-1108.49: Error: symbol not defined: `CHARACTER_E'.
MT_ERROR: 043_example_16 .asm:1109.27-1109.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1110.27-1110.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1110.38-1110.49: Error: symbol not defined: `CHARACTER_S'.
MT_ERROR: 043_example_16 .asm:1111.27-1111.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1112.27-1112.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1112.38-1112.49: Error: symbol not defined: `CHARACTER_T'.
MT_ERROR: 043_example_16 .asm:1113.27-1113.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1114.27-1114.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1114.38-1114.49: Error: symbol not defined: `CHARACTER_E'.
MT_ERROR: 043_example_16 .asm:1115.27-1115.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1116.27-1116.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1116.38-1116.49: Error: symbol not defined: `CHARACTER_R'.
MT_ERROR: 043_example_16 .asm:1117.27-1117.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1126.27-1126.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1126.38-1126.49: Error: symbol not defined: `CHARACTER_K'.
MT_ERROR: 043_example_16 .asm:1127.27-1127.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1128.27-1128.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1128.38-1128.49: Error: symbol not defined: `CHARACTER_C'.
MT_ERROR: 043_example_16 .asm:1129.27-1129.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1130.27-1130.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1130.38-1130.49: Error: symbol not defined: `CHARACTER_P'.
MT_ERROR: 043_example_16 .asm:1131.27-1131.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1132.27-1132.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1132.38-1132.49: Error: symbol not defined: `CHARACTER_S'.
MT_ERROR: 043_example_16 .asm:1133.27-1133.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1134.27-1134.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1134.38-1134.49: Error: symbol not defined: `CHARACTER_M'.
MT_ERROR: 043_example_16 .asm:1135.27-1135.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1136.27-1136.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1136.38-1136.49: Error: symbol not defined: `CHARACTER_3'.
MT_ERROR: 043_example_16 .asm:1137.27-1137.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1141.27-1141.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1141.38-1141.60: Error: symbol not defined: `CHARACTER_GREATER_THAN'.
MT_ERROR: 043_example_16 .asm:1142.27-1142.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1148.27-1148.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1148.38-1148.49: Error: symbol not defined: `CHARACTER_O'.
MT_ERROR: 043_example_16 .asm:1149.27-1149.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1150.27-1150.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1150.38-1150.49: Error: symbol not defined: `CHARACTER_V'.
MT_ERROR: 043_example_16 .asm:1151.27-1151.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1152.27-1152.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1152.38-1152.49: Error: symbol not defined: `CHARACTER_E'.
MT_ERROR: 043_example_16 .asm:1153.27-1153.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1154.27-1154.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1154.38-1154.49: Error: symbol not defined: `CHARACTER_R'.
MT_ERROR: 043_example_16 .asm:1155.27-1155.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1156.27-1156.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1156.38-1156.49: Error: symbol not defined: `CHARACTER_F'.
MT_ERROR: 043_example_16 .asm:1157.27-1157.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1158.27-1158.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1158.38-1158.49: Error: symbol not defined: `CHARACTER_L'.
MT_ERROR: 043_example_16 .asm:1159.27-1159.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1160.27-1160.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1160.38-1160.49: Error: symbol not defined: `CHARACTER_O'.
MT_ERROR: 043_example_16 .asm:1161.27-1161.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1162.27-1162.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1162.38-1162.49: Error: symbol not defined: `CHARACTER_W'.
MT_ERROR: 043_example_16 .asm:1163.27-1163.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1168.27-1168.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1168.38-1168.49: Error: symbol not defined: `CHARACTER_E'.
MT_ERROR: 043_example_16 .asm:1169.27-1169.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1170.27-1170.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1170.38-1170.49: Error: symbol not defined: `CHARACTER_R'.
MT_ERROR: 043_example_16 .asm:1171.27-1171.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1172.27-1172.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1173.27-1173.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1173.38-1173.49: Error: symbol not defined: `CHARACTER_O'.
MT_ERROR: 043_example_16 .asm:1174.27-1174.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1175.27-1175.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1175.38-1175.49: Error: symbol not defined: `CHARACTER_R'.
MT_ERROR: 043_example_16 .asm:1176.27-1176.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1184.27-1184.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1184.38-1184.49: Error: symbol not defined: `CHARACTER_O'.
MT_ERROR: 043_example_16 .asm:1185.27-1185.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1186.27-1186.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1186.38-1186.49: Error: symbol not defined: `CHARACTER_K'.
MT_ERROR: 043_example_16 .asm:1187.27-1187.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1194.27-1194.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1194.38-1194.49: Error: symbol not defined: `CHARACTER_C'.
MT_ERROR: 043_example_16 .asm:1195.27-1195.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1196.27-1196.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1196.38-1196.49: Error: symbol not defined: `CHARACTER_Y'.
MT_ERROR: 043_example_16 .asm:1197.27-1197.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1198.27-1198.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1198.38-1198.49: Error: symbol not defined: `CHARACTER_C'.
MT_ERROR: 043_example_16 .asm:1199.27-1199.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1200.27-1200.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1200.38-1200.49: Error: symbol not defined: `CHARACTER_L'.
MT_ERROR: 043_example_16 .asm:1201.27-1201.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1202.27-1202.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1202.38-1202.49: Error: symbol not defined: `CHARACTER_E'.
MT_ERROR: 043_example_16 .asm:1203.27-1203.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1208.27-1208.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1208.38-1208.49: Error: symbol not defined: `CHARACTER_I'.
MT_ERROR: 043_example_16 .asm:1209.27-1209.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1210.27-1210.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1210.38-1210.49: Error: symbol not defined: `CHARACTER_N'.
MT_ERROR: 043_example_16 .asm:1211.27-1211.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1212.27-1212.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1212.38-1212.49: Error: symbol not defined: `CHARACTER_P'.
MT_ERROR: 043_example_16 .asm:1213.27-1213.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1214.27-1214.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1214.38-1214.49: Error: symbol not defined: `CHARACTER_U'.
MT_ERROR: 043_example_16 .asm:1215.27-1215.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1216.27-1216.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1216.38-1216.49: Error: symbol not defined: `CHARACTER_T'.
MT_ERROR: 043_example_16 .asm:1217.27-1217.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1223.27-1223.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1223.38-1223.49: Error: symbol not defined: `CHARACTER_7'.
MT_ERROR: 043_example_16 .asm:1224.27-1224.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1225.27-1225.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1225.38-1225.49: Error: symbol not defined: `CHARACTER_6'.
MT_ERROR: 043_example_16 .asm:1226.27-1226.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1227.27-1227.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1227.38-1227.49: Error: symbol not defined: `CHARACTER_8'.
MT_ERROR: 043_example_16 .asm:1228.27-1228.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1232.27-1232.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1232.38-1232.49: Error: symbol not defined: `CHARACTER_1'.
MT_ERROR: 043_example_16 .asm:1233.27-1233.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1234.27-1234.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1234.38-1234.49: Error: symbol not defined: `CHARACTER_0'.
MT_ERROR: 043_example_16 .asm:1235.27-1235.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1236.27-1236.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1236.38-1236.49: Error: symbol not defined: `CHARACTER_2'.
MT_ERROR: 043_example_16 .asm:1237.27-1237.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1238.27-1238.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1238.38-1238.49: Error: symbol not defined: `CHARACTER_4'.
MT_ERROR: 043_example_16 .asm:1239.27-1239.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1247.27-1247.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1247.38-1247.49: Error: symbol not defined: `CHARACTER_A'.
MT_ERROR: 043_example_16 .asm:1248.27-1248.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1252.27-1252.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1252.38-1252.49: Error: symbol not defined: `CHARACTER_B'.
MT_ERROR: 043_example_16 .asm:1253.27-1253.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1257.27-1257.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1257.38-1257.49: Error: symbol not defined: `CHARACTER_C'.
MT_ERROR: 043_example_16 .asm:1258.27-1258.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1260.27-1260.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1260.38-1260.49: Error: symbol not defined: `CHARACTER_1'.
MT_ERROR: 043_example_16 .asm:1261.27-1261.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1262.27-1262.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1262.38-1262.49: Error: symbol not defined: `CHARACTER_5'.
MT_ERROR: 043_example_16 .asm:1263.27-1263.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1264.27-1264.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1264.38-1264.49: Error: symbol not defined: `CHARACTER_3'.
MT_ERROR: 043_example_16 .asm:1265.27-1265.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1266.27-1266.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1266.38-1266.49: Error: symbol not defined: `CHARACTER_6'.
MT_ERROR: 043_example_16 .asm:1267.27-1267.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1274.27-1274.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1274.38-1274.49: Error: symbol not defined: `CHARACTER_A'.
MT_ERROR: 043_example_16 .asm:1275.27-1275.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1279.27-1279.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1279.38-1279.49: Error: symbol not defined: `CHARACTER_B'.
MT_ERROR: 043_example_16 .asm:1280.27-1280.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1284.27-1284.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1284.38-1284.49: Error: symbol not defined: `CHARACTER_1'.
MT_ERROR: 043_example_16 .asm:1285.27-1285.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1286.27-1286.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1286.38-1286.49: Error: symbol not defined: `CHARACTER_2'.
MT_ERROR: 043_example_16 .asm:1287.27-1287.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1288.27-1288.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1288.38-1288.49: Error: symbol not defined: `CHARACTER_8'.
MT_ERROR: 043_example_16 .asm:1289.27-1289.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1290.27-1290.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1290.38-1290.49: Error: symbol not defined: `CHARACTER_0'.
MT_ERROR: 043_example_16 .asm:1291.27-1291.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1294.27-1294.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1294.38-1294.49: Error: symbol not defined: `CHARACTER_1'.
MT_ERROR: 043_example_16 .asm:1295.27-1295.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1296.27-1296.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1296.38-1296.49: Error: symbol not defined: `CHARACTER_9'.
MT_ERROR: 043_example_16 .asm:1297.27-1297.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1298.27-1298.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1298.38-1298.49: Error: symbol not defined: `CHARACTER_2'.
MT_ERROR: 043_example_16 .asm:1299.27-1299.39: Error: symbol not defined: `SEND_TO_UART'.
MT_ERROR: 043_example_16 .asm:1300.27-1300.36: Error: symbol not defined: `UART_DATA'.
MT_ERROR: 043_example_16 .asm:1300.38-1300.49: Error: symbol not defined: `CHARACTER_0'.
MT_ERROR: 043_example_16 .asm:1301.27-1301.39: Error: symbol not defined: `SEND_TO_UART'.
