MT_WARNING: 0003_interrupt.asm:11.24-11.29: Warning: instruction `JUMP Z, aaa' requires operand #2 to be of type(s): label; while the given operand is of type: number.
MT_WARNING: 0003_interrupt.asm:12.24-12.29: Warning: instruction `JUMP NZ, aaa' requires operand #2 to be of type(s): label; while the given operand is of type: number.
MT_WARNING: 0003_interrupt.asm:13.24-13.29: Warning: instruction `JUMP C, aaa' requires operand #2 to be of type(s): label; while the given operand is of type: number.
MT_WARNING: 0003_interrupt.asm:14.24-14.29: Warning: instruction `JUMP NC, aaa' requires operand #2 to be of type(s): label; while the given operand is of type: number.
