A  . . . . . . . . . . . . . . . . . NUMBER 0x3FFFB NOT USED CONSTANT    0011_directives.asm:118.1-118.19
A1 . . . . . . . . . . . . . . . . . NUMBER 0x00244 NOT USED CONSTANT    0011_directives.asm:6.1-6.20
A10  . . . . . . . . . . . . . . . . NUMBER 0x00011 NOT USED CONSTANT    0011_directives.asm:15.1-15.20
A11  . . . . . . . . . . . . . . . . NUMBER 0x000AA NOT USED CONSTANT    0011_directives.asm:16.1-16.20
A12  . . . . . . . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    0011_directives.asm:17.1-17.21
A2 . . . . . . . . . . . . . . . . . NUMBER 0x3FFFF NOT USED CONSTANT    0011_directives.asm:7.1-7.25
A3 . . . . . . . . . . . . . . . . . NUMBER 0x00000 NOT USED CONSTANT    0011_directives.asm:8.1-8.18
A4 . . . . . . . . . . . . . . . . . NUMBER 0x00019 NOT USED CONSTANT    0011_directives.asm:9.1-9.24
A5 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0011_directives.asm:10.1-10.23
A6 . . . . . . . . . . . . . . . . . NUMBER 0x00011 NOT USED CONSTANT    0011_directives.asm:11.1-11.27
A7 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0011_directives.asm:12.1-12.27
A8 . . . . . . . . . . . . . . . . . NUMBER 0x00003 NOT USED CONSTANT    0011_directives.asm:13.1-13.18
A9 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0011_directives.asm:14.1-14.19
ABYSS  . . . . . . . . . . . . . . . NUMBER 0x00008 NOT USED CONSTANT    0011_directives.asm:123.1-123.47
AHOJ . . . . . . . . . . . . . . . . REG.   0x00001 NOT USED CONSTANT    0011_directives.asm:58.1-58.23
B  . . . . . . . . . . . . . . . . . NUMBER 0x00005 NOT USED CONSTANT    0011_directives.asm:119.1-119.18
B1 . . . . . . . . . . . . . . . . . NUMBER 0x00244 NOT USED REDEFINABLE 0011_directives.asm:19.1-19.20
B10  . . . . . . . . . . . . . . . . NUMBER 0x00011 NOT USED REDEFINABLE 0011_directives.asm:28.1-28.20
B11  . . . . . . . . . . . . . . . . NUMBER 0x000AA NOT USED REDEFINABLE 0011_directives.asm:29.1-29.20
B12  . . . . . . . . . . . . . . . . NUMBER 0x00004 NOT USED REDEFINABLE 0011_directives.asm:30.1-30.21
B2 . . . . . . . . . . . . . . . . . NUMBER 0x3FFFF NOT USED REDEFINABLE 0011_directives.asm:20.1-20.25
B3 . . . . . . . . . . . . . . . . . NUMBER 0x00000 NOT USED REDEFINABLE 0011_directives.asm:21.1-21.18
B4 . . . . . . . . . . . . . . . . . NUMBER 0x00019 NOT USED REDEFINABLE 0011_directives.asm:22.1-22.24
B5 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED REDEFINABLE 0011_directives.asm:23.1-23.23
B6 . . . . . . . . . . . . . . . . . NUMBER 0x00011 NOT USED REDEFINABLE 0011_directives.asm:24.1-24.27
B7 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED REDEFINABLE 0011_directives.asm:25.1-25.27
B8 . . . . . . . . . . . . . . . . . NUMBER 0x00003 NOT USED REDEFINABLE 0011_directives.asm:26.1-26.18
B9 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED REDEFINABLE 0011_directives.asm:27.1-27.19
C1 . . . . . . . . . . . . . . . . . NUMBER 0x00222 NOT USED CONSTANT    0011_directives.asm:32.1-32.23
C10  . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0011_directives.asm:41.1-41.23
C11  . . . . . . . . . . . . . . . . NUMBER 0x000FE NOT USED CONSTANT    0011_directives.asm:42.1-42.24
C12  . . . . . . . . . . . . . . . . NUMBER 0x00003 NOT USED CONSTANT    0011_directives.asm:43.1-43.25
C2 . . . . . . . . . . . . . . . . . NUMBER 0x0FFFF NOT USED CONSTANT    0011_directives.asm:33.1-33.26
C3 . . . . . . . . . . . . . . . . . NUMBER 0x0000C NOT USED CONSTANT    0011_directives.asm:34.1-34.22
C4 . . . . . . . . . . . . . . . . . NUMBER 0x00000 NOT USED CONSTANT    0011_directives.asm:35.1-35.21
C5 . . . . . . . . . . . . . . . . . NUMBER 0x00000 NOT USED CONSTANT    0011_directives.asm:36.1-36.30
C6 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0011_directives.asm:37.1-37.25
C7 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0011_directives.asm:38.1-38.24
C8 . . . . . . . . . . . . . . . . . NUMBER 0x00015 NOT USED CONSTANT    0011_directives.asm:39.1-39.30
C9 . . . . . . . . . . . . . . . . . NUMBER 0x0001E NOT USED CONSTANT    0011_directives.asm:40.1-40.27
D1 . . . . . . . . . . . . . . . . . NUMBER 0x00222 NOT USED REDEFINABLE 0011_directives.asm:45.1-45.23
D10  . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED REDEFINABLE 0011_directives.asm:54.1-54.23
D11  . . . . . . . . . . . . . . . . NUMBER 0x000FE NOT USED REDEFINABLE 0011_directives.asm:55.1-55.24
D12  . . . . . . . . . . . . . . . . NUMBER 0x00003 NOT USED REDEFINABLE 0011_directives.asm:56.1-56.25
D2 . . . . . . . . . . . . . . . . . NUMBER 0x0FFFF NOT USED REDEFINABLE 0011_directives.asm:46.1-46.26
D3 . . . . . . . . . . . . . . . . . NUMBER 0x0000C NOT USED REDEFINABLE 0011_directives.asm:47.1-47.22
D4 . . . . . . . . . . . . . . . . . NUMBER 0x00000 NOT USED REDEFINABLE 0011_directives.asm:48.1-48.21
D5 . . . . . . . . . . . . . . . . . NUMBER 0x00000 NOT USED REDEFINABLE 0011_directives.asm:49.1-49.30
D6 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED REDEFINABLE 0011_directives.asm:50.1-50.25
D7 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED REDEFINABLE 0011_directives.asm:51.1-51.24
D8 . . . . . . . . . . . . . . . . . NUMBER 0x00015 NOT USED REDEFINABLE 0011_directives.asm:52.1-52.30
D9 . . . . . . . . . . . . . . . . . NUMBER 0x0001E NOT USED REDEFINABLE 0011_directives.asm:53.1-53.27
DOLE . . . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    0011_directives.asm:62.1-62.23
F1 . . . . . . . . . . . . . . . . . REG.   0x00001 NOT USED CONSTANT    0011_directives.asm:67.1-67.18
F2 . . . . . . . . . . . . . . . . . REG.   0x00002 NOT USED CONSTANT    0011_directives.asm:68.1-68.18
F3 . . . . . . . . . . . . . . . . . REG.   0x00003 NOT USED CONSTANT    0011_directives.asm:69.1-69.18
F4 . . . . . . . . . . . . . . . . . REG.   0x00004 NOT USED CONSTANT    0011_directives.asm:70.1-70.18
F5 . . . . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    0011_directives.asm:71.1-71.18
F6 . . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    0011_directives.asm:72.1-72.18
G1 . . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0011_directives.asm:75.1-75.18
G10  . . . . . . . . . . . . . . . . NUMBER 0x00011 NOT USED CONSTANT    0011_directives.asm:84.1-84.20
G11  . . . . . . . . . . . . . . . . NUMBER 0x0000A NOT USED CONSTANT    0011_directives.asm:85.1-85.19
G12  . . . . . . . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    0011_directives.asm:86.1-86.21
G2 . . . . . . . . . . . . . . . . . NUMBER 0x00002 NOT USED CONSTANT    0011_directives.asm:76.1-76.18
G3 . . . . . . . . . . . . . . . . . NUMBER 0x00003 NOT USED CONSTANT    0011_directives.asm:77.1-77.18
G4 . . . . . . . . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    0011_directives.asm:78.1-78.18
G5 . . . . . . . . . . . . . . . . . NUMBER 0x00005 NOT USED CONSTANT    0011_directives.asm:79.1-79.18
G6 . . . . . . . . . . . . . . . . . NUMBER 0x00006 NOT USED CONSTANT    0011_directives.asm:80.1-80.18
G7 . . . . . . . . . . . . . . . . . NUMBER 0x00007 NOT USED CONSTANT    0011_directives.asm:81.1-81.18
G8 . . . . . . . . . . . . . . . . . NUMBER 0x00008 NOT USED CONSTANT    0011_directives.asm:82.1-82.18
G9 . . . . . . . . . . . . . . . . . NUMBER 0x00009 NOT USED CONSTANT    0011_directives.asm:83.1-83.18
I1 . . . . . . . . . . . . . . . . . PORT   0x00244 NOT USED CONSTANT    0011_directives.asm:89.1-89.21
I10  . . . . . . . . . . . . . . . . PORT   0x00011 NOT USED CONSTANT    0011_directives.asm:98.1-98.21
I11  . . . . . . . . . . . . . . . . PORT   0x000AA NOT USED CONSTANT    0011_directives.asm:99.1-99.21
I12  . . . . . . . . . . . . . . . . PORT   0x00015 NOT USED CONSTANT    0011_directives.asm:100.1-100.29
I2 . . . . . . . . . . . . . . . . . PORT   0x3FFFF NOT USED CONSTANT    0011_directives.asm:90.1-90.26
I3 . . . . . . . . . . . . . . . . . PORT   0x00000 NOT USED CONSTANT    0011_directives.asm:91.1-91.19
I4 . . . . . . . . . . . . . . . . . PORT   0x00019 NOT USED CONSTANT    0011_directives.asm:92.1-92.25
I5 . . . . . . . . . . . . . . . . . PORT   0x00001 NOT USED CONSTANT    0011_directives.asm:93.1-93.24
I6 . . . . . . . . . . . . . . . . . PORT   0x00011 NOT USED CONSTANT    0011_directives.asm:94.1-94.28
I7 . . . . . . . . . . . . . . . . . PORT   0x00001 NOT USED CONSTANT    0011_directives.asm:95.1-95.28
I8 . . . . . . . . . . . . . . . . . PORT   0x00003 NOT USED CONSTANT    0011_directives.asm:96.1-96.19
I9 . . . . . . . . . . . . . . . . . PORT   0x00001 NOT USED CONSTANT    0011_directives.asm:97.1-97.20
S0 . . . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 USED     CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 NOT USED CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 NOT USED CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 NOT USED CONSTANT    IMPLICIT
SS1  . . . . . . . . . . . . . . . . NUMBER 0x00005 NOT USED CONSTANT    0011_directives.asm:103.1-103.19
SS10 . . . . . . . . . . . . . . . . NUMBER 0x0002B NOT USED CONSTANT    0011_directives.asm:112.1-112.33
SS11 . . . . . . . . . . . . . . . . NUMBER 0x3FFE7 NOT USED CONSTANT    0011_directives.asm:113.1-113.24
SS12 . . . . . . . . . . . . . . . . NUMBER 0x00002 NOT USED CONSTANT    0011_directives.asm:114.1-114.26
SS13 . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0011_directives.asm:115.1-115.26
SS14 . . . . . . . . . . . . . . . . NUMBER 0x000F0 NOT USED CONSTANT    0011_directives.asm:116.1-116.28
SS2  . . . . . . . . . . . . . . . . NUMBER 0x3FFFB NOT USED CONSTANT    0011_directives.asm:104.1-104.19
SS3  . . . . . . . . . . . . . . . . NUMBER 0x00005 NOT USED CONSTANT    0011_directives.asm:105.1-105.20
SS4  . . . . . . . . . . . . . . . . NUMBER 0x3FFFB NOT USED CONSTANT    0011_directives.asm:106.1-106.21
SS5  . . . . . . . . . . . . . . . . NUMBER 0x00000 NOT USED CONSTANT    0011_directives.asm:107.1-107.22
SS6  . . . . . . . . . . . . . . . . NUMBER 0x3FFEB NOT USED CONSTANT    0011_directives.asm:108.1-108.29
SS7  . . . . . . . . . . . . . . . . NUMBER 0x3FF00 NOT USED CONSTANT    0011_directives.asm:109.1-109.22
SS8  . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0011_directives.asm:110.1-110.56
SS9  . . . . . . . . . . . . . . . . NUMBER 0x0002F NOT USED CONSTANT    0011_directives.asm:111.1-111.38
START  . . . . . . . . . . . . . . . LABEL  0x00000 NOT USED CONSTANT    0011_directives.asm:129.1-129.7
TAM  . . . . . . . . . . . . . . . . REG.   0x00004 NOT USED CONSTANT    0011_directives.asm:61.1-61.22
TE . . . . . . . . . . . . . . . . . REG.   0x00002 NOT USED CONSTANT    0011_directives.asm:59.1-59.21
VY . . . . . . . . . . . . . . . . . REG.   0x00003 NOT USED CONSTANT    0011_directives.asm:60.1-60.21
XXX  . . . . . . . . . . . . . . . . EXPR.          USED     CONSTANT    0011_directives.asm:121.1-121.44
YYY  . . . . . . . . . . . . . . . . EXPR.          USED     CONSTANT    0011_directives.asm:122.1-122.32
ZDRA . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    0011_directives.asm:63.1-63.23
