                   1     ; load case for directives
                   2     device kcpsm1cpld
                   3
                   4
                   5
  00244            6     a1      EQU     580
  3FFFF            7     a2      EQU     0xFFFFFF
W: value out of range: 0xffffff, allowed range is [0x0,0x3ffff] (trimmed to 18 bits) which makes it 0x3ffff.
  00000            8     a3      EQU     0
  00019            9     a4      EQU     0b11001
  00001           10     a5      EQU     0b0001
  00011           11     a6      EQU     0b00010001
  00001           12     a7      EQU     0b00000001
  00003           13     a8      EQU     3
  00001           14     a9      EQU     1h
  00011           15     a10     EQU     11h
  000AA           16     a11     EQU     AAh
  00004           17     a12     EQU     0x04
                  18
  00244           19     b1      SET     580
  3FFFF           20     b2      SET     0xFFFFFF
W: value out of range: 0xffffff, allowed range is [0x0,0x3ffff] (trimmed to 18 bits) which makes it 0x3ffff.
  00000           21     b3      SET     0
  00019           22     b4      SET     0b11001
  00001           23     b5      SET     0b0001
  00011           24     b6      SET     0b00010001
  00001           25     b7      SET     0b00000001
  00003           26     b8      SET     3
  00001           27     b9      SET     1h
  00011           28     b10     SET     11h
  000AA           29     b11     SET     AAh
  00004           30     b12     SET     0x04
                  31
  00222           32     CONSTANT        c1,546
  0FFFF           33     CONSTANT        c2,0xffff
  0000C           34     CONSTANT        c3,12
  00000           35     CONSTANT        c4,0
  00000           36     CONSTANT        c5,0b00000000
  00001           37     CONSTANT        c6,0b001
  00001           38     CONSTANT        c7,0b01
  00015           39     CONSTANT        c8,0b00010101
  0001E           40     CONSTANT        c9,0b11110
  00001           41     CONSTANT        c10,1h
  000FE           42     CONSTANT        c11,FEh
  00003           43     CONSTANT        c12,0x03
                  44
  00222           45     VARIABLE        d1,546
  0FFFF           46     VARIABLE        d2,0xffff
  0000C           47     VARIABLE        d3,12
  00000           48     VARIABLE        d4,0
  00000           49     VARIABLE        d5,0b00000000
  00001           50     VARIABLE        d6,0b001
  00001           51     VARIABLE        d7,0b01
  00015           52     VARIABLE        d8,0b00010101
  0001E           53     VARIABLE        d9,0b11110
  00001           54     VARIABLE        d10,1h
  000FE           55     VARIABLE        d11,FEh
  00003           56     VARIABLE        d12,0x03
                  57
  00001           58     NAMEREG         1,AHOJ
  00002           59     NAMEREG         2,TE
  00003           60     NAMEREG         3,VY
  00004           61     NAMEREG         4,TAM
  00005           62     NAMEREG         5,DOLE
                  63
                  64
                  65
  00001           66     f1      REG     1
W: reusing already reserved space in register file memory at address: 0x1.
  00002           67     f2      REG     2
W: reusing already reserved space in register file memory at address: 0x2.
  00003           68     f3      REG     3
W: reusing already reserved space in register file memory at address: 0x3.
  00004           69     f4      REG     4
W: reusing already reserved space in register file memory at address: 0x4.
                  70
                  71
  00001           72     g1      EQU     1
  00002           73     g2      EQU     2
  00003           74     g3      EQU     3
  00004           75     g4      EQU     4
  00005           76     g5      EQU     5
  00006           77     g6      EQU     6
  00007           78     g7      EQU     7
  00008           79     g8      EQU     8
  00009           80     g9      EQU     9
  00011           81     g10     EQU     11h
  0000A           82     g11     EQU     Ah
  00004           83     g12     EQU     0x04
                  84
                  85
                  86
  00244           87     i1      PORT     580
  3FFFF           88     i2      PORT     0xFFFFFF
W: value out of range: 0xffffff, allowed range is [0x0,0x3ffff] (trimmed to 18 bits) which makes it 0x3ffff.
  00000           89     i3      PORT     0
  00019           90     i4      PORT     0b11001
  00001           91     i5      PORT     0b0001
  00011           92     i6      PORT     0b00010001
  00001           93     i7      PORT     0b00000001
  00003           94     i8      PORT     3
  00001           95     i9      PORT     1h
  00011           96     i10     PORT     11h
  000AA           97     i11     PORT     AAh
  00004           98     i12     PORT     0x04
                  99
                 100     m1      DEFINE   h8 + i3
                 101     m2      DEFINE   i8 + a11
                 102     m3      DEFINE   A3 * A4 * A5 * A6 * A7 + A8 - A9
                 103     M4      DEFINE   (b5 - B6)--B10
                 104
                 105     ;--- CODE ------------- CODE -----------------CODE -----------------
  003FF          106             ORG     0x3FF
  00000          107             ORG     0x000
000 0D001        108             JUMP    Start
                 109
                 110
  00001          111     Start:
                 112             REPT    B6
                 113             SUB     s0,s2                  ; kkkkkkk
                 114             ADD     s1,s2
                 115             ENDR
001 07040        116 +1          SUB     s0,s2                  ; kkkkkkk
002 06140        117 +1          ADD     s1,s2
003 07040        118 +1          SUB     s0,s2                  ; kkkkkkk
004 06140        119 +1          ADD     s1,s2
005 07040        120 +1          SUB     s0,s2                  ; kkkkkkk
006 06140        121 +1          ADD     s1,s2
007 07040        122 +1          SUB     s0,s2                  ; kkkkkkk
008 06140        123 +1          ADD     s1,s2
009 07040        124 +1          SUB     s0,s2                  ; kkkkkkk
00A 06140        125 +1          ADD     s1,s2
00B 07040        126 +1          SUB     s0,s2                  ; kkkkkkk
00C 06140        127 +1          ADD     s1,s2
00D 07040        128 +1          SUB     s0,s2                  ; kkkkkkk
00E 06140        129 +1          ADD     s1,s2
00F 07040        130 +1          SUB     s0,s2                  ; kkkkkkk
010 06140        131 +1          ADD     s1,s2
011 07040        132 +1          SUB     s0,s2                  ; kkkkkkk
012 06140        133 +1          ADD     s1,s2
013 07040        134 +1          SUB     s0,s2                  ; kkkkkkk
014 06140        135 +1          ADD     s1,s2
015 07040        136 +1          SUB     s0,s2                  ; kkkkkkk
016 06140        137 +1          ADD     s1,s2
017 07040        138 +1          SUB     s0,s2                  ; kkkkkkk
018 06140        139 +1          ADD     s1,s2
019 07040        140 +1          SUB     s0,s2                  ; kkkkkkk
01A 06140        141 +1          ADD     s1,s2
01B 07040        142 +1          SUB     s0,s2                  ; kkkkkkk
01C 06140        143 +1          ADD     s1,s2
01D 07040        144 +1          SUB     s0,s2                  ; kkkkkkk
01E 06140        145 +1          ADD     s1,s2
01F 07040        146 +1          SUB     s0,s2                  ; kkkkkkk
020 06140        147 +1          ADD     s1,s2
021 07040        148 +1          SUB     s0,s2                  ; kkkkkkk
022 06140        149 +1          ADD     s1,s2
                 150             ;-----------
                 151             REPT    C10
                 152             SUB     s0,s2                  ; kkkkkkk
                 153             ADD     s1,s2
                 154             INPUT   S0,i1
W: value out of range: 0x244, allowed range is [0x0,0xff] (trimmed to 8 bits) which makes it 0x44.
                 155             ENDR
023 07040        156 +1          SUB     s0,s2                  ; kkkkkkk
024 06140        157 +1          ADD     s1,s2
025 08044        158 +1          INPUT   S0,i1
W: ==> value out of range: 0x244, allowed range is [0x0,0xff] (trimmed to 8 bits) which makes it 0x44.
                 159             ;-------------
                 160
                 161
                 162
