MT_WARNING: 0016_Source_code_ukol_1.asm:41.28-41.33: Warning: instruction `LOAD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:42.28-42.33: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:50.31-50.36: Warning: instruction `LOAD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:52.31-52.36: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:66.31-66.36: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:67.31-67.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:67.38-67.39: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:69.31-69.36: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:76.31-76.36: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:77.31-77.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:77.38-77.39: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:79.31-79.36: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:88.31-88.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:88.38-88.43: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:89.31-89.36: Warning: instruction `SR0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:90.31-90.36: Warning: instruction `SR0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:91.31-91.36: Warning: instruction `SR0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:92.31-92.36: Warning: instruction `SR0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:93.31-93.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:93.38-93.40: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:95.31-95.36: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:97.31-97.36: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:100.31-100.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:100.38-100.43: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:101.31-101.36: Warning: instruction `AND sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:102.31-102.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:102.38-102.40: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:104.31-104.36: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:106.31-106.36: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:115.31-115.36: Warning: instruction `LOAD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:117.31-117.36: Warning: instruction `LOAD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:135.31-135.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:135.38-135.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:136.31-136.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:136.38-136.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:137.31-137.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:137.38-137.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:138.31-138.36: Warning: instruction `SUB sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:138.38-138.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:140.31-140.36: Warning: instruction `SUB sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:140.38-140.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:142.31-142.36: Warning: instruction `SUB sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:142.38-142.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:146.31-146.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:146.38-146.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:147.31-147.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:147.38-147.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:148.31-148.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:148.38-148.40: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:149.31-149.36: Warning: instruction `SUB sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:149.38-149.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:151.31-151.36: Warning: instruction `SUB sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:151.38-151.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:153.31-153.36: Warning: instruction `SUB sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:153.38-153.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 0016_Source_code_ukol_1.asm:77.38-77.39: Warning: value out of range: 0x8, allowed range is [0x0,0x7] (trimmed to 3 bits) which makes it 0x0.
MT_WARNING: 0016_Source_code_ukol_1.asm:93.38-93.40: Warning: value out of range: 0xa, allowed range is [0x0,0x7] (trimmed to 3 bits) which makes it 0x2.
MT_WARNING: 0016_Source_code_ukol_1.asm:102.38-102.40: Warning: value out of range: 0xa, allowed range is [0x0,0x7] (trimmed to 3 bits) which makes it 0x2.
MT_WARNING: 0016_Source_code_ukol_1.asm:135.38-135.41: Warning: value out of range: 0xfa, allowed range is [0x0,0x7] (trimmed to 3 bits) which makes it 0x2.
MT_WARNING: 0016_Source_code_ukol_1.asm:136.38-136.41: Warning: value out of range: 0xf9, allowed range is [0x0,0x7] (trimmed to 3 bits) which makes it 0x1.
MT_WARNING: 0016_Source_code_ukol_1.asm:137.38-137.41: Warning: value out of range: 0xc8, allowed range is [0x0,0x7] (trimmed to 3 bits) which makes it 0x0.
MT_WARNING: 0016_Source_code_ukol_1.asm:146.38-146.41: Warning: value out of range: 0xfa, allowed range is [0x0,0x7] (trimmed to 3 bits) which makes it 0x2.
MT_WARNING: 0016_Source_code_ukol_1.asm:147.38-147.41: Warning: value out of range: 0xf9, allowed range is [0x0,0x7] (trimmed to 3 bits) which makes it 0x1.
MT_WARNING: 0016_Source_code_ukol_1.asm:148.38-148.40: Warning: value out of range: 0x14, allowed range is [0x0,0x7] (trimmed to 3 bits) which makes it 0x4.
