COUNTER  . . . . . . . . . . . . . . NUMBER 0x0000F NOT USED REDEFINABLE 0018_demo_1.asm:9.1-9.30
INC_DEC  . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    0018_demo_1.asm:11.1-11.33
MAIN . . . . . . . . . . . . . . . . LABEL  0x00004 USED     CONSTANT    0018_demo_1.asm:41.1-41.6
RAM_POINTER  . . . . . . . . . . . . NUMBER 0x00000 NOT USED REDEFINABLE 0018_demo_1.asm:12.1-12.29
S0 . . . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 NOT USED CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 NOT USED CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 NOT USED CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 NOT USED CONSTANT    IMPLICIT
START  . . . . . . . . . . . . . . . LABEL  0x00001 USED     CONSTANT    0018_demo_1.asm:34.1-34.7
X  . . . . . . . . . . . . . . . . . NUMBER 0x00064 USED     REDEFINABLE 0018_demo_1.asm:10.1-10.29
