LED_ID . . . . . . . . . . . . . . . PORT   0x00008 NOT USED CONSTANT    0022_load.asm:28.9-28.37
RX_ID  . . . . . . . . . . . . . . . PORT   0x00002 NOT USED CONSTANT    0022_load.asm:26.9-26.37
S0 . . . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 USED     CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 NOT USED CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 NOT USED CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 NOT USED CONSTANT    IMPLICIT
TEMP1  . . . . . . . . . . . . . . . REG.   0x00000 NOT USED CONSTANT    0022_load.asm:19.9-19.33
TEMP2  . . . . . . . . . . . . . . . REG.   0x00001 NOT USED CONSTANT    0022_load.asm:20.9-20.33
TEMP3  . . . . . . . . . . . . . . . REG.   0x00002 NOT USED CONSTANT    0022_load.asm:21.9-21.33
TX_ID  . . . . . . . . . . . . . . . PORT   0x00001 NOT USED CONSTANT    0022_load.asm:25.9-25.37
UART_STAT  . . . . . . . . . . . . . PORT   0x00004 NOT USED CONSTANT    0022_load.asm:27.9-27.37
