S0 . . . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 USED     CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 NOT USED CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 NOT USED CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 NOT USED CONSTANT    IMPLICIT
START  . . . . . . . . . . . . . . . LABEL  0x00001 USED     CONSTANT    0024_demo_2_wait_loop.asm:19.1-19.7
TEMP1  . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    0024_demo_2_wait_loop.asm:14.1-14.27
TEMP2  . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    0024_demo_2_wait_loop.asm:15.1-15.27
TEMP3  . . . . . . . . . . . . . . . REG.   0x00002 USED     CONSTANT    0024_demo_2_wait_loop.asm:16.1-16.27
WAIT_100MS . . . . . . . . . . . . . LABEL  0x0000E USED     CONSTANT    0024_demo_2_wait_loop.asm:40.1-40.12
WAIT_100MS_I . . . . . . . . . . . . LABEL  0x00011 USED     CONSTANT    0024_demo_2_wait_loop.asm:43.1-43.14
WAIT_1S  . . . . . . . . . . . . . . LABEL  0x00004 USED     CONSTANT    0024_demo_2_wait_loop.asm:29.1-29.9
WAIT_1S_I  . . . . . . . . . . . . . LABEL  0x00007 USED     CONSTANT    0024_demo_2_wait_loop.asm:32.1-32.11
