                   1     DEVICE KCPSM3
                   2
  00005            3     BSDA_Z  EQU     5
  00005            4     BSCL_Z  EQU     5
  00005            5     BSDA_0  EQU     5
  00005            6     BSCL_0  EQU     5
  00005            7     BSDA_IN EQU     5
                   8     ; ---\              /--------\                                            /--
                   9     ;     \  SDA       /          \                                          /
                  10     ;      \----------/ \--------/ \----------------------------------------/
                  11     ; -------\            /----\                                         /-------
                  12     ;         \  SCL     /      \                                       /
                  13     ;          \--------/        \-------------------------------------/
                  14     ; | Start    |      Data bit     |                             |  Stop     |
                  15
000 2CF05         16     Init_I2C:       OUTPUT     sF, bSDA_Z              ; SDA = Z
001 2CF05         17                     OUTPUT     sF, bSCL_Z              ; SCL = Z
002 34003         18                     JUMP    Delay
                  19
                  20     DElay:
                  21     ; -------------------------------------------------------------------------------
                  22     ; Routine to set up for and read four bytes from I2C device
                  23     ; -------------------------------------------------------------------------------
                  24
                  25     ReadWrite4_I2C:
003 3009A         26                     CALL    I2C_Start               ; Send Start, control byte and ack
004 05C00         27                     INPUT    sC, @s0                  ; Load device code for TX
005 20C06         28                     SL0     sC                      ; add write flag
006 30057         29                     CALL    I2C_Xmit                ; Send address and ack
007 3008E         30                     CALL    I2C_SAck
                  31
008 05C10         32                     INPUT    sC, @s1                  ; Load data for TX
009 30057         33                     CALL    I2C_Xmit                ; Send data and ack
00A 3008E         34                     CALL    I2C_SAck
                  35
00B 30098         36                     CALL    I2C_RepStart            ; Send repeated start, control byte and ack
00C 05C00         37                     INPUT    sC, @s0                  ; Load device code for TX
00D 20C07         38                     SL1     sC                      ; add read flag
00E 30057         39                     CALL    I2C_Xmit                ; Send address and ack
00F 3008E         40                     CALL    I2C_SAck
                  41
010 30068         42                     CALL    I2C_Recv                ; Read 8 bits of data and send ack
011 30078         43                     CALL    I2C_MAck
012 052C0         44                     INPUT    s2, @sC
                  45
013 30068         46                     CALL    I2C_Recv                ; Read next 8 bits of data and send ack
014 30078         47                     CALL    I2C_MAck
015 053C0         48                     INPUT    s3, @sC
                  49
016 30068         50                     CALL    I2C_Recv                ; Read 8 bits of data and send ack
017 30078         51                     CALL    I2C_MAck
018 054C0         52                     INPUT    s4, @sC
                  53
019 30068         54                     CALL    I2C_Recv                ; Read next 8 bits of data and send ack
01A 30083         55                     CALL    I2C_MNAck
01B 055C0         56                     INPUT    s5, @sC
                  57
01C 340A0         58                     JUMP    I2C_Stop                ; Send Stop
                  59
                  60     ; -------------------------------------------------------------------------------
                  61     ; Routine to set up for and write two bytes to I2C device
                  62     ; -------------------------------------------------------------------------------
                  63     Write3_I2C:
01D 3009A         64                     CALL    I2C_Start               ; Send Start, control byte and ack
01E 05C00         65                     INPUT    sC, @s0                  ; Load device code for TX
01F 20C06         66                     SL0     sC                      ; add write flag
020 30057         67                     CALL    I2C_Xmit                ; Send address and ack
021 3008E         68                     CALL    I2C_SAck
                  69
022 05C10         70                     INPUT    sC, @s1                  ; Load data for TX
023 30057         71                     CALL    I2C_Xmit                ; Send data and ack
024 3008E         72                     CALL    I2C_SAck
                  73
025 05C20         74                     INPUT    sC, @s2                  ; Load data for TX
026 30057         75                     CALL    I2C_Xmit                ; Send data and ack
027 3008E         76                     CALL    I2C_SAck
                  77
028 05C30         78                     INPUT    sC, @s3                  ; Load data for TX
029 30057         79                     CALL    I2C_Xmit                ; Send data and ack
02A 3008E         80                     CALL    I2C_SAck
                  81
02B 340A0         82                     JUMP    I2C_Stop                ; Send stop
                  83
                  84     ; -------------------------------------------------------------------------------
                  85     ; Routine to set up for and read two bytes from I2C device
                  86     ; -------------------------------------------------------------------------------
                  87
                  88     Read2_I2C:
02C 3009A         89                     CALL    I2C_Start               ; Send start, control byte and ack
02D 05C00         90                     INPUT    sC, @s0                  ; Load device code for TX
02E 20C07         91                     SL1     sC                      ; add read flag
02F 30057         92                     CALL    I2C_Xmit                ; Send address and ack
030 3008E         93                     CALL    I2C_SAck
                  94
031 30068         95                     CALL    I2C_Recv                ; Read 8 bits of data and send ack
032 30078         96                     CALL    I2C_MAck
033 052C0         97                     INPUT    s2, @sC
                  98
034 30068         99                     CALL    I2C_Recv                ; Read next 8 bits of data and send ack
035 30083        100                     CALL    I2C_MNAck
036 053C0        101                     INPUT    s3, @sC
                 102
037 340A0        103                     JUMP    I2C_Stop                ; Send Stop
                 104
                 105     ; -------------------------------------------------------------------------------
                 106     ; Routine to set up for and write two bytes to I2C device
                 107     ; -------------------------------------------------------------------------------
                 108     Write2_I2C:
038 3009A        109                     CALL    I2C_Start               ; Send Start, control byte and ack
039 05C00        110                     INPUT    sC, @s0                  ; Load device code for TX
03A 20C06        111                     SL0     sC                      ; add write flag
03B 30057        112                     CALL    I2C_Xmit                ; Send address and ack
03C 3008E        113                     CALL    I2C_SAck
                 114
03D 05C10        115                     INPUT    sC, @s1                  ; Load data for TX
03E 30057        116                     CALL    I2C_Xmit                ; Send data and ack
03F 3008E        117                     CALL    I2C_SAck
                 118
040 05C20        119                     INPUT    sC, @s2                  ; Load data for TX
041 30057        120                     CALL    I2C_Xmit                ; Send data and ack
042 3008E        121                     CALL    I2C_SAck
                 122
043 340A0        123                     JUMP    I2C_Stop                ; Send stop
                 124
                 125     ; -------------------------------------------------------------------------------
                 126     ; Routine to set up for and read one byte of I2C device
                 127     ; -------------------------------------------------------------------------------
                 128     Read1_I2C:
                 129
044 3009A        130                     CALL    I2C_Start               ; Send start, control byte and ack
045 05C00        131                     INPUT    sC, @s0                  ; Load address for TX
046 20C07        132                     SL1     sC                      ; add read flag
047 30057        133                     CALL    I2C_Xmit                ; Send address and ack
048 3008E        134                     CALL    I2C_SAck
                 135
049 3009A        136                     CALL    I2C_Start               ; Send start, control byte and ack
                 137
04A 30068        138                     CALL    I2C_Recv                ; Read 8 bits of data and send ack
04B 30083        139                     CALL    I2C_MNAck
04C 052C0        140                     INPUT    s2, @sC
                 141
04D 340A0        142                     JUMP    I2C_Stop                ; Send Stop
                 143
                 144     ; -------------------------------------------------------------------------------
                 145     ; Routine to set up for and write one byte to I2C device
                 146     ; -------------------------------------------------------------------------------
                 147     Write1_I2C:
                 148
04E 3009A        149                     CALL    I2C_Start               ; Send Start, control byte and ack
04F 05C00        150                     INPUT    sC, @s0                  ; Load device code for TX
050 20C06        151                     SL0     sC                      ; add write flag
051 30057        152                     CALL    I2C_Xmit                ; Send address and ack
052 3008E        153                     CALL    I2C_SAck
                 154
053 05C10        155                     INPUT    sC, @s1                  ; Load data for TX
054 30057        156                     CALL    I2C_Xmit                ; Send data and ack
055 3008E        157                     CALL    I2C_SAck
                 158
056 340A0        159                     JUMP    I2C_Stop                ; Send stop
                 160
                 161     ; -------------------------------------------------------------------------------
                 162     ; Transmit 8 bits of I2C data
                 163     ; -------------------------------------------------------------------------------
                 164     I2C_Xmit:
057 04D08        165                     INPUT    sD, 8                   ; Load I2C bit counter
                 166     I2C_TX:
058 30003        167                     CALL    Delay
059 20C06        168                     SL0     sC                      ; Move data bit -> carry
05A 3585E        169                     JUMP    C, I2C_TX1              ; Jump if bit high
                 170     I2C_TX0:
05B 2CF05        171                     OUTPUT     sF, bSDA_0              ; SDA = 0
05C 30003        172                     CALL    Delay
05D 34060        173                     JUMP    I2C_TX2                 ; Jump over next instructions
                 174     I2C_TX1:
05E 2CF05        175                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
05F 30003        176                     CALL    Delay
                 177     I2C_TX2:
                 178
060 2CF05        179                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
061 30003        180                     CALL    Delay
062 30003        181                     CALL    Delay
063 30003        182                     CALL    Delay
064 2CF05        183                     OUTPUT     sF, bSCL_0              ; SCL = 0
                 184
065 1DD10        185                     SUB     sD, 1                   ; Decrement I2C bit counter
066 35458        186                     JUMP    NZ, I2C_TX              ; Loop until 8 bits are sent
067 34003        187                     JUMP    Delay
                 188
                 189     ; -------------------------------------------------------------------------------
                 190     ; Read 8 bits of I2C data
                 191     ; -------------------------------------------------------------------------------
                 192     I2C_Recv:
068 04D08        193                     INPUT    sD, 8                   ; Load I2C bit counter
069 30003        194                     CALL    Delay
06A 2CF05        195                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
                 196
                 197     I2C_RX:
06B 30003        198                     CALL    Delay
06C 2CF05        199                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
06D 30003        200                     CALL    Delay
06E 30003        201                     CALL    Delay
06F 04F05        202                     IN      sF, bSDA_In
070 30003        203                     CALL    Delay
071 20F0E        204                     SR0     sF                      ; LSBit -> carry bit
072 20C00        205                     SLA     sC                      ; Carry shifted into LSBit
073 2CF05        206                     OUTPUT     sF, bSCL_0              ; SCL = 0
074 30003        207                     CALL    Delay
075 1DD10        208                     SUB     sD, 1                   ; Decrement I2C bit counter
076 3546B        209                     JUMP    NZ, I2C_RX              ; Loop until 8 bits are read
077 2A000        210                     RETURN
                 211
                 212     ; -------------------------------------------------------------------------------
                 213     ; Ack by master, keep data 0
                 214     ; -------------------------------------------------------------------------------
                 215     I2C_MAck:
078 30003        216                     CALL    Delay
079 2CF05        217                     OUTPUT     sF, bSDA_0              ; SDA = 0
07A 30003        218                     CALL    Delay
07B 2CF05        219                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
07C 30003        220                     CALL    Delay
07D 30003        221                     CALL    Delay
07E 30003        222                     CALL    Delay
07F 2CF05        223                     OUTPUT     sF, bSCL_0              ; SCL = 0
080 30003        224                     CALL    Delay
081 2CF05        225                     OUTPUT     sF, bSDA_0              ; SDA = 0
082 2A000        226                     RETURN
                 227
                 228     ; -------------------------------------------------------------------------------
                 229     ; NAck by master, release data
                 230     ; -------------------------------------------------------------------------------
                 231     I2C_MNAck:
083 30003        232                     CALL    Delay
084 2CF05        233                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
085 30003        234                     CALL    Delay
086 2CF05        235                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
087 30003        236                     CALL    Delay
088 30003        237                     CALL    Delay
089 30003        238                     CALL    Delay
08A 2CF05        239                     OUTPUT     sF, bSCL_0              ; SCL = 0
08B 30003        240                     CALL    Delay
08C 2CF05        241                     OUTPUT     sF, bSDA_0              ; SDA = 0
08D 2A000        242                     RETURN
                 243
                 244     ; -------------------------------------------------------------------------------
                 245     ; Ack by slave, release data
                 246     ; -------------------------------------------------------------------------------
                 247     I2C_SAck:
08E 30003        248                     CALL    Delay
08F 2CF05        249                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
090 30003        250                     CALL    Delay
091 2CF05        251                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
092 30003        252                     CALL    Delay
093 30003        253                     CALL    Delay
094 30003        254                     CALL    Delay
095 2CF05        255                     OUTPUT     sF, bSCL_0              ; SCL = 0
096 30003        256                     CALL    Delay
097 2A000        257                     RETURN
                 258
                 259     ; -------------------------------------------------------------------------------
                 260     ; Set up start condition for I2C
                 261     ; -------------------------------------------------------------------------------
                 262
                 263     ; SCL and SDA set to inputs, signals go high due to pull-up resistors
                 264
                 265     I2C_RepStart:
098 30003        266                     CALL    Delay
099 2CF05        267                     OUTPUT     sF, bSCL_Z              ; SCL = Z
                 268     I2C_Start:
09A 30003        269                     CALL    Delay
09B 2CF05        270                     OUTPUT     sF, bSDA_0              ; SDA = 0
09C 30003        271                     CALL    Delay
09D 2CF05        272                     OUTPUT     sF, bSCL_0              ; SCL = 0
09E 30003        273                     CALL    Delay
09F 2A000        274                     RETURN
                 275
                 276     ; -------------------------------------------------------------------------------
                 277     ; Send I2C stop command
                 278     ; -------------------------------------------------------------------------------
                 279     I2C_Stop:
0A0 30003        280                     CALL    Delay
0A1 2CF05        281                     OUTPUT     sF, bSCL_Z              ; SCL = 1 due to pull-up
0A2 30003        282                     CALL    Delay
0A3 2CF05        283                     OUTPUT     sF, bSDA_Z              ; SDA = 1 due to pull-up
0A4 30003        284                     CALL    Delay
0A5 2A000        285                     RETURN
                 286
                 287     ; -----------I2C Subroutines end-------------------------------------------------
                 288
