                   1     
                   2     ;
                   3     ; PicoBlaze kód pro počáteční inicializaci A/D převodníku ADS6445 a zdroje hodin LMK4011
                   4     
                   5     ; A/D převodník - 16bit registry
                   6     ;				  Max 20 MHz
                   7     ;				  A4-A0 + D10-D0	
                   8     ;
                   9     ; LMK4011 -		  32bit registry
                  10     ; 				  Max 20 MHz
                  11     ;				  D27-D0 + A3-A0
                  12     ;
                  13     ; Martin Madron 30.4.2013
                  14     ;
                  15     ;
                  16     device          KCPSM3
                  17     ; Start
                  18     ;##############################################################################;
                  19     ; Přiřazení jmen registrům
  00000           20     	NAMEREG		s0,temp1              ; temporary data register
  00001           21     	NAMEREG		s1,temp2              ; temporary data register
  00002           22     	NAMEREG		s2,temp3              ; temporary data register
  00003           23     	NAMEREG		s3,RXdata             ; temporary data register
  00004           24     	NAMEREG		s4,TXdata             ; temporary data register
                  25     
                  26     ; PORT_IDs
  00001           27     	CONSTANT	TX_data_01, 01          ;  data register port ID
  00002           28     	CONSTANT	TX_data_02, 02          ;  data register port ID
  00004           29     	CONSTANT	TX_data_03, 04          ;  data register port ID
  00008           30     	CONSTANT	TX_data_04, 08          ;  data register port ID
  0000C           31     	CONSTANT	Read_data, 12           ;  data register port ID
                  32     
  00004           33     CHREG                   equ             4
  00004           34     SWITCH                   equ             4
  00004           35     UART_STAT                   equ             4
  00004           36     UART_DATA                   equ             4
                  37     
                  38     	
                  39     ; Inicializace
                  40     ;##############################################################################;
  00000           41     	ADDRESS	000
000 34001         42     	JUMP	Start
                  43     ; Čekání 1s pro inicializaci obvodů
001 3002B         44     Start:              CALL      wait_1s             ; wait for 1s
                  45     ; end of initialization
                  46     
                  47     ;  Main 
002 3000D         48     main_loop:          CALL      GetChar             ; get (wait for) new character
003 14414         49                         COMPARE      chreg,#20           ; Space character received?
004 35402         50                         JUMP      NZ,main_loop        ; If not space, get another character
005 04404         51                         IN        chreg,Switch        ; If yes, read content of switches
006 30008         52                         CALL      SendChar            ; And send it via UART
007 34002         53                         JUMP      main_loop
                  54     
                  55     ;##############################################################################;
                  56     ;  General purpose procedures
                  57     ;##############################################################################;
                  58     
                  59     ; Basic UART text output procedures (CALLs)
                  60     
                  61     ;==============================================================================;
                  62     ; Send character stored in chreg via UART
                  63     ; Registers used: Temp1, chreg
                  64     ;==============================================================================;
008 04004         65     SendChar:           IN        Temp1, UART_stat    ; checking UART status
009 13040         66                         TEST      Temp1, 4            ; test bit 2 (is Tx ready?)
00A 35008         67                         JUMP      Z, SendChar         ; wait until Tx is ready
00B 2C404         68                         OUT       chreg, UART_data    ; Send the character
00C 2A000         69                         RET                           ; Return from procedure
                  70     
                  71     ;==============================================================================;
                  72     ; Reads a single character from UART (waits on receive when none is prepared)
                  73     ; Registers used: Temp1, chreg
                  74     ;==============================================================================;
00D 04004         75     GetChar:            IN        Temp1, UART_stat    ; checking UART status
00E 13080         76                         TEST      Temp1, 8            ; test bit 3 (new Rx data?)
00F 3500D         77                         JUMP      Z, GetChar          ; wait for new Rx data
010 04404         78                         IN        chreg, UART_data    ; Read the character
011 2A000         79                         RET                           ; Return from procedure
                  80     
                  81     ;==============================================================================;
                  82     ; Procedure for sending content of "chreg" register in hexadecimal ASCII format
                  83     ;   (two characters, one for each nibble)
                  84     ; Reister used: Temp1, Temp2, chreg
                  85     ; Procedures used: SendChar
                  86     ;==============================================================================;
012 01140         87     SendByte:           LOAD      Temp2, chreg        ; make a backup of chreg
013 2040E         88                         SR0       chreg               ; move upper nibble to lower nibble
014 2040E         89                         SR0       chreg
015 2040E         90                         SR0       chreg
016 2040E         91                         SR0       chreg
017 154A0         92                         CMP      chreg, 10           ; if not greater than 9, than it is a number
018 3581B         93                         JUMP      C, SendBNum1        ; C is set when Temp < 10 (Temp-10)
019 18425         94                         ADD       chreg, #37          ; when letter, add #37; letter conversion
01A 3401C         95                         JUMP      SendB1
01B 1841E         96     SendBNum1:          ADD       chreg, #30          ; when number, add #30; number conversion
01C 30008         97     SendB1:             CALL      SendChar            ; Send Character
                  98     
01D 01410         99                         LOAD      chreg, Temp2        ; load the whole byte again
01E 0A40F        100                         AND       chreg, #0Fh          ; select second character
01F 154A0        101                         CMP      chreg, 10           ; if not greater than 9, than number
020 35823        102                         JUMP      C, SendBNum2        ; C is set when Temp < 10 (Temp-10 under 0)
021 18425        103                         ADD       chreg, #37          ; when letter, add #37; letter conversion
022 34024        104                         JUMP      SendB2
023 1841E        105     SendBNum2:          ADD       chreg, #30          ; when number, add #30; number conversion
024 30008        106     SendB2:             CALL      SendChar            ; Send character
025 2A000        107                         RET
                 108     
                 109     ;==============================================================================;
                 110     ; Send 0D and 0A character pair via UART
                 111     ; Registers used: Temp1, chreg
                 112     ; Procedures used: SendChar
                 113     ;==============================================================================;
026 00400        114     SendCRLF:           LOAD      chreg, #0D          ; CR character
027 30008        115                         CALL      SendChar            ; Send character
028 0040A        116                         LOAD      chreg, #0Ah          ; Load LF character
029 30008        117                         CALL      SendChar            ; Send character
02A 2A000        118                         RET                           ; Return from procedure
                 119     
                 120     ;==============================================================================;
                 121     ; Procedures for waiting for specified time
                 122     ; Duration is set in registers Temp1, Temp2 and Temp3
                 123     ;
                 124     ;   clock           instruction execution time
                 125     ;   10.00 MHz              200.00 ns
                 126     ;   19.44 MHz              102.88 ns
                 127     ;   38.88 MHz               51.44 ns
                 128     ;   50.00 MHz               40.00 ns
                 129     ;  100.00 MHz               20.00 ns
                 130     ;
                 131     ; wait_time = (4 + (((2 * Temp1) + 2) * Temp2 + 2) * Temp3) * 2 * clk_period
                 132     ;   1s @ (10 MHz, Temp1 = 250, Temp2 = 249, Temp3 = 40)
                 133     ;
                 134     ; ČEKACÍ SMYČKY
                 135     ;==============================================================================;
02B 010A0        136     wait_1s:            LOAD      Temp1, 250          ; Load Temp1 register
W: value out of range: 250, allowed range is [0,15] (trimmed to 4 bits) which makes it 10
02C 01190        137                         LOAD      Temp2, 249          ; Load Temp2 register
W: value out of range: 249, allowed range is [0,15] (trimmed to 4 bits) which makes it 9
02D 01280        138                         LOAD      Temp3, 200          ; Load Temp3 register
W: value out of range: 200, allowed range is [0,15] (trimmed to 4 bits) which makes it 8
02E 1D010        139     wait_1s_i:          SUB       Temp1, 1
02F 3542E        140                         JUMP      NZ, wait_1s_i
030 1D110        141                         SUB       Temp2, 1
031 3542E        142                         JUMP      NZ, wait_1s_i
032 1D210        143                         SUB       Temp3, 1
033 3542E        144                         JUMP      NZ, wait_1s_i
034 2A000        145                         RET
                 146     
035 010A0        147     wait_100ms:         LOAD      Temp1, 250          ; Load Temp1 register
036 01190        148                         LOAD      Temp2, 249          ; Load Temp2 register
037 01240        149                         LOAD      Temp3, 20           ; Load Temp3 register
W: value out of range: 20, allowed range is [0,15] (trimmed to 4 bits) which makes it 4
038 1D010        150     wait_100ms_i:       SUB       Temp1, 1
039 35438        151                         JUMP      NZ, wait_100ms_i
03A 1D110        152                         SUB       Temp2, 1
03B 35438        153                         JUMP      NZ, wait_100ms_i
03C 1D210        154                         SUB       Temp3, 1
03D 35438        155                         JUMP      NZ, wait_100ms_i
03E 2A000        156                         RET
                 157     
                 158     ;##############################################################################;
