S0 . . . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 NOT USED CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 NOT USED CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 NOT USED CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 NOT USED CONSTANT    IMPLICIT
S8 . . . . . . . . . . . . . . . . . REG.   0x00008 NOT USED CONSTANT    IMPLICIT
S9 . . . . . . . . . . . . . . . . . REG.   0x00009 NOT USED CONSTANT    IMPLICIT
SA . . . . . . . . . . . . . . . . . REG.   0x0000A NOT USED CONSTANT    IMPLICIT
SB . . . . . . . . . . . . . . . . . REG.   0x0000B NOT USED CONSTANT    IMPLICIT
SC . . . . . . . . . . . . . . . . . REG.   0x0000C NOT USED CONSTANT    IMPLICIT
SCRATCHPAD_TRANSFERS . . . . . . . . LABEL  0x0000A NOT USED CONSTANT    1004_shift_and_rotate.asm:48.1-48.22
SD . . . . . . . . . . . . . . . . . REG.   0x0000D NOT USED CONSTANT    IMPLICIT
SE . . . . . . . . . . . . . . . . . REG.   0x0000E NOT USED CONSTANT    IMPLICIT
SF . . . . . . . . . . . . . . . . . REG.   0x0000F NOT USED CONSTANT    IMPLICIT
START  . . . . . . . . . . . . . . . LABEL  0x00000 NOT USED CONSTANT    1004_shift_and_rotate.asm:33.1-33.7
TESTSYMB1  . . . . . . . . . . . . . NUMBER 0x00001 NOT USED REDEFINABLE 1004_shift_and_rotate.asm:6.1-6.27
TESTSYMB10 . . . . . . . . . . . . . REG.   0x00009 USED     CONSTANT    1004_shift_and_rotate.asm:15.1-15.28
TESTSYMB11 . . . . . . . . . . . . . REG.   0x0000A NOT USED CONSTANT    1004_shift_and_rotate.asm:16.1-16.28
TESTSYMB12 . . . . . . . . . . . . . REG.   0x0000B NOT USED CONSTANT    1004_shift_and_rotate.asm:17.1-17.28
TESTSYMB13 . . . . . . . . . . . . . DATA   0x0000C NOT USED CONSTANT    1004_shift_and_rotate.asm:18.1-18.29
TESTSYMB14 . . . . . . . . . . . . . DATA   0x00005 NOT USED CONSTANT    1004_shift_and_rotate.asm:19.1-19.31
TESTSYMB15 . . . . . . . . . . . . . DATA   0x00002 NOT USED CONSTANT    1004_shift_and_rotate.asm:20.1-20.28
TESTSYMB16 . . . . . . . . . . . . . DATA   0x00003 NOT USED CONSTANT    1004_shift_and_rotate.asm:21.1-21.29
TESTSYMB17 . . . . . . . . . . . . . LABEL  0x00002 NOT USED CONSTANT    1004_shift_and_rotate.asm:22.1-22.34
TESTSYMB18 . . . . . . . . . . . . . LABEL  0x00002 NOT USED CONSTANT    1004_shift_and_rotate.asm:23.1-23.29
TESTSYMB19 . . . . . . . . . . . . . LABEL  0x00002 NOT USED CONSTANT    1004_shift_and_rotate.asm:24.1-24.29
TESTSYMB2  . . . . . . . . . . . . . NUMBER 0x00011 NOT USED REDEFINABLE 1004_shift_and_rotate.asm:7.1-7.29
TESTSYMB20 . . . . . . . . . . . . . LABEL  0x00002 NOT USED CONSTANT    1004_shift_and_rotate.asm:25.1-25.29
TESTSYMB21 . . . . . . . . . . . . . EXPR.          NOT USED CONSTANT    1004_shift_and_rotate.asm:26.1-26.31
TESTSYMB22 . . . . . . . . . . . . . EXPR.          NOT USED CONSTANT    1004_shift_and_rotate.asm:27.1-27.31
TESTSYMB23 . . . . . . . . . . . . . EXPR.          NOT USED CONSTANT    1004_shift_and_rotate.asm:28.1-28.31
TESTSYMB24 . . . . . . . . . . . . . EXPR.          NOT USED CONSTANT    1004_shift_and_rotate.asm:29.1-29.51
TESTSYMB3  . . . . . . . . . . . . . NUMBER 0x00001 NOT USED REDEFINABLE 1004_shift_and_rotate.asm:8.1-8.26
TESTSYMB4  . . . . . . . . . . . . . NUMBER 0x00003 NOT USED REDEFINABLE 1004_shift_and_rotate.asm:9.1-9.27
TESTSYMB5  . . . . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    1004_shift_and_rotate.asm:10.1-10.27
TESTSYMB6  . . . . . . . . . . . . . NUMBER 0x00005 NOT USED CONSTANT    1004_shift_and_rotate.asm:11.1-11.29
TESTSYMB7  . . . . . . . . . . . . . NUMBER 0x00006 NOT USED CONSTANT    1004_shift_and_rotate.asm:12.1-12.26
TESTSYMB8  . . . . . . . . . . . . . NUMBER 0x00007 NOT USED CONSTANT    1004_shift_and_rotate.asm:13.1-13.26
TESTSYMB9  . . . . . . . . . . . . . REG.   0x00008 NOT USED CONSTANT    1004_shift_and_rotate.asm:14.1-14.27
