                   1     device kcpsm1
                   2
                   3
  00006            4     ss3      EQU     0x06
  00006            5     B       SET     6
                   6
                   7
                   8
  00000            9     Start:
                  10             SKIP    6
006 0C120         11             LOAD    s1,s2
007 0C120         12             LOAD    s1,s2
008 0C120         13             LOAD    s1,s2
009 0C120         14             LOAD    s1,s2
00A 0C120         15             LOAD    s1,s2
00B 0C120         16             LOAD    s1,s2
                  17
                  18             #WHILE   B
                  19                     SR0     s0
                  20                     B       SET     B - 1
                  21             #ENDW
00C 0D00E         22 +1                  SR0     s0
  00005           23 +1                  B       SET     B - 1
00D 0D00E         24 +1                  SR0     s0
  00004           25 +1                  B       SET     B - 1
00E 0D00E         26 +1                  SR0     s0
  00003           27 +1                  B       SET     B - 1
00F 0D00E         28 +1                  SR0     s0
  00002           29 +1                  B       SET     B - 1
010 0D00E         30 +1                  SR0     s0
  00001           31 +1                  B       SET     B - 1
011 0D00E         32 +1                  SR0     s0
  00000           33 +1                  B       SET     B - 1
                  34
                  35             REPT    8
                  36                     SL0     sC
                  37             ENDR
012 0DC06         38 +1                  SL0     sC
013 0DC06         39 +1                  SL0     sC
014 0DC06         40 +1                  SL0     sC
015 0DC06         41 +1                  SL0     sC
016 0DC06         42 +1                  SL0     sC
017 0DC06         43 +1                  SL0     sC
018 0DC06         44 +1                  SL0     sC
019 0DC06         45 +1                  SL0     sC
                  46
                  47             END
                  48
                  49
