                   1     ; Compiler test case for Assembler
                   2     ; instruction opcodes
                   3
                   4     device kcpsm2
                   5     s1       EQU        04h
E: symbol already defined: "S1".
                   6     s2       EQU        0x04
E: symbol already defined: "S2".
                   7     s3       EQU        6
E: symbol already defined: "S3".
                   8     s4       EQU        7
E: symbol already defined: "S4".
                   9
                  10
                  11
  00000           12     START:
                  13          ; Arithmetics
000 08101         14             ADD        s1,#01h
001 08105         15             ADD        s1,#5
002 08105         16             ADD        s1,#05h
003 08105         17             ADD        s1,#0x05
004 08105         18             ADD        s1,#0b101
005 08105         19             ADD        s1,#0b00000101
006 08105         20             ADD        s1,#5D
007 08105         21             ADD        s1,#5O
008 08105         22             ADD        s1,#5Q
009 08105         23             ADD        s1,#5h
00A 08105         24             ADD        s1,#101b
00B 08105         25             ADD        s1,#00000101b
                  26
                  27
00C 0A101         28             ADDCY      s1,#01h
00D 0A105         29             ADDCY      s1,#5
00E 0A105         30             ADDCY      s1,#05h
00F 0A105         31             ADDCY      s1,#0x05
010 0A105         32             ADDCY      s1,#0b101
011 0A105         33             ADDCY      s1,#0b00000101
012 0A105         34             ADDCY      s1,#5D
013 0A105         35             ADDCY      s1,#5O
014 0A105         36             ADDCY      s1,#5Q
015 0A105         37             ADDCY      s1,#5h
016 0A105         38             ADDCY      s1,#101b
017 0A105         39             ADDCY      s1,#00000101b
                  40
                  41
018 0C101         42             SUB        s1,#01h
019 0C105         43             SUB        s1,#5
01A 0C105         44             SUB        s1,#05h
01B 0C105         45             SUB        s1,#0x05
01C 0C105         46             SUB        s1,#0b101
01D 0C105         47             SUB        s1,#0b00000101
01E 0C105         48             SUB        s1,#5D
01F 0C105         49             SUB        s1,#5O
020 0C105         50             SUB        s1,#5Q
021 0C105         51             SUB        s1,#5h
022 0C105         52             SUB        s1,#101b
023 0C105         53             SUB        s1,#00000101b
                  54
                  55
024 0E101         56             SUBCY      s1,#01h
025 0E105         57             SUBCY      s1,#5
026 0E105         58             SUBCY      s1,#05h
027 0E105         59             SUBCY      s1,#0x05
028 0E105         60             SUBCY      s1,#0b101
029 0E105         61             SUBCY      s1,#0b00000101
02A 0E105         62             SUBCY      s1,#5D
02B 0E105         63             SUBCY      s1,#5O
02C 0E105         64             SUBCY      s1,#5Q
02D 0E105         65             SUBCY      s1,#5h
02E 0E105         66             SUBCY      s1,#101b
02F 0E105         67             SUBCY      s1,#00000101b
                  68
                  69
                  70             COMPARE    s1,#01h
E: instruction not supported on the this device: COMPARE sX, kk.
                  71             COMPARE    s1,#5
E: instruction not supported on the this device: COMPARE sX, kk.
                  72             COMPARE    s1,#05h
E: instruction not supported on the this device: COMPARE sX, kk.
                  73             COMPARE    s1,#0x05
E: instruction not supported on the this device: COMPARE sX, kk.
                  74             COMPARE    s1,#0b101
E: instruction not supported on the this device: COMPARE sX, kk.
                  75             COMPARE    s1,#0b00000101
E: instruction not supported on the this device: COMPARE sX, kk.
                  76             COMPARE    s1,#5D
E: instruction not supported on the this device: COMPARE sX, kk.
                  77             COMPARE    s1,#5O
E: instruction not supported on the this device: COMPARE sX, kk.
                  78             COMPARE    s1,#5Q
E: instruction not supported on the this device: COMPARE sX, kk.
                  79             COMPARE    s1,#5h
E: instruction not supported on the this device: COMPARE sX, kk.
                  80             COMPARE    s1,#101b
E: instruction not supported on the this device: COMPARE sX, kk.
                  81             COMPARE    s1,#00000101b
E: instruction not supported on the this device: COMPARE sX, kk.
                  82
030 18210         83             ADD         s2,s2
031 1A210         84             ADDCY       s2,s2
032 1C210         85             SUB         s2,s2
033 1E218         86             SUBCY       s2,s3
                  87             COMPARE     s2,s4
E: instruction not supported on the this device: COMPARE sX, sY.
                  88
                  89     END
                  90
                  91
                  92       ;  JUMP aaa ADD sX,kk LOAD sX,kk SR0 sX
                  93     ;JUMP Z,aaa ADDCY sX,kk AND sX,kk SR1 sX
                  94     ;JUMP NZ,aaa SUB sX,kk OR sX,kk SRX sX
                  95     ;JUMP C,aaa SUBCY sX,kk XOR sX,kk SRA sX
                  96     ;JUMP NC,aaa COMPARE sX,kk TEST sX,kk RR sX
                  97     ;CALL aaa ADD sX,sY LOAD sX,sY SL0 sX
                  98     ;CALL Z,aaa ADDCY sX,sY AND sX,sY SL1 sX
                  99     ;CALL NZ,aaa SUB sX,sY OR sX,sY SLX sX
                 100     ;CALL C,aaa SUBCY sX,sY XOR sX,sY SLA sX
                 101     ;CALL NC,aaa COMPARE sX,sY TEST sX,sY RL sX
