                   1     ; Compiler load case for Assembler
                   2     ; instruction opcodes
                   3
                   4     device kcpsm2
                   5     s1       EQU        04h
E: symbol already defined: "S1".
                   6     s2       EQU        0x04
E: symbol already defined: "S2".
                   7     s3       EQU        6
E: symbol already defined: "S3".
                   8     s4       EQU        7
E: symbol already defined: "S4".
                   9
                  10
                  11
  00000           12     START:
                  13          ; Arithmetics
000 08101         14             ADD        s1,#01h
001 08105         15             ADD        s1,#5
002 08105         16             ADD        s1,#05h
003 08105         17             ADD        s1,#0x05
004 08105         18             ADD        s1,#0b101
005 08105         19             ADD        s1,#0b00000101
006 08105         20             ADD        s1,#5D
007 08105         21             ADD        s1,#5O
008 08105         22             ADD        s1,#5Q
009 08105         23             ADD        s1,#5h
00A 08105         24             ADD        s1,#101b
00B 08105         25             ADD        s1,#00000101b
                  26
                  27
00C 0A101         28             ADDCY      s1,#01h
00D 0A105         29             ADDCY      s1,#5
00E 0A105         30             ADDCY      s1,#05h
00F 0A105         31             ADDCY      s1,#0x05
010 0A105         32             ADDCY      s1,#0b101
011 0A105         33             ADDCY      s1,#0b00000101
012 0A105         34             ADDCY      s1,#5D
013 0A105         35             ADDCY      s1,#5O
014 0A105         36             ADDCY      s1,#5Q
015 0A105         37             ADDCY      s1,#5h
016 0A105         38             ADDCY      s1,#101b
017 0A105         39             ADDCY      s1,#00000101b
                  40
                  41
018 0C101         42             SUB        s1,#01h
019 0C105         43             SUB        s1,#5
01A 0C105         44             SUB        s1,#05h
01B 0C105         45             SUB        s1,#0x05
01C 0C105         46             SUB        s1,#0b101
01D 0C105         47             SUB        s1,#0b00000101
01E 0C105         48             SUB        s1,#5D
01F 0C105         49             SUB        s1,#5O
020 0C105         50             SUB        s1,#5Q
021 0C105         51             SUB        s1,#5h
022 0C105         52             SUB        s1,#101b
023 0C105         53             SUB        s1,#00000101b
                  54
                  55
024 0E101         56             SUBCY      s1,#01h
025 0E105         57             SUBCY      s1,#5
026 0E105         58             SUBCY      s1,#05h
027 0E105         59             SUBCY      s1,#0x05
028 0E105         60             SUBCY      s1,#0b101
029 0E105         61             SUBCY      s1,#0b00000101
02A 0E105         62             SUBCY      s1,#5D
02B 0E105         63             SUBCY      s1,#5O
02C 0E105         64             SUBCY      s1,#5Q
02D 0E105         65             SUBCY      s1,#5h
02E 0E105         66             SUBCY      s1,#101b
02F 0E105         67             SUBCY      s1,#00000101b
                  68
                  69
030 00101         70             load    s1,#01h
031 00105         71             load    s1,#5
032 00105         72             load    s1,#05h
033 00105         73             load    s1,#0x05
034 00105         74             load    s1,#0b101
035 00105         75             load    s1,#0b00000101
036 00105         76             load    s1,#5D
037 00105         77             load    s1,#5O
038 00105         78             load    s1,#5Q
039 00105         79             load    s1,#5h
03A 00105         80             load    s1,#101b
03B 00105         81             load    s1,#00000101b
                  82
03C 18210         83             ADD         s2,s2
03D 1A210         84             ADDCY       s2,s2
03E 1C210         85             SUB         s2,s2
03F 1E218         86             SUBCY       s2,s3
040 10220         87             load     s2,s4
                  88
                  89     END
                  90
                  91
                  92       ;  JUMP aaa ADD sX,kk LOAD sX,kk SR0 sX
                  93     ;JUMP Z,aaa ADDCY sX,kk AND sX,kk SR1 sX
                  94     ;JUMP NZ,aaa SUB sX,kk OR sX,kk SRX sX
                  95     ;JUMP C,aaa SUBCY sX,kk XOR sX,kk SRA sX
                  96     ;JUMP NC,aaa load sX,kk load sX,kk RR sX
                  97     ;CALL aaa ADD sX,sY LOAD sX,sY SL0 sX
                  98     ;CALL Z,aaa ADDCY sX,sY AND sX,sY SL1 sX
                  99     ;CALL NZ,aaa SUB sX,sY OR sX,sY SLX sX
                 100     ;CALL C,aaa SUBCY sX,sY XOR sX,sY SLA sX
                 101     ;CALL NC,aaa load sX,sY load sX,sY RL sX
