                   1     ; Compiler test case for Assembler
                   2     ; instruction opcodes
                   3
                   4     device kcpsm2
                   5
                   6
  00000            7     Start:
000 35000          8             JUMP        Z, 0x000
W: instruction `JUMP Z, aaa' requires operand #2 to be of type(s): label; while the given operand is of type: number.
001 35400          9             JUMP        NZ,0x000
W: instruction `JUMP NZ, aaa' requires operand #2 to be of type(s): label; while the given operand is of type: number.
002 35800         10             JUMP        C, 0x000
W: instruction `JUMP C, aaa' requires operand #2 to be of type(s): label; while the given operand is of type: number.
003 35C00         11             JUMP        NC,0x000
W: instruction `JUMP NC, aaa' requires operand #2 to be of type(s): label; while the given operand is of type: number.
                  12
                  13
                  14         ; Others
004 36009         15             CALl      Podprog
005 37009         16             CALL      Z,Podprog
006 37409         17             CALL      NZ,Podprog
007 37809         18             CALL      C,Podprog
008 37C09         19             CALL      NC,Podprog
                  20
  00009           21     Podprog:
009 24000         22             RETURN
00A 25000         23             RETURN    Z
00B 25400         24             RETURN    NZ
00C 25800         25             RETURN    C
00D 25C00         26             RETURN    NC
                  27
                  28
                  29       ;  JUMP aaa ADD sX,kk LOAD sX,kk SR0 sX
                  30     ;JUMP Z,aaa ADDCY sX,kk AND sX,kk SR1 sX
                  31     ;JUMP NZ,aaa SUB sX,kk OR sX,kk SRX sX
                  32     ;JUMP C,aaa SUBCY sX,kk XOR sX,kk SRA sX
                  33     ;JUMP NC,aaa COMPARE sX,kk TEST sX,kk RR sX
                  34     ;CALL aaa ADD sX,sY LOAD sX,sY SL0 sX
                  35     ;CALL Z,aaa ADDCY sX,sY AND sX,sY SL1 sX
                  36     ;CALL NZ,aaa SUB sX,sY OR sX,sY SLX sX
                  37     ;CALL C,aaa SUBCY sX,sY XOR sX,sY SLA sX
                  38     ;CALL NC,aaa COMPARE sX,sY TEST sX,sY RL sX
