                   1     device kcpsm2
                   2
                   3     ; -------------------------------------------------------------------------------
                   4     ; SPI routines
                   5     ; data to move in s1, s1&s2, s1&s2&s3
                   6     ; uses s0, sF
                   7     ; sE: bit in the command reg of the SPI_LE pin
                   8     ; sD: address of the command register
                   9     ; sC: address of the SPI control/status register
                  10     ; -------------------------------------------------------------------------------
                  11
                  12
  00001           13     bMOSI           EQU    0b00000001
  00080           14     bMISO           EQU    0b10000000
  00002           15     bSCLK           EQU    0b00000010
                  16
  00000           17     ESPI24:
                  18           ; address of the SPI register, contains MOSI, MISO, SCLK signals
  00000           19     SPI24:
000 31F68         20                     IN      sF, @sD                  ; switch on the appropriate CE
001 06EFF         21                     XOR     sE, #FFh
002 12F70         22                     AND     sF, sE
003 32F68         23                     OUT     sF, @sD
                  24
004 10008         25                     LOAD    s0, s1
005 3601C         26                     CALL    SPI8
006 10010         27                     LOAD    s0, s2
007 3601C         28                     CALL    SPI8
008 10018         29                     LOAD    s0, s3
009 3601C         30                     CALL    SPI8
                  31
00A 31F68         32                     IN      sF, @sD
00B 06EFF         33                     XOR     sE, #FFh
00C 14F70         34                     OR      sF, sE
00D 32F68         35                     OUT     sF, @sD                  ; switch off the CE
                  36
00E 24000         37                     RET
                  38
  0000F           39     ESPI16:
                  40           ; address of the SPI register, contains MOSI, MISO, SCLK signals
  0000F           41     SPI16:
00F 31F68         42                     IN      sF, @sD                  ; switch on the appropriate CE
010 06EFF         43                     XOR     sE, #FFh
011 12F70         44                     AND     sF, sE
012 32F68         45                     OUT     sF, @sD
                  46
013 10008         47                     LOAD    s0, s1
014 3601C         48                     CALL    SPI8
015 10010         49                     LOAD    s0, s2
016 3601C         50                     CALL    SPI8
                  51
017 31F68         52                     IN      sF, @sD
018 06EFF         53                     XOR     sE, #FFh
019 14F70         54                     OR      sF, sE
01A 32F68         55                     OUT     sF, @sD                  ; switch off the CE
                  56
01B 24000         57                     RET
                  58
  0001C           59     ESPI8:
                  60         ; address of the SPI register, contains MOSI, MISO, SCLK signals
  0001C           61     SPI8:
01C 31F68         62                     IN      sF, @sD                  ; switch on the appropriate CE
01D 06EFF         63                     XOR     sE, #FFh
01E 12F70         64                     AND     sF, sE
01F 32F68         65                     OUT     sF, @sD
                  66
020 10008         67                     LOAD    s0, s1
021 3601C         68                     CALL    SPI8
                  69
022 31F68         70                     IN      sF, @sD
023 06EFF         71                     XOR     sE, #FFh
024 14F70         72                     OR      sF, sE
025 32F68         73                     OUT     sF, @sD                  ; switch off the CE
                  74
026 24000         75                     RET
                  76
                  77     ; -------------------------------------------------------------------------------
                  78     ; raw SPI routines
                  79     ; byte to move in s0
                  80     ; uses sF
                  81     ; -------------------------------------------------------------------------------
                  82
  00027           83     SPI8_:                                          ; shift 8 bits
027 36028         84                     CALL    SPI4_
                  85
  00028           86     SPI4_:                                          ; shift 4 bits
028 36029         87                     CALL    SPI2_
                  88
  00029           89     SPI2_:                                          ; shift 2 bits
029 3602A         90                     CALL    SPI1_
                  91
                  92     ; -------------------------------------------------------------------------------
                  93     ; send one bit w/clock
                  94     ; -------------------------------------------------------------------------------
                  95
  0002A           96     SPI1_:                                          ; shift 1 bit
02A 31F60         97                     IN      sF, @sC
02B 12FF0         98                     AND     sF, ~ bMOSI             ; clear MOSI bit
W: instruction `AND sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: expression.
R: result is negative number: 0xfffffffffffffffe, this will represented as 5-bit number in two's complement arithmetic which makes it: 0x1e.
                  99
02C 28006        100                     SL0     s0                      ; check if upper bit set
02D 14F08        101                     OR      sF, bMOSI               ; set MOSI bit
W: instruction `OR sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
                 102
02E 32F60        103                     OUT     sF, @sC                  ; update MOSI signal
02F 14F10        104                     OR      sF, bSCLK               ; set SCLK bit
W: instruction `OR sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
030 32F60        105                     OUT     sF, @sC                  ; update SCLK signal
031 12FE8        106                     AND     sF, ~ bSCLK             ; clear SCLK bit
W: instruction `AND sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: expression.
R: result is negative number: 0xfffffffffffffffd, this will represented as 5-bit number in two's complement arithmetic which makes it: 0x1d.
032 32F60        107                     OUT     sF, @sC                  ; update SCLK bit
                 108
033 31F60        109                     IN      sF, @sC
                 110                     TEST    sF, bMISO               ; test MISO signal
W: instruction `TEST sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
E: instruction not supported on the this device: TEST sX, sY.
034 25000        111                     RET     Z
035 04001        112                     OR      s0, #1                   ; reflect it in s0
036 24000        113                     RET
                 114
                 115     ; -----------SPI Subroutines end-------------------------------------------------
