                   1     ; test case for directives
                   2     device kcpsm2
                   3
                   4
  00000            5     s10     AUTOSPR
E: symbol already defined: "S10".
  00001            6     s11     AUTOSPR
E: symbol already defined: "S11".
  00002            7     s12     AUTOSPR
E: symbol already defined: "S12".
  00003            8     s13     AUTOSPR
E: symbol already defined: "S13".
  00004            9     s14     AUTOSPR
E: symbol already defined: "S14".
  00005           10     s15     AUTOSPR
E: symbol already defined: "S15".
  00006           11     s16     AUTOSPR
E: symbol already defined: "S16".
  00007           12     s17     AUTOSPR
E: symbol already defined: "S17".
  00008           13     s18     AUTOSPR
E: symbol already defined: "S18".
  00009           14     s19     AUTOSPR
E: symbol already defined: "S19".
                  15
  00244           16     a1      EQU     580
  3FFFF           17     a2      EQU     0xFFFFFF
W: value out of range: 0xffffff, allowed range is [0x0,0x3ffff] (trimmed to 18 bits) which makes it 0x3ffff.
  00000           18     a3      EQU     0
  00019           19     a4      EQU     0b11001
  00001           20     a5      EQU     0b0001
  00011           21     a6      EQU     0b00010001
  00001           22     a7      EQU     0b00000001
  00003           23     a8      EQU     3
  00001           24     a9      EQU     1h
  00011           25     a10     EQU     11h
  000AA           26     a11     EQU     AAh
  00004           27     a12     EQU     0x04
                  28
  00244           29     b1      SET     580
  3FFFF           30     b2      SET     0xFFFFFF
W: value out of range: 0xffffff, allowed range is [0x0,0x3ffff] (trimmed to 18 bits) which makes it 0x3ffff.
  00000           31     b3      SET     0
  00019           32     b4      SET     0b11001
  00001           33     b5      SET     0b0001
  00011           34     b6      SET     0b00010001
  00001           35     b7      SET     0b00000001
  00003           36     b8      SET     3
  00001           37     b9      SET     1h
  00011           38     b10     SET     11h
  000AA           39     b11     SET     AAh
  00004           40     b12     SET     0x04
                  41
  00222           42     CONSTANT        c1,546
  0FFFF           43     CONSTANT        c2,0xffff
  0000C           44     CONSTANT        c3,12
  00000           45     CONSTANT        c4,0
  00000           46     CONSTANT        c5,0b00000000
  00001           47     CONSTANT        c6,0b001
  00001           48     CONSTANT        c7,0b01
  00015           49     CONSTANT        c8,0b00010101
  0001E           50     CONSTANT        c9,0b11110
  00001           51     CONSTANT        c10,1h
  000FE           52     CONSTANT        c11,FEh
  00003           53     CONSTANT        c12,0x03
                  54
  00222           55     VARIABLE        d1,546
  0FFFF           56     VARIABLE        d2,0xffff
  0000C           57     VARIABLE        d3,12
  00000           58     VARIABLE        d4,0
  00000           59     VARIABLE        d5,0b00000000
  00001           60     VARIABLE        d6,0b001
  00001           61     VARIABLE        d7,0b01
  00015           62     VARIABLE        d8,0b00010101
  0001E           63     VARIABLE        d9,0b11110
  00001           64     VARIABLE        d10,1h
  000FE           65     VARIABLE        d11,FEh
  00003           66     VARIABLE        d12,0x03
                  67
  00001           68     NAMEREG         1,AHOJ
  00002           69     NAMEREG         2,TE
  00003           70     NAMEREG         3,VY
  00004           71     NAMEREG         4,TAM
  00005           72     NAMEREG         5,DOLE
  00006           73     NAMEREG         6,ZDRA
  00007           74     NAMEREG         7,VIM
  00008           75     NAMEREG         8,VAS
  00009           76     NAMEREG         9,SECKY
  0000A           77     NAMEREG         10,HOLA
  0000B           78     NAMEREG         11,OLA
  0000C           79     NAMEREG         12,HEJ
                  80
                  81
  00001           82     f1      REG     1
W: reusing already reserved space in register file memory at address: 0x1.
  00002           83     f2      REG     2
W: reusing already reserved space in register file memory at address: 0x2.
  00003           84     f3      REG     3
W: reusing already reserved space in register file memory at address: 0x3.
  00004           85     f4      REG     4
W: reusing already reserved space in register file memory at address: 0x4.
  00005           86     f5      REG     5
W: reusing already reserved space in register file memory at address: 0x5.
  00006           87     f6      REG     6
W: reusing already reserved space in register file memory at address: 0x6.
  00007           88     f7      REG     7
W: reusing already reserved space in register file memory at address: 0x7.
  00008           89     f8      REG     8
W: reusing already reserved space in register file memory at address: 0x8.
  00009           90     f9      REG     9
W: reusing already reserved space in register file memory at address: 0x9.
  0000A           91     f10     REG     10
W: reusing already reserved space in register file memory at address: 0xa.
  0000B           92     f11     REG     11
W: reusing already reserved space in register file memory at address: 0xb.
  0000C           93     f12     REG     12
W: reusing already reserved space in register file memory at address: 0xc.
                  94
  00001           95     g1      DATA     1
W: reusing already reserved space in scratch pad memory at address: 0x1.
  00002           96     g2      DATA     2
W: reusing already reserved space in scratch pad memory at address: 0x2.
  00003           97     g3      DATA     3
W: reusing already reserved space in scratch pad memory at address: 0x3.
  00004           98     g4      DATA     4
W: reusing already reserved space in scratch pad memory at address: 0x4.
  00005           99     g5      DATA     5
W: reusing already reserved space in scratch pad memory at address: 0x5.
  00006          100     g6      DATA     6
W: reusing already reserved space in scratch pad memory at address: 0x6.
  00007          101     g7      DATA     7
W: reusing already reserved space in scratch pad memory at address: 0x7.
  00008          102     g8      DATA     8
W: reusing already reserved space in scratch pad memory at address: 0x8.
  00009          103     g9      DATA     9
W: reusing already reserved space in scratch pad memory at address: 0x9.
  00011          104     g10     DATA     11h
  0000A          105     g11     DATA     Ah
  00004          106     g12     DATA     0x04
W: reusing already reserved space in scratch pad memory at address: 0x4.
                 107
                 108
  00244          109     h1      CODE     580
  3FFFF          110     h2      CODE     0xFFFFFF
W: value out of range: 0xffffff, allowed range is [0x0,0x3ffff] (trimmed to 18 bits) which makes it 0x3ffff.
  00000          111     h3      CODE     0
  00019          112     h4      CODE     0b11001
  00001          113     h5      CODE     0b0001
  00011          114     h6      CODE     0b00010001
  00001          115     h7      CODE     0b00000001
  00003          116     h8      CODE     3
  00001          117     h9      CODE     1h
  00011          118     h10     CODE     11h
  000AA          119     h11     CODE     AAh
  00004          120     h12     CODE     0x04
                 121
  00244          122     i1      PORT     580
  3FFFF          123     i2      PORT     0xFFFFFF
W: value out of range: 0xffffff, allowed range is [0x0,0x3ffff] (trimmed to 18 bits) which makes it 0x3ffff.
  00000          124     i3      PORT     0
  00019          125     i4      PORT     0b11001
  00001          126     i5      PORT     0b0001
  00011          127     i6      PORT     0b00010001
  00001          128     i7      PORT     0b00000001
  00003          129     i8      PORT     3
  00001          130     i9      PORT     1h
  00011          131     i10     PORT     11h
  000AA          132     i11     PORT     AAh
  00004          133     i12     PORT     0x04
                 134
                 135     m1      DEFINE   h8 + i3
                 136     m2      DEFINE   i8 + a11
                 137     m3      DEFINE   A3 * A4 * A5 * A6 * A7 + A8 - A9
                 138     M4      DEFINE   (b5 - B6)--B10
                 139
                 140     ;--- CODE ------------- CODE -----------------CODE -----------------
  003FF          141             ORG     0x3FF
  00000          142             ORG     0x000
000 34001        143             JUMP    Start
                 144
                 145
  00001          146     Start:
                 147             REPT    B6
                 148             SUB     s0,s2                  ; kkkkkkk
                 149             ADD     s1,s2
                 150             ENDR
001 1C010        151 +1          SUB     s0,s2                  ; kkkkkkk
002 18110        152 +1          ADD     s1,s2
003 1C010        153 +1          SUB     s0,s2                  ; kkkkkkk
004 18110        154 +1          ADD     s1,s2
005 1C010        155 +1          SUB     s0,s2                  ; kkkkkkk
006 18110        156 +1          ADD     s1,s2
007 1C010        157 +1          SUB     s0,s2                  ; kkkkkkk
008 18110        158 +1          ADD     s1,s2
009 1C010        159 +1          SUB     s0,s2                  ; kkkkkkk
00A 18110        160 +1          ADD     s1,s2
00B 1C010        161 +1          SUB     s0,s2                  ; kkkkkkk
00C 18110        162 +1          ADD     s1,s2
00D 1C010        163 +1          SUB     s0,s2                  ; kkkkkkk
00E 18110        164 +1          ADD     s1,s2
00F 1C010        165 +1          SUB     s0,s2                  ; kkkkkkk
010 18110        166 +1          ADD     s1,s2
011 1C010        167 +1          SUB     s0,s2                  ; kkkkkkk
012 18110        168 +1          ADD     s1,s2
013 1C010        169 +1          SUB     s0,s2                  ; kkkkkkk
014 18110        170 +1          ADD     s1,s2
015 1C010        171 +1          SUB     s0,s2                  ; kkkkkkk
016 18110        172 +1          ADD     s1,s2
017 1C010        173 +1          SUB     s0,s2                  ; kkkkkkk
018 18110        174 +1          ADD     s1,s2
019 1C010        175 +1          SUB     s0,s2                  ; kkkkkkk
01A 18110        176 +1          ADD     s1,s2
01B 1C010        177 +1          SUB     s0,s2                  ; kkkkkkk
01C 18110        178 +1          ADD     s1,s2
01D 1C010        179 +1          SUB     s0,s2                  ; kkkkkkk
01E 18110        180 +1          ADD     s1,s2
01F 1C010        181 +1          SUB     s0,s2                  ; kkkkkkk
020 18110        182 +1          ADD     s1,s2
021 1C010        183 +1          SUB     s0,s2                  ; kkkkkkk
022 18110        184 +1          ADD     s1,s2
                 185             ;-----------
                 186             REPT    C10
                 187             SUB     s0,s2                  ; kkkkkkk
                 188             ADD     s1,s2
                 189             INPUT   S0,i1
W: value out of range: 0x244, allowed range is [0x0,0xff] (trimmed to 8 bits) which makes it 0x44.
                 190             ENDR
023 1C010        191 +1          SUB     s0,s2                  ; kkkkkkk
024 18110        192 +1          ADD     s1,s2
025 20044        193 +1          INPUT   S0,i1
W: ==> value out of range: 0x244, allowed range is [0x0,0xff] (trimmed to 8 bits) which makes it 0x44.
                 194             ;-------------
                 195     XYZ     MACRO   S0,S1,S2,S3,S4,S5,S6,S7,S8,S9,S9
W: macro parameter `S0' eclipses global symbol `S0'.
W: macro parameter `S1' eclipses global symbol `S1'.
W: macro parameter `S2' eclipses global symbol `S2'.
W: macro parameter `S3' eclipses global symbol `S3'.
W: macro parameter `S4' eclipses global symbol `S4'.
W: macro parameter `S5' eclipses global symbol `S5'.
W: macro parameter `S6' eclipses global symbol `S6'.
W: macro parameter `S7' eclipses global symbol `S7'.
W: macro parameter `S8' eclipses global symbol `S8'.
W: macro parameter `S9' eclipses global symbol `S9'.
W: macro parameter `S9' eclipses global symbol `S9'.
                 196
                 197                 #IF      S0 == S1
                 198                 EXITM
                 199                 #ENDIF
                 200             ENDM
                 201
                 202     XYZ0    MACRO   S0
W: macro parameter `S0' eclipses global symbol `S0'.
                 203
                 204                 #IF      S0 == S1
                 205                 EXITM
                 206                 #ENDIF
                 207             ENDM
                 208
                 209     XYZ1     MACRO   S0,S1
W: macro parameter `S0' eclipses global symbol `S0'.
W: macro parameter `S1' eclipses global symbol `S1'.
                 210
                 211                 #IF      S0 == S1
                 212                 EXITM
                 213                 #ENDIF
                 214             ENDM
                 215
                 216     XYZ2     MACRO   S0,S1,S2
W: macro parameter `S0' eclipses global symbol `S0'.
W: macro parameter `S1' eclipses global symbol `S1'.
W: macro parameter `S2' eclipses global symbol `S2'.
                 217
                 218                 #IF      S0 == S1
                 219                 EXITM
                 220                 #ENDIF
                 221             ENDM
                 222
                 223     XYZ3     MACRO   S0,S1,S2,S3
W: macro parameter `S0' eclipses global symbol `S0'.
W: macro parameter `S1' eclipses global symbol `S1'.
W: macro parameter `S2' eclipses global symbol `S2'.
W: macro parameter `S3' eclipses global symbol `S3'.
                 224
                 225                 #IF      S0 == S1
                 226                 EXITM
                 227                 #ENDIF
                 228             ENDM
                 229     XYZ4     MACRO   S0,S1,S2,S3,S4
W: macro parameter `S0' eclipses global symbol `S0'.
W: macro parameter `S1' eclipses global symbol `S1'.
W: macro parameter `S2' eclipses global symbol `S2'.
W: macro parameter `S3' eclipses global symbol `S3'.
W: macro parameter `S4' eclipses global symbol `S4'.
                 230
                 231                 #IF      S0 == S1
                 232                 EXITM
                 233                 #ENDIF
                 234             ENDM
                 235     XYZ5     MACRO   S0,S1,S2,S3,S4,S5
W: macro parameter `S0' eclipses global symbol `S0'.
W: macro parameter `S1' eclipses global symbol `S1'.
W: macro parameter `S2' eclipses global symbol `S2'.
W: macro parameter `S3' eclipses global symbol `S3'.
W: macro parameter `S4' eclipses global symbol `S4'.
W: macro parameter `S5' eclipses global symbol `S5'.
                 236
                 237                 #IF      S0 == S1
                 238                 EXITM
                 239                 #ENDIF
                 240             ENDM
                 241     XYZ6     MACRO   S0,S1,S2,S3,S4,S5,S6
W: macro parameter `S0' eclipses global symbol `S0'.
W: macro parameter `S1' eclipses global symbol `S1'.
W: macro parameter `S2' eclipses global symbol `S2'.
W: macro parameter `S3' eclipses global symbol `S3'.
W: macro parameter `S4' eclipses global symbol `S4'.
W: macro parameter `S5' eclipses global symbol `S5'.
W: macro parameter `S6' eclipses global symbol `S6'.
                 242
                 243                 #IF      S0 == S1
                 244                 EXITM
                 245                 #ENDIF
                 246             ENDM
                 247     XYZ7     MACRO   S0,S1,S2,S3,S4,S5,S6,S7
W: macro parameter `S0' eclipses global symbol `S0'.
W: macro parameter `S1' eclipses global symbol `S1'.
W: macro parameter `S2' eclipses global symbol `S2'.
W: macro parameter `S3' eclipses global symbol `S3'.
W: macro parameter `S4' eclipses global symbol `S4'.
W: macro parameter `S5' eclipses global symbol `S5'.
W: macro parameter `S6' eclipses global symbol `S6'.
W: macro parameter `S7' eclipses global symbol `S7'.
                 248
                 249                 #IF      S0 == S1
                 250                 EXITM
                 251                 #ENDIF
                 252             ENDM
                 253     XYZ8     MACRO   S0,S1,S2,S3,S4,S5,S6,S7,S8
W: macro parameter `S0' eclipses global symbol `S0'.
W: macro parameter `S1' eclipses global symbol `S1'.
W: macro parameter `S2' eclipses global symbol `S2'.
W: macro parameter `S3' eclipses global symbol `S3'.
W: macro parameter `S4' eclipses global symbol `S4'.
W: macro parameter `S5' eclipses global symbol `S5'.
W: macro parameter `S6' eclipses global symbol `S6'.
W: macro parameter `S7' eclipses global symbol `S7'.
W: macro parameter `S8' eclipses global symbol `S8'.
                 254
                 255                 #IF      S0 == S1
                 256                 EXITM
                 257                 #ENDIF
                 258             ENDM
                 259
                 260
                 261             END
                 262             5555BALBALBALABLABALA
                 263
                 264
