MT_WARNING: 2015_PicoBlaze_SDR.asm:49.31-49.36: Warning: instruction `LOAD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:51.31-51.36: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:66.38-66.39: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:68.31-68.36: Warning: instruction `OUTPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:76.38-76.39: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:78.31-78.36: Warning: instruction `INPUT sX, pp' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:87.38-87.43: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:88.31-88.36: Warning: instruction `SR0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:89.31-89.36: Warning: instruction `SR0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:90.31-90.36: Warning: instruction `SR0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:91.31-91.36: Warning: instruction `SR0 sX' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:92.31-92.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:92.38-92.40: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:94.31-94.36: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:96.31-96.36: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:99.31-99.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:100.31-100.36: Warning: instruction `AND sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:101.31-101.36: Warning: instruction `LOAD sX, sY' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:101.38-101.40: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:103.31-103.36: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:105.31-105.36: Warning: instruction `ADD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:114.31-114.36: Warning: instruction `LOAD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:116.31-116.36: Warning: instruction `LOAD sX, kk' requires operand #1 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:136.38-136.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:137.38-137.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:138.38-138.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:139.38-139.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:141.38-141.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:143.38-143.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:147.38-147.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:148.38-148.41: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:149.38-149.40: Warning: instruction `LOAD sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:150.38-150.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:152.38-152.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:154.38-154.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 2015_PicoBlaze_SDR.asm:136.38-136.41: Warning: value out of range: 0xfa, allowed range is [0x0,0x1f] (trimmed to 5 bits) which makes it 0x1a.
MT_WARNING: 2015_PicoBlaze_SDR.asm:137.38-137.41: Warning: value out of range: 0xf9, allowed range is [0x0,0x1f] (trimmed to 5 bits) which makes it 0x19.
MT_WARNING: 2015_PicoBlaze_SDR.asm:138.38-138.41: Warning: value out of range: 0xc8, allowed range is [0x0,0x1f] (trimmed to 5 bits) which makes it 0x8.
MT_WARNING: 2015_PicoBlaze_SDR.asm:147.38-147.41: Warning: value out of range: 0xfa, allowed range is [0x0,0x1f] (trimmed to 5 bits) which makes it 0x1a.
MT_WARNING: 2015_PicoBlaze_SDR.asm:148.38-148.41: Warning: value out of range: 0xf9, allowed range is [0x0,0x1f] (trimmed to 5 bits) which makes it 0x19.
