INTERRUPT  . . . . . . . . . . . . . LABEL  0x00000 NOT USED CONSTANT    2021_demo_4.asm:156.1-156.11
LED_ID . . . . . . . . . . . . . . . PORT   0x00008 NOT USED CONSTANT    2021_demo_4.asm:32.9-32.37
LED_REG  . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    2021_demo_4.asm:27.9-27.38
MAIN_LOOP  . . . . . . . . . . . . . LABEL  0x00041 USED     CONSTANT    2021_demo_4.asm:173.1-173.11
RXEQU  . . . . . . . . . . . . . . . REG.   0x00003 NOT USED CONSTANT    2021_demo_4.asm:25.9-25.32
RX_EQU . . . . . . . . . . . . . . . NUMBER 0x00004 USED     CONSTANT    2021_demo_4.asm:18.1-18.41
RX_ID  . . . . . . . . . . . . . . . PORT   0x00002 USED     CONSTANT    2021_demo_4.asm:30.9-30.37
S0 . . . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    IMPLICIT
S10  . . . . . . . . . . . . . . . . REG.   0x00010 NOT USED CONSTANT    IMPLICIT
S11  . . . . . . . . . . . . . . . . REG.   0x00011 NOT USED CONSTANT    IMPLICIT
S12  . . . . . . . . . . . . . . . . REG.   0x00012 NOT USED CONSTANT    IMPLICIT
S13  . . . . . . . . . . . . . . . . REG.   0x00013 NOT USED CONSTANT    IMPLICIT
S14  . . . . . . . . . . . . . . . . REG.   0x00014 NOT USED CONSTANT    IMPLICIT
S15  . . . . . . . . . . . . . . . . REG.   0x00015 NOT USED CONSTANT    IMPLICIT
S16  . . . . . . . . . . . . . . . . REG.   0x00016 NOT USED CONSTANT    IMPLICIT
S17  . . . . . . . . . . . . . . . . REG.   0x00017 NOT USED CONSTANT    IMPLICIT
S18  . . . . . . . . . . . . . . . . REG.   0x00018 NOT USED CONSTANT    IMPLICIT
S19  . . . . . . . . . . . . . . . . REG.   0x00019 NOT USED CONSTANT    IMPLICIT
S1A  . . . . . . . . . . . . . . . . REG.   0x0001A NOT USED CONSTANT    IMPLICIT
S1B  . . . . . . . . . . . . . . . . REG.   0x0001B NOT USED CONSTANT    IMPLICIT
S1C  . . . . . . . . . . . . . . . . REG.   0x0001C NOT USED CONSTANT    IMPLICIT
S1D  . . . . . . . . . . . . . . . . REG.   0x0001D NOT USED CONSTANT    IMPLICIT
S1E  . . . . . . . . . . . . . . . . REG.   0x0001E NOT USED CONSTANT    IMPLICIT
S1F  . . . . . . . . . . . . . . . . REG.   0x0001F NOT USED CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 USED     CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 USED     CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 USED     CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 USED     CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 NOT USED CONSTANT    IMPLICIT
S8 . . . . . . . . . . . . . . . . . REG.   0x00008 NOT USED CONSTANT    IMPLICIT
S9 . . . . . . . . . . . . . . . . . REG.   0x00009 NOT USED CONSTANT    IMPLICIT
SA . . . . . . . . . . . . . . . . . REG.   0x0000A NOT USED CONSTANT    IMPLICIT
SB . . . . . . . . . . . . . . . . . REG.   0x0000B NOT USED CONSTANT    IMPLICIT
SC . . . . . . . . . . . . . . . . . REG.   0x0000C NOT USED CONSTANT    IMPLICIT
SD . . . . . . . . . . . . . . . . . REG.   0x0000D NOT USED CONSTANT    IMPLICIT
SE . . . . . . . . . . . . . . . . . REG.   0x0000E NOT USED CONSTANT    IMPLICIT
SF . . . . . . . . . . . . . . . . . REG.   0x0000F NOT USED CONSTANT    IMPLICIT
START  . . . . . . . . . . . . . . . LABEL  0x00038 NOT USED CONSTANT    2021_demo_4.asm:168.1-168.7
TEMP1  . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    2021_demo_4.asm:21.9-21.33
TEMP2  . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    2021_demo_4.asm:22.9-22.33
TEMP3  . . . . . . . . . . . . . . . REG.   0x00002 USED     CONSTANT    2021_demo_4.asm:23.9-23.33
TXEQU  . . . . . . . . . . . . . . . REG.   0x00004 USED     CONSTANT    2021_demo_4.asm:26.9-26.36
TX_ID  . . . . . . . . . . . . . . . PORT   0x00001 USED     CONSTANT    2021_demo_4.asm:29.9-29.37
UART_STAT  . . . . . . . . . . . . . PORT   0x00004 USED     CONSTANT    2021_demo_4.asm:31.9-31.37
WAIT_1S  . . . . . . . . . . . . . . LABEL  0x00038 NOT USED CONSTANT    2021_demo_4.asm:96.1-96.9 ==> 2021_demo_4.asm:169.21-169.32
WAIT_1S_I  . . . . . . . . . . . . . LABEL  0x0003B USED     CONSTANT    2021_demo_4.asm:99.1-99.11 ==> 2021_demo_4.asm:169.21-169.32
