AUTHENTICATION_CONTROL_PORT  . . . . NUMBER 0x00010 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:126.1-126.37
AUTHENTICATION_CRC0  . . . . . . . . NUMBER 0x0001A USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:173.1-173.37
AUTHENTICATION_CRC1  . . . . . . . . NUMBER 0x0001B USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:174.1-174.37
AUTHENTICATION_STATUS  . . . . . . . NUMBER 0x0001C USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:177.1-177.37
AUTHORISE_COMMAND  . . . . . . . . . LABEL  0x0004F USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:486.1-486.19
AUTH_BYTE_LOOP . . . . . . . . . . . LABEL  0x000B2 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:729.1-729.16
AUTH_CHECK2  . . . . . . . . . . . . LABEL  0x0009A USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:695.1-695.13
AUTH_CHECK3  . . . . . . . . . . . . LABEL  0x0009E USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:699.1-699.13
AUTH_CHECK4  . . . . . . . . . . . . LABEL  0x000A2 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:703.1-703.13
AUTH_FAILURE . . . . . . . . . . . . LABEL  0x00036 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:447.1-447.14
AUTH_LINE_LOOP . . . . . . . . . . . LABEL  0x000AF USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:726.1-726.16
AUTH_PASSED  . . . . . . . . . . . . LABEL  0x00033 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:435.1-435.13
AUTH_READ_DELAY  . . . . . . . . . . LABEL  0x000A9 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:710.1-710.17
AUTH_READ_LOOP . . . . . . . . . . . LABEL  0x00095 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:690.1-690.16
AUTH_WRITE_CHECK2  . . . . . . . . . LABEL  0x000C6 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:777.1-777.19
AUTH_WRITE_CHECK3  . . . . . . . . . LABEL  0x000CC USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:783.1-783.19
AUTH_WRITE_CHECK4  . . . . . . . . . LABEL  0x000D2 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:789.1-789.19
AUTH_WRITE_LOOP  . . . . . . . . . . LABEL  0x000BF USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:770.1-770.17
CHARACTER_0  . . . . . . . . . . . . NUMBER 0x00030 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:256.1-256.37
CHARACTER_1  . . . . . . . . . . . . NUMBER 0x00031 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:257.1-257.37
CHARACTER_2  . . . . . . . . . . . . NUMBER 0x00032 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:258.1-258.37
CHARACTER_3  . . . . . . . . . . . . NUMBER 0x00033 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:259.1-259.37
CHARACTER_4  . . . . . . . . . . . . NUMBER 0x00034 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:260.1-260.37
CHARACTER_5  . . . . . . . . . . . . NUMBER 0x00035 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:261.1-261.37
CHARACTER_6  . . . . . . . . . . . . NUMBER 0x00036 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:262.1-262.37
CHARACTER_7  . . . . . . . . . . . . NUMBER 0x00037 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:263.1-263.37
CHARACTER_8  . . . . . . . . . . . . NUMBER 0x00038 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:264.1-264.37
CHARACTER_9  . . . . . . . . . . . . NUMBER 0x00039 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:265.1-265.37
CHARACTER_A  . . . . . . . . . . . . NUMBER 0x00061 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:204.1-204.37
CHARACTER_B  . . . . . . . . . . . . NUMBER 0x00062 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:205.1-205.37
CHARACTER_BS . . . . . . . . . . . . NUMBER 0x00008 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:281.1-281.37
CHARACTER_C  . . . . . . . . . . . . NUMBER 0x00063 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:206.1-206.37
CHARACTER_COLON  . . . . . . . . . . NUMBER 0x0003A NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:266.1-266.37
CHARACTER_COMMA  . . . . . . . . . . NUMBER 0x0002C NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:272.1-272.37
CHARACTER_CR . . . . . . . . . . . . NUMBER 0x0000D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:277.1-277.37
CHARACTER_D  . . . . . . . . . . . . NUMBER 0x00064 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:207.1-207.37
CHARACTER_DIVIDE . . . . . . . . . . NUMBER 0x0002F NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:270.1-270.37
CHARACTER_DOLLAR . . . . . . . . . . NUMBER 0x00024 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:279.1-279.37
CHARACTER_E  . . . . . . . . . . . . NUMBER 0x00065 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:208.1-208.37
CHARACTER_EQUALS . . . . . . . . . . NUMBER 0x0003D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:275.1-275.37
CHARACTER_EXCLAIM  . . . . . . . . . NUMBER 0x00021 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:280.1-280.37
CHARACTER_F  . . . . . . . . . . . . NUMBER 0x00066 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:209.1-209.37
CHARACTER_FULLSTOP . . . . . . . . . NUMBER 0x0002E USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:267.1-267.37
CHARACTER_G  . . . . . . . . . . . . NUMBER 0x00067 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:210.1-210.37
CHARACTER_GREATER_THAN . . . . . . . NUMBER 0x0003E USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:274.1-274.37
CHARACTER_H  . . . . . . . . . . . . NUMBER 0x00068 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:211.1-211.37
CHARACTER_I  . . . . . . . . . . . . NUMBER 0x00069 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:212.1-212.37
CHARACTER_J  . . . . . . . . . . . . NUMBER 0x0006A NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:213.1-213.37
CHARACTER_K  . . . . . . . . . . . . NUMBER 0x0006B NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:214.1-214.37
CHARACTER_L  . . . . . . . . . . . . NUMBER 0x0006C USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:215.1-215.37
CHARACTER_LESS_THAN  . . . . . . . . NUMBER 0x0003C NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:273.1-273.37
CHARACTER_M  . . . . . . . . . . . . NUMBER 0x0006D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:216.1-216.37
CHARACTER_MINUS  . . . . . . . . . . NUMBER 0x0002D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:269.1-269.37
CHARACTER_N  . . . . . . . . . . . . NUMBER 0x0006E USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:217.1-217.37
CHARACTER_O  . . . . . . . . . . . . NUMBER 0x0006F USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:218.1-218.37
CHARACTER_P  . . . . . . . . . . . . NUMBER 0x00070 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:219.1-219.37
CHARACTER_PLUS . . . . . . . . . . . NUMBER 0x0002B NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:271.1-271.37
CHARACTER_Q  . . . . . . . . . . . . NUMBER 0x00071 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:220.1-220.37
CHARACTER_QUESTION . . . . . . . . . NUMBER 0x0003F NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:278.1-278.37
CHARACTER_R  . . . . . . . . . . . . NUMBER 0x00072 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:221.1-221.37
CHARACTER_S  . . . . . . . . . . . . NUMBER 0x00073 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:222.1-222.37
CHARACTER_SEMI_COLON . . . . . . . . NUMBER 0x0003B NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:268.1-268.37
CHARACTER_SPACE  . . . . . . . . . . NUMBER 0x00020 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:276.1-276.37
CHARACTER_T  . . . . . . . . . . . . NUMBER 0x00074 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:223.1-223.37
CHARACTER_U  . . . . . . . . . . . . NUMBER 0x00075 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:224.1-224.37
CHARACTER_V  . . . . . . . . . . . . NUMBER 0x00076 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:225.1-225.37
CHARACTER_W  . . . . . . . . . . . . NUMBER 0x00077 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:226.1-226.37
CHARACTER_X  . . . . . . . . . . . . NUMBER 0x00078 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:227.1-227.37
CHARACTER_Y  . . . . . . . . . . . . NUMBER 0x00079 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:228.1-228.37
CHARACTER_Z  . . . . . . . . . . . . NUMBER 0x0007A USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:229.1-229.37
COLD_START . . . . . . . . . . . . . LABEL  0x00000 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:291.1-291.12
COMPUTED_CRC0  . . . . . . . . . . . NUMBER 0x00018 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:169.1-169.37
COMPUTED_CRC1  . . . . . . . . . . . NUMBER 0x00019 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:170.1-170.37
COMPUTE_CRC16  . . . . . . . . . . . LABEL  0x00084 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:638.1-638.15
COMPUTE_SEEDED_CRC . . . . . . . . . LABEL  0x0007F USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:609.1-609.20
CRC16_LOOP . . . . . . . . . . . . . LABEL  0x00085 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:639.1-639.12
CRC16_SHIFT  . . . . . . . . . . . . LABEL  0x0008B USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:645.1-645.13
DELAY_1MS  . . . . . . . . . . . . . LABEL  0x0034F USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1918.1-1918.11
DELAY_1S . . . . . . . . . . . . . . LABEL  0x00359 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1940.1-1940.10
DELAY_1US  . . . . . . . . . . . . . LABEL  0x00346 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1898.1-1898.11
DELAY_1US_CONSTANT . . . . . . . . . NUMBER 0x0000B USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:197.1-197.37
DELAY_20MS . . . . . . . . . . . . . LABEL  0x00354 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1930.1-1930.12
DELAY_40US . . . . . . . . . . . . . LABEL  0x0034A USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1907.1-1907.12
DELAY_NS . . . . . . . . . . . . . . LABEL  0x0035E USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1951.1-1951.10
DISABLE_APP_HARDWARE . . . . . . . . LABEL  0x00056 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:505.1-505.22
DISP_AUTHENTICATION  . . . . . . . . LABEL  0x003A7 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:2052.1-2052.21
DISP_FAILED  . . . . . . . . . . . . LABEL  0x003D4 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:2112.1-2112.13
DISP_FLASH_SERIAL_NO . . . . . . . . LABEL  0x00386 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:2013.1-2013.22
DISP_HEX_BYTE  . . . . . . . . . . . LABEL  0x0014B USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1158.1-1158.15
DISP_PASSED  . . . . . . . . . . . . LABEL  0x003C6 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:2090.1-2090.13
DISP_PICOBLAZE . . . . . . . . . . . LABEL  0x00362 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1967.1-1967.16
DISP_SECURITY  . . . . . . . . . . . LABEL  0x00375 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1991.1-1991.15
DISP_SERIAL_NUMBER . . . . . . . . . LABEL  0x00070 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:571.1-571.20
DISP_SN_LOOP . . . . . . . . . . . . LABEL  0x00077 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:578.1-578.14
END_DISP_SN  . . . . . . . . . . . . LABEL  0x0007D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:585.1-585.13
END_ISR  . . . . . . . . . . . . . . LABEL  0x003F6 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:2160.1-2160.9
END_READ_SN  . . . . . . . . . . . . LABEL  0x000FD USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:917.1-917.13
END_SEND_SN  . . . . . . . . . . . . LABEL  0x0006E USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:555.1-555.13
ERASE_AUTHENTICATION . . . . . . . . LABEL  0x000DC USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:809.1-809.22
ERASE_COMMAND  . . . . . . . . . . . LABEL  0x0004B USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:479.1-479.15
HEX_BYTE_TO_ASCII  . . . . . . . . . LABEL  0x0012D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1105.1-1105.19
HEX_TO_ASCII . . . . . . . . . . . . LABEL  0x00139 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1122.1-1122.14
ISR  . . . . . . . . . . . . . . . . LABEL  0x003E3 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:2137.1-2137.5
ISR_PRESERVE_S0  . . . . . . . . . . NUMBER 0x00000 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:156.1-156.37
LCD_CLEAR  . . . . . . . . . . . . . LABEL  0x00337 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1848.1-1848.11
LCD_CURSOR . . . . . . . . . . . . . LABEL  0x0033C USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1871.1-1871.12
LCD_DB4  . . . . . . . . . . . . . . NUMBER 0x00010 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:83.1-83.37
LCD_DB5  . . . . . . . . . . . . . . NUMBER 0x00020 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:84.1-84.37
LCD_DB6  . . . . . . . . . . . . . . NUMBER 0x00040 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:85.1-85.37
LCD_DB7  . . . . . . . . . . . . . . NUMBER 0x00080 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:86.1-86.37
LCD_DRIVE  . . . . . . . . . . . . . NUMBER 0x00008 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:82.1-82.37
LCD_E  . . . . . . . . . . . . . . . NUMBER 0x00001 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:79.1-79.37
LCD_INPUT_PORT . . . . . . . . . . . NUMBER 0x00003 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:89.1-89.37
LCD_OUTPUT_PORT  . . . . . . . . . . NUMBER 0x00020 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:78.1-78.37
LCD_PULSE_E  . . . . . . . . . . . . LABEL  0x002E3 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1692.1-1692.13
LCD_READ_DB4 . . . . . . . . . . . . NUMBER 0x00010 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:94.1-94.37
LCD_READ_DB5 . . . . . . . . . . . . NUMBER 0x00020 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:95.1-95.37
LCD_READ_DB6 . . . . . . . . . . . . NUMBER 0x00040 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:96.1-96.37
LCD_READ_DB7 . . . . . . . . . . . . NUMBER 0x00080 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:97.1-97.37
LCD_READ_EQU8  . . . . . . . . . . . LABEL  0x0030D NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:1791.1-1791.15
LCD_READ_SPARE0  . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:90.1-90.37
LCD_READ_SPARE1  . . . . . . . . . . NUMBER 0x00002 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:91.1-91.37
LCD_READ_SPARE2  . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:92.1-92.37
LCD_READ_SPARE3  . . . . . . . . . . NUMBER 0x00008 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:93.1-93.37
LCD_RESET  . . . . . . . . . . . . . LABEL  0x00326 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1831.1-1831.11
LCD_RS . . . . . . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:81.1-81.37
LCD_RW . . . . . . . . . . . . . . . NUMBER 0x00002 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:80.1-80.37
LCD_WRITE_EQU  . . . . . . . . . . . LABEL  0x002FC USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1754.1-1754.15
LCD_WRITE_INST4  . . . . . . . . . . LABEL  0x002E9 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1708.1-1708.17
LCD_WRITE_INST8  . . . . . . . . . . LABEL  0x002ED USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1725.1-1725.17
LINK_FIFO_WRITE_PORT . . . . . . . . NUMBER 0x00004 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:141.1-141.37
MENU . . . . . . . . . . . . . . . . LABEL  0x0003C USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:458.1-458.6
NEXT_AUTH_READ . . . . . . . . . . . LABEL  0x000A6 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:707.1-707.16
NUMBER_CHAR  . . . . . . . . . . . . LABEL  0x0013C USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1125.1-1125.13
PASS_TOKEN . . . . . . . . . . . . . LABEL  0x003F0 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:2153.1-2153.12
RANDOM_VALUE_PORT  . . . . . . . . . NUMBER 0x00004 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:132.1-132.37
READ_AUTHENTICATION  . . . . . . . . LABEL  0x00092 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:687.1-687.21
READ_CHARACTER . . . . . . . . . . . LABEL  0x0011F USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1046.1-1046.16
READ_COMMAND . . . . . . . . . . . . LABEL  0x00046 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:471.1-471.14
READ_FROM_UART . . . . . . . . . . . LABEL  0x0011B USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1042.1-1042.16
READ_SF_SERIAL_NUMBER  . . . . . . . LABEL  0x000F0 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:903.1-903.23
READ_SN_LOOP . . . . . . . . . . . . LABEL  0x000F6 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:909.1-909.14
RX_EQU_PRESENT . . . . . . . . . . . NUMBER 0x00004 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:57.1-57.36
RX_FULL  . . . . . . . . . . . . . . NUMBER 0x00010 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:59.1-59.37
RX_HALF_FULL . . . . . . . . . . . . NUMBER 0x00008 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:58.1-58.37
S0 . . . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    IMPLICIT
S10  . . . . . . . . . . . . . . . . REG.   0x00010 NOT USED CONSTANT    IMPLICIT
S11  . . . . . . . . . . . . . . . . REG.   0x00011 NOT USED CONSTANT    IMPLICIT
S12  . . . . . . . . . . . . . . . . REG.   0x00012 NOT USED CONSTANT    IMPLICIT
S13  . . . . . . . . . . . . . . . . REG.   0x00013 NOT USED CONSTANT    IMPLICIT
S14  . . . . . . . . . . . . . . . . REG.   0x00014 NOT USED CONSTANT    IMPLICIT
S15  . . . . . . . . . . . . . . . . REG.   0x00015 NOT USED CONSTANT    IMPLICIT
S16  . . . . . . . . . . . . . . . . REG.   0x00016 NOT USED CONSTANT    IMPLICIT
S17  . . . . . . . . . . . . . . . . REG.   0x00017 NOT USED CONSTANT    IMPLICIT
S18  . . . . . . . . . . . . . . . . REG.   0x00018 NOT USED CONSTANT    IMPLICIT
S19  . . . . . . . . . . . . . . . . REG.   0x00019 NOT USED CONSTANT    IMPLICIT
S1A  . . . . . . . . . . . . . . . . REG.   0x0001A NOT USED CONSTANT    IMPLICIT
S1B  . . . . . . . . . . . . . . . . REG.   0x0001B NOT USED CONSTANT    IMPLICIT
S1C  . . . . . . . . . . . . . . . . REG.   0x0001C NOT USED CONSTANT    IMPLICIT
S1D  . . . . . . . . . . . . . . . . REG.   0x0001D NOT USED CONSTANT    IMPLICIT
S1E  . . . . . . . . . . . . . . . . REG.   0x0001E NOT USED CONSTANT    IMPLICIT
S1F  . . . . . . . . . . . . . . . . REG.   0x0001F NOT USED CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 USED     CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 USED     CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 USED     CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 USED     CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 USED     CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 USED     CONSTANT    IMPLICIT
S8 . . . . . . . . . . . . . . . . . REG.   0x00008 USED     CONSTANT    IMPLICIT
S9 . . . . . . . . . . . . . . . . . REG.   0x00009 USED     CONSTANT    IMPLICIT
SA . . . . . . . . . . . . . . . . . REG.   0x0000A USED     CONSTANT    IMPLICIT
SB . . . . . . . . . . . . . . . . . REG.   0x0000B USED     CONSTANT    IMPLICIT
SC . . . . . . . . . . . . . . . . . REG.   0x0000C NOT USED CONSTANT    IMPLICIT
SD . . . . . . . . . . . . . . . . . REG.   0x0000D USED     CONSTANT    IMPLICIT
SE . . . . . . . . . . . . . . . . . REG.   0x0000E USED     CONSTANT    IMPLICIT
SECURITY_DISABLE_INTERRUPTS  . . . . NUMBER 0x00001 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:127.1-127.37
SECURITY_DISABLE_OUTPUTS . . . . . . NUMBER 0x00002 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:128.1-128.37
SEND_AUTH  . . . . . . . . . . . . . LABEL  0x0020D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1405.1-1405.11
SEND_AUTHENTICATION  . . . . . . . . LABEL  0x00230 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1452.1-1452.21
SEND_AUTHORIS  . . . . . . . . . . . LABEL  0x00216 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1417.1-1417.15
SEND_AUTHORISATION . . . . . . . . . LABEL  0x00220 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1430.1-1430.20
SEND_AUTHORISE . . . . . . . . . . . LABEL  0x0022C USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1445.1-1445.16
SEND_AUTH_PAGE . . . . . . . . . . . LABEL  0x000AC USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:723.1-723.16
SEND_COMPUTED_CRC  . . . . . . . . . LABEL  0x00250 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1497.1-1497.19
SEND_COPYRIGHT . . . . . . . . . . . LABEL  0x001B2 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1300.1-1300.16
SEND_CR  . . . . . . . . . . . . . . LABEL  0x00152 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1175.1-1175.9
SEND_CRC . . . . . . . . . . . . . . LABEL  0x00247 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1483.1-1483.10
SEND_DASH  . . . . . . . . . . . . . LABEL  0x0015D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1198.1-1198.11
SEND_EQUALS  . . . . . . . . . . . . LABEL  0x00158 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1188.1-1188.13
SEND_ERASE . . . . . . . . . . . . . LABEL  0x00261 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1518.1-1518.12
SEND_ERASE_IN_PROGRESS . . . . . . . LABEL  0x0026D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1534.1-1534.24
SEND_FAILED  . . . . . . . . . . . . LABEL  0x0028D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1574.1-1574.13
SEND_FLASH . . . . . . . . . . . . . LABEL  0x001E5 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1356.1-1356.12
SEND_FLASH_CRC . . . . . . . . . . . LABEL  0x00246 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1478.1-1478.16
SEND_FLASH_SERIAL_NUMBER . . . . . . LABEL  0x001F0 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1372.1-1372.26
SEND_HEX_3BYTES  . . . . . . . . . . LABEL  0x00144 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1145.1-1145.17
SEND_HEX_BYTE  . . . . . . . . . . . LABEL  0x0013E USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1133.1-1133.15
SEND_MENU  . . . . . . . . . . . . . LABEL  0x002BA USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1632.1-1632.11
SEND_OK  . . . . . . . . . . . . . . LABEL  0x00287 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1564.1-1564.9
SEND_PASSED  . . . . . . . . . . . . LABEL  0x0029B USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1592.1-1592.13
SEND_SERIAL_NUMBER . . . . . . . . . LABEL  0x00065 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:545.1-545.20
SEND_SN_LOOP . . . . . . . . . . . . LABEL  0x00067 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:547.1-547.14
SEND_SPACE . . . . . . . . . . . . . LABEL  0x00155 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1181.1-1181.12
SEND_TO_UART . . . . . . . . . . . . LABEL  0x00121 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1060.1-1060.14
SEND_WELCOME . . . . . . . . . . . . LABEL  0x00162 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1207.1-1207.14
SEND_WRITING . . . . . . . . . . . . LABEL  0x002A8 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1610.1-1610.14
SERIAL_NUMBER0 . . . . . . . . . . . NUMBER 0x00010 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:159.1-159.37
SERIAL_NUMBER1 . . . . . . . . . . . NUMBER 0x00011 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:160.1-160.37
SERIAL_NUMBER2 . . . . . . . . . . . NUMBER 0x00012 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:161.1-161.37
SERIAL_NUMBER3 . . . . . . . . . . . NUMBER 0x00013 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:162.1-162.37
SERIAL_NUMBER4 . . . . . . . . . . . NUMBER 0x00014 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:163.1-163.37
SERIAL_NUMBER5 . . . . . . . . . . . NUMBER 0x00015 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:164.1-164.37
SERIAL_NUMBER6 . . . . . . . . . . . NUMBER 0x00016 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:165.1-165.37
SERIAL_NUMBER7 . . . . . . . . . . . NUMBER 0x00017 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:166.1-166.37
SET_LINE2  . . . . . . . . . . . . . LABEL  0x00342 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1877.1-1877.11
SET_SF_READ_ARRAY_MODE . . . . . . . LABEL  0x00113 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:998.1-998.24
SF . . . . . . . . . . . . . . . . . REG.   0x0000F USED     CONSTANT    IMPLICIT
SF_ADDR_HI_PORT  . . . . . . . . . . NUMBER 0x00083 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:112.1-112.37
SF_ADDR_LO_PORT  . . . . . . . . . . NUMBER 0x00081 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:114.1-114.37
SF_ADDR_MI_PORT  . . . . . . . . . . NUMBER 0x00082 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:113.1-113.37
SF_BYTE_READ . . . . . . . . . . . . LABEL  0x000FF USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:941.1-941.14
SF_BYTE_WRITE  . . . . . . . . . . . LABEL  0x00109 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:972.1-972.15
SF_CE  . . . . . . . . . . . . . . . NUMBER 0x00002 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:118.1-118.37
SF_CONTROL_PORT  . . . . . . . . . . NUMBER 0x00040 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:116.1-116.37
SF_EQU_IN_PORT . . . . . . . . . . . NUMBER 0x00002 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:108.1-108.36
SF_EQU_OUT_PORT  . . . . . . . . . . NUMBER 0x00080 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:110.1-110.36
SF_ERASE_BLOCK . . . . . . . . . . . LABEL  0x000E2 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:849.1-849.16
SF_INIT  . . . . . . . . . . . . . . LABEL  0x000DF USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:824.1-824.9
SF_READ  . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:117.1-117.37
SF_SINGLE_BYTE_WRITE . . . . . . . . LABEL  0x000EA USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:878.1-878.22
SF_WE  . . . . . . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:119.1-119.37
SPARE1 . . . . . . . . . . . . . . . NUMBER 0x00020 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:60.1-60.37
SPARE2 . . . . . . . . . . . . . . . NUMBER 0x00040 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:61.1-61.37
STATUS_PORT  . . . . . . . . . . . . NUMBER 0x00000 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:54.1-54.37
STRATAFLASH_STS  . . . . . . . . . . NUMBER 0x00080 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:62.1-62.37
TX_FULL  . . . . . . . . . . . . . . NUMBER 0x00002 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:56.1-56.37
TX_HALF_FULL . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:55.1-55.37
UART_EQU . . . . . . . . . . . . . . REG.   0x0000F USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:148.1-148.34
UART_READ_PORT . . . . . . . . . . . NUMBER 0x00001 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:64.1-64.37
UART_WRITE . . . . . . . . . . . . . LABEL  0x00125 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1064.1-1064.12
UART_WRITE_PORT  . . . . . . . . . . NUMBER 0x00008 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:66.1-66.37
UPPER_CASE . . . . . . . . . . . . . LABEL  0x00127 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1084.1-1084.12
WAIT_1MS . . . . . . . . . . . . . . LABEL  0x00350 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1919.1-1919.10
WAIT_1S  . . . . . . . . . . . . . . LABEL  0x0035A USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1941.1-1941.9
WAIT_1US . . . . . . . . . . . . . . LABEL  0x00347 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1899.1-1899.10
WAIT_20MS  . . . . . . . . . . . . . LABEL  0x00355 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1931.1-1931.11
WAIT_40US  . . . . . . . . . . . . . LABEL  0x0034B USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1908.1-1908.11
WAIT_SF_READY  . . . . . . . . . . . LABEL  0x00116 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:1017.1-1017.15
WARM_START . . . . . . . . . . . . . LABEL  0x00008 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:321.1-321.12
WRITE_AUTH . . . . . . . . . . . . . LABEL  0x000D8 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:795.1-795.12
WRITE_AUTHENTICATION . . . . . . . . LABEL  0x000BC USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:767.1-767.22
_CHARACTER_A . . . . . . . . . . . . NUMBER 0x00041 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:230.1-230.37
_CHARACTER_B . . . . . . . . . . . . NUMBER 0x00042 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:231.1-231.37
_CHARACTER_C . . . . . . . . . . . . NUMBER 0x00043 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:232.1-232.37
_CHARACTER_D . . . . . . . . . . . . NUMBER 0x00044 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:233.1-233.37
_CHARACTER_E . . . . . . . . . . . . NUMBER 0x00045 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:234.1-234.37
_CHARACTER_F . . . . . . . . . . . . NUMBER 0x00046 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:235.1-235.37
_CHARACTER_G . . . . . . . . . . . . NUMBER 0x00047 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:236.1-236.37
_CHARACTER_H . . . . . . . . . . . . NUMBER 0x00048 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:237.1-237.37
_CHARACTER_I . . . . . . . . . . . . NUMBER 0x00049 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:238.1-238.37
_CHARACTER_J . . . . . . . . . . . . NUMBER 0x0004A NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:239.1-239.37
_CHARACTER_K . . . . . . . . . . . . NUMBER 0x0004B USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:240.1-240.37
_CHARACTER_L . . . . . . . . . . . . NUMBER 0x0004C USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:241.1-241.37
_CHARACTER_M . . . . . . . . . . . . NUMBER 0x0004D USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:242.1-242.37
_CHARACTER_N . . . . . . . . . . . . NUMBER 0x0004E USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:243.1-243.37
_CHARACTER_O . . . . . . . . . . . . NUMBER 0x0004F USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:244.1-244.37
_CHARACTER_P . . . . . . . . . . . . NUMBER 0x00050 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:245.1-245.37
_CHARACTER_Q . . . . . . . . . . . . NUMBER 0x00051 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:246.1-246.37
_CHARACTER_R . . . . . . . . . . . . NUMBER 0x00052 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:247.1-247.37
_CHARACTER_S . . . . . . . . . . . . NUMBER 0x00053 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:248.1-248.37
_CHARACTER_T . . . . . . . . . . . . NUMBER 0x00054 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:249.1-249.37
_CHARACTER_U . . . . . . . . . . . . NUMBER 0x00055 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:250.1-250.37
_CHARACTER_V . . . . . . . . . . . . NUMBER 0x00056 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:251.1-251.37
_CHARACTER_W . . . . . . . . . . . . NUMBER 0x00057 USED     CONSTANT    2030_example3.ind_spaces.short_inst.asm:252.1-252.37
_CHARACTER_X . . . . . . . . . . . . NUMBER 0x00058 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:253.1-253.37
_CHARACTER_Y . . . . . . . . . . . . NUMBER 0x00059 NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:254.1-254.37
_CHARACTER_Z . . . . . . . . . . . . NUMBER 0x0005A NOT USED CONSTANT    2030_example3.ind_spaces.short_inst.asm:255.1-255.37
