ALL_LED_FADE . . . . . . . . . . . . LABEL  0x000E4 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:468.1-468.14
ALL_LED_FADE_LOOP  . . . . . . . . . LABEL  0x000E5 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:469.1-469.19
AUTHENTICATION_CHECK . . . . . . . . LABEL  0x000B6 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:407.1-407.22
CHARACTER_A  . . . . . . . . . . . . NUMBER 0x00041 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:1.1-1.23
CHARACTER_F  . . . . . . . . . . . . NUMBER 0x00046 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:2.1-2.23
CHARACTER_I  . . . . . . . . . . . . NUMBER 0x00049 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:3.1-3.23
CHARACTER_L  . . . . . . . . . . . . NUMBER 0x0004C USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:4.1-4.23
CHARACTER_P  . . . . . . . . . . . . NUMBER 0x00050 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:5.1-5.23
CHARACTER_S  . . . . . . . . . . . . NUMBER 0x00053 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:6.1-6.23
CLEAR_LOOP . . . . . . . . . . . . . LABEL  0x00002 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:129.1-129.12
COLD_START . . . . . . . . . . . . . LABEL  0x00000 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:127.1-127.12
DECAY_LEDS . . . . . . . . . . . . . LABEL  0x000EA USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:474.1-474.12
DELAY_S0_LOOP  . . . . . . . . . . . LABEL  0x00018 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:183.1-183.15
DELAY_S1_LOOP  . . . . . . . . . . . LABEL  0x00017 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:182.1-182.15
DELAY_S2_LOOP  . . . . . . . . . . . LABEL  0x00016 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:181.1-181.15
ENABLE_INT . . . . . . . . . . . . . LABEL  0x00007 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:135.1-135.12
FAILED_LED_SEQUENCE  . . . . . . . . LABEL  0x000E2 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:466.1-466.21
FAIL_CONFIRM . . . . . . . . . . . . LABEL  0x000CB USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:435.1-435.14
GO_DOWN  . . . . . . . . . . . . . . LABEL  0x000B1 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:377.1-377.9
GO_DOWN_LOOP . . . . . . . . . . . . LABEL  0x000B2 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:378.1-378.14
GO_UP_LOOP . . . . . . . . . . . . . LABEL  0x000AC USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:372.1-372.12
INC_LED0 . . . . . . . . . . . . . . LABEL  0x00024 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:198.1-198.10
INC_LED1 . . . . . . . . . . . . . . LABEL  0x00037 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:218.1-218.10
INC_LED2 . . . . . . . . . . . . . . LABEL  0x00048 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:236.1-236.10
INC_LED3 . . . . . . . . . . . . . . LABEL  0x00059 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:255.1-255.10
INC_LED4 . . . . . . . . . . . . . . LABEL  0x0006A USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:273.1-273.10
INC_LED5 . . . . . . . . . . . . . . LABEL  0x0007B USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:291.1-291.10
INC_LED6 . . . . . . . . . . . . . . LABEL  0x00091 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:314.1-314.10
INC_LED7 . . . . . . . . . . . . . . LABEL  0x0009F USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:329.1-329.10
ISR  . . . . . . . . . . . . . . . . LABEL  0x000FE USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:530.1-530.5
ISR_PRESERVE_S0  . . . . . . . . . . NUMBER 0x0000D USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:94.1-94.27
ISR_PRESERVE_S1  . . . . . . . . . . NUMBER 0x0000E USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:95.1-95.27
ISR_PRESERVE_S2  . . . . . . . . . . NUMBER 0x0000F USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:96.1-96.27
LED0 . . . . . . . . . . . . . . . . NUMBER 0x00001 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:42.1-42.17
LED0_SEQUENCE  . . . . . . . . . . . NUMBER 0x00010 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:99.1-99.25
LED1 . . . . . . . . . . . . . . . . NUMBER 0x00002 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:43.1-43.17
LED1_SEQUENCE  . . . . . . . . . . . NUMBER 0x00011 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:100.1-100.25
LED2 . . . . . . . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:44.1-44.17
LED2_SEQUENCE  . . . . . . . . . . . NUMBER 0x00012 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:101.1-101.25
LED3 . . . . . . . . . . . . . . . . NUMBER 0x00008 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:45.1-45.17
LED3_SEQUENCE  . . . . . . . . . . . NUMBER 0x00013 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:102.1-102.25
LED4 . . . . . . . . . . . . . . . . NUMBER 0x00010 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:46.1-46.17
LED4_SEQUENCE  . . . . . . . . . . . NUMBER 0x00014 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:103.1-103.25
LED5 . . . . . . . . . . . . . . . . NUMBER 0x00020 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:47.1-47.17
LED5_SEQUENCE  . . . . . . . . . . . NUMBER 0x00015 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:104.1-104.25
LED6 . . . . . . . . . . . . . . . . NUMBER 0x00040 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:48.1-48.17
LED6_SEQUENCE  . . . . . . . . . . . NUMBER 0x00016 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:105.1-105.25
LED7 . . . . . . . . . . . . . . . . NUMBER 0x00080 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:49.1-49.17
LED7_SEQUENCE  . . . . . . . . . . . NUMBER 0x00017 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:106.1-106.25
LED_PORT . . . . . . . . . . . . . . NUMBER 0x00080 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:41.1-41.20
LED_READ_PORT  . . . . . . . . . . . NUMBER 0x00000 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:51.1-51.25
LED_TO_DUTY  . . . . . . . . . . . . LABEL  0x000A8 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:368.1-368.13
LINK_FIFO_CONTROL_PORT . . . . . . . NUMBER 0x00020 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:62.1-62.33
LINK_FIFO_DATA_PRESENT . . . . . . . NUMBER 0x00001 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:66.1-66.33
LINK_FIFO_FULL . . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:68.1-68.26
LINK_FIFO_HALF_FULL  . . . . . . . . NUMBER 0x00002 NOT USED CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:67.1-67.30
LINK_FIFO_READ_PORT  . . . . . . . . NUMBER 0x00002 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:70.1-70.30
LINK_FIFO_RESET  . . . . . . . . . . NUMBER 0x00001 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:63.1-63.27
LINK_FIFO_STATUS_PORT  . . . . . . . NUMBER 0x00001 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:65.1-65.32
NORMAL_LED1  . . . . . . . . . . . . LABEL  0x00031 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:212.1-212.13
NORMAL_LED6  . . . . . . . . . . . . LABEL  0x0008B USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:308.1-308.13
NORMAL_LED_SEQUENCE  . . . . . . . . LABEL  0x00015 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:180.1-180.21
PWM_CHANNEL0 . . . . . . . . . . . . NUMBER 0x00001 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:86.1-86.24
PWM_CHANNEL1 . . . . . . . . . . . . NUMBER 0x00002 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:87.1-87.24
PWM_CHANNEL2 . . . . . . . . . . . . NUMBER 0x00003 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:88.1-88.24
PWM_CHANNEL3 . . . . . . . . . . . . NUMBER 0x00004 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:89.1-89.24
PWM_CHANNEL4 . . . . . . . . . . . . NUMBER 0x00005 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:90.1-90.24
PWM_CHANNEL5 . . . . . . . . . . . . NUMBER 0x00006 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:91.1-91.24
PWM_CHANNEL6 . . . . . . . . . . . . NUMBER 0x00007 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:92.1-92.24
PWM_CHANNEL7 . . . . . . . . . . . . NUMBER 0x00008 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:93.1-93.24
PWM_DUTY_COUNTER . . . . . . . . . . NUMBER 0x00000 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:85.1-85.27
READ_LINK_FIFO . . . . . . . . . . . LABEL  0x000F9 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:500.1-500.16
REQUEST_DELAY  . . . . . . . . . . . LABEL  0x000CC USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:436.1-436.15
S0 . . . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 USED     CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 USED     CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 USED     CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 NOT USED CONSTANT    IMPLICIT
S8 . . . . . . . . . . . . . . . . . REG.   0x00008 NOT USED CONSTANT    IMPLICIT
S9 . . . . . . . . . . . . . . . . . REG.   0x00009 NOT USED CONSTANT    IMPLICIT
SA . . . . . . . . . . . . . . . . . REG.   0x0000A NOT USED CONSTANT    IMPLICIT
SB . . . . . . . . . . . . . . . . . REG.   0x0000B NOT USED CONSTANT    IMPLICIT
SC . . . . . . . . . . . . . . . . . REG.   0x0000C NOT USED CONSTANT    IMPLICIT
SD . . . . . . . . . . . . . . . . . REG.   0x0000D NOT USED CONSTANT    IMPLICIT
SE . . . . . . . . . . . . . . . . . REG.   0x0000E NOT USED CONSTANT    IMPLICIT
SECURITY_INTERRUPT . . . . . . . . . NUMBER 0x00001 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:55.1-55.29
SECURITY_REQUEST_PORT  . . . . . . . NUMBER 0x00040 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:54.1-54.32
SF . . . . . . . . . . . . . . . . . REG.   0x0000F USED     CONSTANT    IMPLICIT
STOP_COMPLETELY  . . . . . . . . . . LABEL  0x000F8 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:489.1-489.17
TEST_LED0_START  . . . . . . . . . . LABEL  0x00026 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:200.1-200.17
TEST_LED1_START  . . . . . . . . . . LABEL  0x00039 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:220.1-220.17
TEST_LED2_START  . . . . . . . . . . LABEL  0x0004A USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:238.1-238.17
TEST_LED3_START  . . . . . . . . . . LABEL  0x0005B USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:257.1-257.17
TEST_LED4_START  . . . . . . . . . . LABEL  0x0006C USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:275.1-275.17
TEST_LED5_START  . . . . . . . . . . LABEL  0x0007D USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:293.1-293.17
TEST_LED6_START  . . . . . . . . . . LABEL  0x00093 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:316.1-316.17
TEST_LED7_START  . . . . . . . . . . LABEL  0x000A1 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:331.1-331.17
UPDATE_LED0  . . . . . . . . . . . . LABEL  0x00029 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:203.1-203.13
UPDATE_LED1  . . . . . . . . . . . . LABEL  0x0003F USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:226.1-226.13
UPDATE_LED2  . . . . . . . . . . . . LABEL  0x00050 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:244.1-244.13
UPDATE_LED3  . . . . . . . . . . . . LABEL  0x00061 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:263.1-263.13
UPDATE_LED4  . . . . . . . . . . . . LABEL  0x00072 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:281.1-281.13
UPDATE_LED5  . . . . . . . . . . . . LABEL  0x00083 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:299.1-299.13
UPDATE_LED6  . . . . . . . . . . . . LABEL  0x00096 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:319.1-319.13
UPDATE_LED7  . . . . . . . . . . . . LABEL  0x000A4 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:334.1-334.13
WAIT_S1  . . . . . . . . . . . . . . LABEL  0x000EB USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:475.1-475.9
WAIT_S2  . . . . . . . . . . . . . . LABEL  0x000EC USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:476.1-476.9
WAIT_S3  . . . . . . . . . . . . . . LABEL  0x000ED USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:477.1-477.9
WARM_START . . . . . . . . . . . . . LABEL  0x00013 USED     CONSTANT    3029_s3kit_example2.ind_tabs.full_inst.asm:177.1-177.12
