                   1     device kcpsm6
                   2
                   3
  00006            4     ss3      EQU     0x06
  00006            5     B       SET     6
                   6
                   7
                   8
  00000            9     Start:
                  10             SKIP    6
006 00120         11             LOAD    s1,s2
007 00120         12             LOAD    s1,s2
008 00120         13             LOAD    s1,s2
009 00120         14             LOAD    s1,s2
00A 00120         15             LOAD    s1,s2
00B 00120         16             LOAD    s1,s2
                  17
                  18             #WHILE   B
                  19                     SR0     s0
                  20                     B       SET     B - 1
                  21             #ENDW
00C 1400E         22 +1                  SR0     s0
  00005           23 +1                  B       SET     B - 1
00D 1400E         24 +1                  SR0     s0
  00004           25 +1                  B       SET     B - 1
00E 1400E         26 +1                  SR0     s0
  00003           27 +1                  B       SET     B - 1
00F 1400E         28 +1                  SR0     s0
  00002           29 +1                  B       SET     B - 1
010 1400E         30 +1                  SR0     s0
  00001           31 +1                  B       SET     B - 1
011 1400E         32 +1                  SR0     s0
  00000           33 +1                  B       SET     B - 1
                  34
                  35             REPT    8
                  36                     SL0     sC
                  37             ENDR
012 14C06         38 +1                  SL0     sC
013 14C06         39 +1                  SL0     sC
014 14C06         40 +1                  SL0     sC
015 14C06         41 +1                  SL0     sC
016 14C06         42 +1                  SL0     sC
017 14C06         43 +1                  SL0     sC
018 14C06         44 +1                  SL0     sC
019 14C06         45 +1                  SL0     sC
                  46
                  47             END
                  48
                  49
