MT_WARNING: 6019_demo_2.asm:28.38-28.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 6019_demo_2.asm:30.38-30.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 6019_demo_2.asm:32.38-32.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 6019_demo_2.asm:39.38-39.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 6019_demo_2.asm:41.38-41.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
MT_WARNING: 6019_demo_2.asm:43.38-43.39: Warning: instruction `SUB sX, sY' requires operand #2 to be of type(s): register; while the given operand is of type: number.
