ABORT_ERASE  . . . . . . . . . . . . LABEL  0x0003E USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:286.1-286.13
ADDR_OUT_OF_SEQUENCE . . . . . . . . LABEL  0x00086 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:404.1-404.22
ASCII_BYTE_TO_HEX  . . . . . . . . . LABEL  0x00204 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1219.1-1219.19
ASCII_LETTER . . . . . . . . . . . . LABEL  0x0021B USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1250.1-1250.14
ASCII_TO_HEX . . . . . . . . . . . . LABEL  0x00211 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1240.1-1240.14
BULK_ERASE_SPI . . . . . . . . . . . LABEL  0x00173 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:872.1-872.16
BULK_ERASE_WAIT  . . . . . . . . . . LABEL  0x0017D USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:882.1-882.17
BYTE_PROGRAMMED  . . . . . . . . . . LABEL  0x0009A USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:424.1-424.17
CHARACTER_0  . . . . . . . . . . . . NUMBER 0x00030 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:137.1-137.45
CHARACTER_1  . . . . . . . . . . . . NUMBER 0x00031 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:138.1-138.45
CHARACTER_2  . . . . . . . . . . . . NUMBER 0x00032 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:139.1-139.45
CHARACTER_3  . . . . . . . . . . . . NUMBER 0x00033 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:140.1-140.45
CHARACTER_4  . . . . . . . . . . . . NUMBER 0x00034 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:141.1-141.45
CHARACTER_5  . . . . . . . . . . . . NUMBER 0x00035 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:142.1-142.45
CHARACTER_6  . . . . . . . . . . . . NUMBER 0x00036 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:143.1-143.45
CHARACTER_7  . . . . . . . . . . . . NUMBER 0x00037 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:144.1-144.45
CHARACTER_8  . . . . . . . . . . . . NUMBER 0x00038 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:145.1-145.45
CHARACTER_9  . . . . . . . . . . . . NUMBER 0x00039 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:146.1-146.45
CHARACTER_A  . . . . . . . . . . . . NUMBER 0x00061 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:85.1-85.45
CHARACTER_B  . . . . . . . . . . . . NUMBER 0x00062 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:86.1-86.45
CHARACTER_BS . . . . . . . . . . . . NUMBER 0x00008 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:165.1-165.45
CHARACTER_C  . . . . . . . . . . . . NUMBER 0x00063 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:87.1-87.45
CHARACTER_CLOSE  . . . . . . . . . . NUMBER 0x00029 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:156.1-156.45
CHARACTER_COLON  . . . . . . . . . . NUMBER 0x0003A USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:147.1-147.45
CHARACTER_COMMA  . . . . . . . . . . NUMBER 0x0002C NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:152.1-152.45
CHARACTER_CR . . . . . . . . . . . . NUMBER 0x0000D USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:160.1-160.45
CHARACTER_D  . . . . . . . . . . . . NUMBER 0x00064 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:88.1-88.45
CHARACTER_DIVIDE . . . . . . . . . . NUMBER 0x0002F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:157.1-157.45
CHARACTER_DOLLAR . . . . . . . . . . NUMBER 0x00024 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:163.1-163.45
CHARACTER_E  . . . . . . . . . . . . NUMBER 0x00065 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:89.1-89.45
CHARACTER_EQUALS . . . . . . . . . . NUMBER 0x0003D USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:158.1-158.45
CHARACTER_EXCLAIM  . . . . . . . . . NUMBER 0x00021 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:164.1-164.45
CHARACTER_F  . . . . . . . . . . . . NUMBER 0x00066 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:90.1-90.45
CHARACTER_FULLSTOP . . . . . . . . . NUMBER 0x0002E USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:148.1-148.45
CHARACTER_G  . . . . . . . . . . . . NUMBER 0x00067 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:91.1-91.45
CHARACTER_GREATER_THAN . . . . . . . NUMBER 0x0003E USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:154.1-154.45
CHARACTER_H  . . . . . . . . . . . . NUMBER 0x00068 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:92.1-92.45
CHARACTER_I  . . . . . . . . . . . . NUMBER 0x00069 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:93.1-93.45
CHARACTER_J  . . . . . . . . . . . . NUMBER 0x0006A NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:94.1-94.45
CHARACTER_K  . . . . . . . . . . . . NUMBER 0x0006B NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:95.1-95.45
CHARACTER_L  . . . . . . . . . . . . NUMBER 0x0006C USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:96.1-96.45
CHARACTER_LESS_THAN  . . . . . . . . NUMBER 0x0003C NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:153.1-153.45
CHARACTER_LF . . . . . . . . . . . . NUMBER 0x0000A USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:161.1-161.45
CHARACTER_M  . . . . . . . . . . . . NUMBER 0x0006D USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:97.1-97.45
CHARACTER_MINUS  . . . . . . . . . . NUMBER 0x0002D USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:150.1-150.45
CHARACTER_N  . . . . . . . . . . . . NUMBER 0x0006E USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:98.1-98.45
CHARACTER_O  . . . . . . . . . . . . NUMBER 0x0006F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:99.1-99.45
CHARACTER_OPEN . . . . . . . . . . . NUMBER 0x00028 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:155.1-155.45
CHARACTER_P  . . . . . . . . . . . . NUMBER 0x00070 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:100.1-100.45
CHARACTER_PLUS . . . . . . . . . . . NUMBER 0x0002B NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:151.1-151.45
CHARACTER_Q  . . . . . . . . . . . . NUMBER 0x00071 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:101.1-101.45
CHARACTER_QUESTION . . . . . . . . . NUMBER 0x0003F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:162.1-162.45
CHARACTER_R  . . . . . . . . . . . . NUMBER 0x00072 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:102.1-102.45
CHARACTER_S  . . . . . . . . . . . . NUMBER 0x00073 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:103.1-103.45
CHARACTER_SEMI_COLON . . . . . . . . NUMBER 0x0003B NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:149.1-149.45
CHARACTER_SPACE  . . . . . . . . . . NUMBER 0x00020 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:159.1-159.45
CHARACTER_T  . . . . . . . . . . . . NUMBER 0x00074 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:104.1-104.45
CHARACTER_U  . . . . . . . . . . . . NUMBER 0x00075 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:105.1-105.45
CHARACTER_V  . . . . . . . . . . . . NUMBER 0x00076 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:106.1-106.45
CHARACTER_W  . . . . . . . . . . . . NUMBER 0x00077 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:107.1-107.45
CHARACTER_X  . . . . . . . . . . . . NUMBER 0x00078 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:108.1-108.45
CHARACTER_XOFF . . . . . . . . . . . NUMBER 0x00013 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:167.1-167.45
CHARACTER_XON  . . . . . . . . . . . NUMBER 0x00011 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:166.1-166.45
CHARACTER_Y  . . . . . . . . . . . . NUMBER 0x00079 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:109.1-109.45
CHARACTER_Z  . . . . . . . . . . . . NUMBER 0x0007A USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:110.1-110.45
CLOSE_PROG_PAGE_SPI  . . . . . . . . LABEL  0x0018F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:923.1-923.21
COLD_START . . . . . . . . . . . . . LABEL  0x00000 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:201.1-201.12
DECIMAL_TO_ASCII . . . . . . . . . . LABEL  0x001C7 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1078.1-1078.18
DELAY_1MS  . . . . . . . . . . . . . LABEL  0x001A0 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:968.1-968.11
DELAY_1S . . . . . . . . . . . . . . LABEL  0x001AA USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:990.1-990.10
DELAY_1US  . . . . . . . . . . . . . LABEL  0x00197 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:948.1-948.11
DELAY_1US_CONSTANT . . . . . . . . . NUMBER 0x0000B USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:77.1-77.45
DELAY_20MS . . . . . . . . . . . . . LABEL  0x001A5 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:980.1-980.12
DELAY_40US . . . . . . . . . . . . . LABEL  0x0019B USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:957.1-957.12
END_PROGRAM_MCS  . . . . . . . . . . LABEL  0x000A5 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:435.1-435.17
ERASE_COMMAND  . . . . . . . . . . . LABEL  0x00033 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:274.1-274.15
ERASE_SPI_SECTOR . . . . . . . . . . LABEL  0x0015F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:843.1-843.18
ERASE_TEST_SECTOR  . . . . . . . . . LABEL  0x000F1 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:578.1-578.19
HEX_BYTE_TO_ASCII  . . . . . . . . . LABEL  0x001E6 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1159.1-1159.19
HEX_TO_ASCII . . . . . . . . . . . . LABEL  0x001F2 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1176.1-1176.14
ID_COMMAND . . . . . . . . . . . . . LABEL  0x00022 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:252.1-252.12
ISR  . . . . . . . . . . . . . . . . LABEL  0x003F5 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1658.1-1658.5
ISR_PRESERVE_S0  . . . . . . . . . . NUMBER 0x00000 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:173.1-173.45
ISR_SEND_CHARACTER . . . . . . . . . LABEL  0x003FC USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1665.1-1665.20
ISR_SEND_XON . . . . . . . . . . . . LABEL  0x003FB USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1664.1-1664.14
LINE_START . . . . . . . . . . . . . NUMBER 0x0002B USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:195.1-195.45
MCS_ADDRESS  . . . . . . . . . . . . LABEL  0x000B9 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:492.1-492.13
MCS_ADDRESS_BOUNDARY . . . . . . . . LABEL  0x000A1 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:431.1-431.22
MEMORY_BLANK_FAIL  . . . . . . . . . LABEL  0x000FF USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:592.1-592.19
MEMORY_BLANK_RESULT  . . . . . . . . LABEL  0x00100 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:593.1-593.21
MEMORY_COMMS_TEST  . . . . . . . . . LABEL  0x00102 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:609.1-609.19
MEMORY_TEST  . . . . . . . . . . . . LABEL  0x000DB NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:550.1-550.13
MEMORY_VERIFY_FAIL . . . . . . . . . LABEL  0x000EE USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:572.1-572.20
MEMORY_VERIFY_RESULT . . . . . . . . LABEL  0x000EF USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:573.1-573.22
NEW_LOW_ADDRESS  . . . . . . . . . . LABEL  0x000C4 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:503.1-503.17
NEXT_PROG_LINE . . . . . . . . . . . LABEL  0x00070 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:379.1-379.16
NEXT_SPI_FLASH_BIT . . . . . . . . . LABEL  0x00114 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:713.1-713.20
NUMBER_CHAR  . . . . . . . . . . . . LABEL  0x001F5 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1179.1-1179.13
OBTAIN_8BITS . . . . . . . . . . . . LABEL  0x00069 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:349.1-349.14
OPEN_PROG_PAGE_SPI . . . . . . . . . LABEL  0x00181 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:900.1-900.20
PAGE_ADDRESS_H . . . . . . . . . . . NUMBER 0x00001 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:175.1-175.45
PAGE_ADDRESS_L . . . . . . . . . . . NUMBER 0x00003 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:177.1-177.45
PAGE_ADDRESS_M . . . . . . . . . . . NUMBER 0x00002 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:176.1-176.45
PAGE_IS_OPEN . . . . . . . . . . . . LABEL  0x0008C USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:410.1-410.14
PAGE_PROG_WAIT . . . . . . . . . . . LABEL  0x00193 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:927.1-927.16
PATTERN_LOOP . . . . . . . . . . . . LABEL  0x000DF USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:554.1-554.14
PROGRAM_BYTE . . . . . . . . . . . . LABEL  0x00088 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:406.1-406.14
PROGRAM_COMMAND  . . . . . . . . . . LABEL  0x00054 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:322.1-322.17
PROGRAM_MCS  . . . . . . . . . . . . LABEL  0x0006F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:378.1-378.13
PROMPT . . . . . . . . . . . . . . . LABEL  0x00006 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:212.1-212.8
READ_CHARACTER . . . . . . . . . . . LABEL  0x001B4 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1031.1-1031.16
READ_COMMAND . . . . . . . . . . . . LABEL  0x00059 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:333.1-333.14
READ_FROM_UART . . . . . . . . . . . LABEL  0x001AF USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1026.1-1026.16
READ_MCS_BYTE  . . . . . . . . . . . LABEL  0x000AD USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:461.1-461.15
READ_MCS_LINE  . . . . . . . . . . . LABEL  0x000A9 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:457.1-457.15
READ_SPI_BYTE  . . . . . . . . . . . LABEL  0x0014E USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:816.1-816.15
READ_SPI_FLASH_ID  . . . . . . . . . LABEL  0x0013E USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:793.1-793.19
READ_SPI_FLASH_STATUS  . . . . . . . LABEL  0x0011F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:742.1-742.23
READ_UPPER_CASE  . . . . . . . . . . LABEL  0x0001D USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:237.1-237.17
READ_XON . . . . . . . . . . . . . . LABEL  0x001BD USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1040.1-1040.10
RESET_SPI_FLASH_WREN . . . . . . . . LABEL  0x00134 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:773.1-773.22
RX_DATA_PRESENT  . . . . . . . . . . NUMBER 0x00008 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:29.1-29.45
RX_FULL  . . . . . . . . . . . . . . NUMBER 0x00020 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:31.1-31.45
RX_HALF_FULL . . . . . . . . . . . . NUMBER 0x00010 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:30.1-30.45
S0 . . . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 USED     CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 USED     CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 USED     CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 USED     CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 USED     CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 USED     CONSTANT    IMPLICIT
S8 . . . . . . . . . . . . . . . . . REG.   0x00008 USED     CONSTANT    IMPLICIT
S9 . . . . . . . . . . . . . . . . . REG.   0x00009 USED     CONSTANT    IMPLICIT
SA . . . . . . . . . . . . . . . . . REG.   0x0000A USED     CONSTANT    IMPLICIT
SB . . . . . . . . . . . . . . . . . REG.   0x0000B USED     CONSTANT    IMPLICIT
SC . . . . . . . . . . . . . . . . . REG.   0x0000C USED     CONSTANT    IMPLICIT
SD . . . . . . . . . . . . . . . . . REG.   0x0000D USED     CONSTANT    IMPLICIT
SE . . . . . . . . . . . . . . . . . REG.   0x0000E USED     CONSTANT    IMPLICIT
SECTOR_ERASE_COMMAND . . . . . . . . LABEL  0x00040 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:296.1-296.22
SECTOR_ERASE_WAIT  . . . . . . . . . LABEL  0x0016F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:859.1-859.19
SEND_ABORT . . . . . . . . . . . . . LABEL  0x0034A USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1607.1-1607.12
SEND_CONFIRM . . . . . . . . . . . . LABEL  0x0032D USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1574.1-1574.14
SEND_CR  . . . . . . . . . . . . . . LABEL  0x0021D USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1257.1-1257.9
SEND_ERASE . . . . . . . . . . . . . LABEL  0x002AA USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1423.1-1423.12
SEND_ERASE_IN_PROGRESS . . . . . . . LABEL  0x00293 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1396.1-1396.24
SEND_HEX_3BYTES  . . . . . . . . . . LABEL  0x001FD USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1200.1-1200.17
SEND_HEX_BYTE  . . . . . . . . . . . LABEL  0x001F7 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1187.1-1187.15
SEND_ID  . . . . . . . . . . . . . . LABEL  0x00328 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1565.1-1565.9
SEND_MCS_FILE  . . . . . . . . . . . LABEL  0x00281 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1374.1-1374.15
SEND_MENU  . . . . . . . . . . . . . LABEL  0x002BD USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1451.1-1451.11
SEND_OK  . . . . . . . . . . . . . . LABEL  0x002B6 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1439.1-1439.9
SEND_PAGE  . . . . . . . . . . . . . LABEL  0x0031F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1553.1-1553.11
SEND_PAGE_ADDRESS  . . . . . . . . . LABEL  0x00357 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1623.1-1623.19
SEND_SPACE . . . . . . . . . . . . . LABEL  0x00220 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1263.1-1263.12
SEND_SPI_BYTE  . . . . . . . . . . . LABEL  0x000CE USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:523.1-523.15
SEND_SPI_LINE  . . . . . . . . . . . LABEL  0x000CA USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:519.1-519.15
SEND_SPI_PAGE  . . . . . . . . . . . LABEL  0x000C9 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:518.1-518.15
SEND_TO_UART . . . . . . . . . . . . LABEL  0x001C1 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1059.1-1059.14
SEND_WAITING_MCS_FILE  . . . . . . . LABEL  0x0026C USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1353.1-1353.23
SEND_WELCOME . . . . . . . . . . . . LABEL  0x00223 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1275.1-1275.14
SET_SPI_FLASH_WREN . . . . . . . . . LABEL  0x0012A USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:758.1-758.20
SF . . . . . . . . . . . . . . . . . REG.   0x0000F USED     CONSTANT    IMPLICIT
SPI_ADC_CONV . . . . . . . . . . . . NUMBER 0x00010 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:43.1-43.45
SPI_AMP_CS . . . . . . . . . . . . . NUMBER 0x00008 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:42.1-42.45
SPI_AMP_SDI  . . . . . . . . . . . . NUMBER 0x00040 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:53.1-53.45
SPI_AMP_SHDN . . . . . . . . . . . . NUMBER 0x00040 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:45.1-45.45
SPI_CONTROL_PORT . . . . . . . . . . NUMBER 0x00008 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:38.1-38.45
SPI_CONTROL_STATUS . . . . . . . . . NUMBER 0x00004 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:179.1-179.45
SPI_DAC_CLR  . . . . . . . . . . . . NUMBER 0x00080 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:46.1-46.45
SPI_DAC_CS . . . . . . . . . . . . . NUMBER 0x00020 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:44.1-44.45
SPI_FLASH_ID_FAIL  . . . . . . . . . LABEL  0x0010B USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:618.1-618.19
SPI_FLASH_ID_RESULT  . . . . . . . . LABEL  0x0010C USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:619.1-619.21
SPI_FLASH_TX_RX  . . . . . . . . . . LABEL  0x00112 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:711.1-711.17
SPI_INIT . . . . . . . . . . . . . . LABEL  0x0010E USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:685.1-685.10
SPI_INPUT_PORT . . . . . . . . . . . NUMBER 0x00002 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:51.1-51.45
SPI_OUTPUT_PORT  . . . . . . . . . . NUMBER 0x00004 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:48.1-48.45
SPI_ROM_CS . . . . . . . . . . . . . NUMBER 0x00002 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:40.1-40.45
SPI_SCK  . . . . . . . . . . . . . . NUMBER 0x00001 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:39.1-39.45
SPI_SDI  . . . . . . . . . . . . . . NUMBER 0x00080 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:52.1-52.45
SPI_SDO  . . . . . . . . . . . . . . NUMBER 0x00080 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:49.1-49.45
SPI_SPARE_CONTROL  . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:41.1-41.45
STATUS_PORT  . . . . . . . . . . . . NUMBER 0x00000 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:25.1-25.45
SWAP_BITS  . . . . . . . . . . . . . LABEL  0x0008E USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:412.1-412.11
TEST_FOR_TEN . . . . . . . . . . . . LABEL  0x001C8 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1079.1-1079.14
TX_DATA_PRESENT  . . . . . . . . . . NUMBER 0x00001 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:26.1-26.45
TX_FULL  . . . . . . . . . . . . . . NUMBER 0x00004 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:28.1-28.45
TX_HALF_FULL . . . . . . . . . . . . NUMBER 0x00002 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:27.1-27.45
UART_DATA  . . . . . . . . . . . . . REG.   0x0000F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:60.1-60.43
UART_READ_PORT . . . . . . . . . . . NUMBER 0x00001 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:33.1-33.45
UART_WRITE . . . . . . . . . . . . . LABEL  0x001C5 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1063.1-1063.12
UART_WRITE_PORT  . . . . . . . . . . NUMBER 0x00010 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:35.1-35.45
UPPER_CASE . . . . . . . . . . . . . LABEL  0x001CE USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1097.1-1097.12
VERIFY_BLANK_PAGE  . . . . . . . . . LABEL  0x000F9 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:586.1-586.19
VERIFY_TEST_PAGE . . . . . . . . . . LABEL  0x000E8 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:566.1-566.18
WAIT_1MS . . . . . . . . . . . . . . LABEL  0x001A1 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:969.1-969.10
WAIT_1S  . . . . . . . . . . . . . . LABEL  0x001AB USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:991.1-991.9
WAIT_1US . . . . . . . . . . . . . . LABEL  0x00198 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:949.1-949.10
WAIT_20MS  . . . . . . . . . . . . . LABEL  0x001A6 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:981.1-981.11
WAIT_40US  . . . . . . . . . . . . . LABEL  0x0019C USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:958.1-958.11
WAIT_MCS_LINE_START  . . . . . . . . LABEL  0x000AA USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:458.1-458.21
WAIT_RX_CHARACTER  . . . . . . . . . LABEL  0x001B0 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1027.1-1027.19
WAIT_XON . . . . . . . . . . . . . . LABEL  0x001B9 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1036.1-1036.10
WARM_START . . . . . . . . . . . . . LABEL  0x00005 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:211.1-211.12
WELCOME_START  . . . . . . . . . . . LABEL  0x00003 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:204.1-204.15
_1CHAR_TO_VALUE  . . . . . . . . . . LABEL  0x001D4 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1114.1-1114.17
_2CHAR_TO_VALUE  . . . . . . . . . . LABEL  0x001D8 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:1130.1-1130.17
_CHARACTER_A . . . . . . . . . . . . NUMBER 0x00041 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:111.1-111.45
_CHARACTER_B . . . . . . . . . . . . NUMBER 0x00042 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:112.1-112.45
_CHARACTER_C . . . . . . . . . . . . NUMBER 0x00043 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:113.1-113.45
_CHARACTER_D . . . . . . . . . . . . NUMBER 0x00044 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:114.1-114.45
_CHARACTER_E . . . . . . . . . . . . NUMBER 0x00045 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:115.1-115.45
_CHARACTER_F . . . . . . . . . . . . NUMBER 0x00046 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:116.1-116.45
_CHARACTER_G . . . . . . . . . . . . NUMBER 0x00047 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:117.1-117.45
_CHARACTER_H . . . . . . . . . . . . NUMBER 0x00048 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:118.1-118.45
_CHARACTER_I . . . . . . . . . . . . NUMBER 0x00049 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:119.1-119.45
_CHARACTER_J . . . . . . . . . . . . NUMBER 0x0004A NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:120.1-120.45
_CHARACTER_K . . . . . . . . . . . . NUMBER 0x0004B USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:121.1-121.45
_CHARACTER_L . . . . . . . . . . . . NUMBER 0x0004C USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:122.1-122.45
_CHARACTER_M . . . . . . . . . . . . NUMBER 0x0004D USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:123.1-123.45
_CHARACTER_N . . . . . . . . . . . . NUMBER 0x0004E NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:124.1-124.45
_CHARACTER_O . . . . . . . . . . . . NUMBER 0x0004F USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:125.1-125.45
_CHARACTER_P . . . . . . . . . . . . NUMBER 0x00050 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:126.1-126.45
_CHARACTER_Q . . . . . . . . . . . . NUMBER 0x00051 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:127.1-127.45
_CHARACTER_R . . . . . . . . . . . . NUMBER 0x00052 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:128.1-128.45
_CHARACTER_S . . . . . . . . . . . . NUMBER 0x00053 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:129.1-129.45
_CHARACTER_T . . . . . . . . . . . . NUMBER 0x00054 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:130.1-130.45
_CHARACTER_U . . . . . . . . . . . . NUMBER 0x00055 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:131.1-131.45
_CHARACTER_V . . . . . . . . . . . . NUMBER 0x00056 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:132.1-132.45
_CHARACTER_W . . . . . . . . . . . . NUMBER 0x00057 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:133.1-133.45
_CHARACTER_X . . . . . . . . . . . . NUMBER 0x00058 NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:134.1-134.45
_CHARACTER_Y . . . . . . . . . . . . NUMBER 0x00059 USED     CONSTANT    6041_example_14.ind_spaces.full_inst.asm:135.1-135.45
_CHARACTER_Z . . . . . . . . . . . . NUMBER 0x0005A NOT USED CONSTANT    6041_example_14.ind_spaces.full_inst.asm:136.1-136.45
