:WAIT_FOR.WAITING.1  . . . . . . . . LABEL  0x00002 USED     CONSTANT    LOCAL
:WAIT_FOR.WAITING.2  . . . . . . . . LABEL  0x00009 USED     CONSTANT    LOCAL
BTN  . . . . . . . . . . . . . . . . PORT   0x00002 USED     CONSTANT    Demotest.asm:11.1-11.39
BTN_I  . . . . . . . . . . . . . . . REG.   0x00001 USED     CONSTANT    Demotest.asm:14.1-14.24
LEDS . . . . . . . . . . . . . . . . PORT   0x00001 USED     CONSTANT    Demotest.asm:10.1-10.39
LED_I  . . . . . . . . . . . . . . . REG.   0x00000 USED     CONSTANT    Demotest.asm:13.1-13.24
MAIN . . . . . . . . . . . . . . . . LABEL  0x00005 USED     CONSTANT    Demotest.asm:49.1-49.6
S0 . . . . . . . . . . . . . . . . . REG.   0x00000 NOT USED CONSTANT    IMPLICIT
S1 . . . . . . . . . . . . . . . . . REG.   0x00001 NOT USED CONSTANT    IMPLICIT
S2 . . . . . . . . . . . . . . . . . REG.   0x00002 NOT USED CONSTANT    IMPLICIT
S3 . . . . . . . . . . . . . . . . . REG.   0x00003 NOT USED CONSTANT    IMPLICIT
S4 . . . . . . . . . . . . . . . . . REG.   0x00004 NOT USED CONSTANT    IMPLICIT
S5 . . . . . . . . . . . . . . . . . REG.   0x00005 NOT USED CONSTANT    IMPLICIT
S6 . . . . . . . . . . . . . . . . . REG.   0x00006 NOT USED CONSTANT    IMPLICIT
S7 . . . . . . . . . . . . . . . . . REG.   0x00007 NOT USED CONSTANT    IMPLICIT
S8 . . . . . . . . . . . . . . . . . REG.   0x00008 NOT USED CONSTANT    IMPLICIT
S9 . . . . . . . . . . . . . . . . . REG.   0x00009 NOT USED CONSTANT    IMPLICIT
SA . . . . . . . . . . . . . . . . . REG.   0x0000A NOT USED CONSTANT    IMPLICIT
SB . . . . . . . . . . . . . . . . . REG.   0x0000B NOT USED CONSTANT    IMPLICIT
SC . . . . . . . . . . . . . . . . . REG.   0x0000C NOT USED CONSTANT    IMPLICIT
SD . . . . . . . . . . . . . . . . . REG.   0x0000D USED     CONSTANT    IMPLICIT
SE . . . . . . . . . . . . . . . . . REG.   0x0000E USED     CONSTANT    IMPLICIT
SF . . . . . . . . . . . . . . . . . REG.   0x0000F USED     CONSTANT    IMPLICIT
START  . . . . . . . . . . . . . . . LABEL  0x00001 USED     CONSTANT    Demotest.asm:41.1-41.7
TEMP1  . . . . . . . . . . . . . . . REG.   0x0000E USED     CONSTANT    Demotest.asm:16.1-16.29
TEMP2  . . . . . . . . . . . . . . . REG.   0x0000F NOT USED CONSTANT    Demotest.asm:17.1-17.29
TEMP3  . . . . . . . . . . . . . . . REG.   0x0000D NOT USED CONSTANT    Demotest.asm:18.1-18.29
