
1 + 2 + 3 | "a + b + c"
1 + "2" + "3" + # + #d | "a + #b + # c + # + #d"
1, 2, 3 "__VA_ARGS__"
"1, 2, 3" "#__VA_ARGS__"
("1", 2, 3, 4) (1, "2"3, 4) (1, "2"  |3, 4) "(#a, b, __VA_ARGS__) (a, #b,   ##  __VA_ARGS__) (a, #b  |##__VA_ARGS__)"
("1", 2, ) (1, "2") (1, "2"  |) "(#a, b, __VA_ARGS__) (a, #b,   ##  __VA_ARGS__) (a, #b  |##__VA_ARGS__)"
(1, 2, 3, 4) ("1", 23, 4) "(a, b, c) (#a, b, ##c)"
(1, 2, ) ("1", 2) "(a, b, c) (#a, b, ##c)"
ghidefabc "abc ## def ## ghi"
abcdefghi123yyy xxx "abc##def   ##   ghi ## 123 ## ## yyy xxx"
(11,22,33) "(abc,def,ghi)"


int j[] = { 123, 45, 67, 89, 10, 11, 12,  };

